<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Alternative Tests for Treatment Effects | Design and Analysis of Experiments</title>
  <meta name="description" content="This is a course on Experimental Design and Analysis." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Alternative Tests for Treatment Effects | Design and Analysis of Experiments" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a course on Experimental Design and Analysis." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Alternative Tests for Treatment Effects | Design and Analysis of Experiments" />
  
  <meta name="twitter:description" content="This is a course on Experimental Design and Analysis." />
  

<meta name="author" content="Larry Winner" />


<meta name="date" content="2026-06-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="analysis-of-treatment-means.html"/>
<link rel="next" href="balanced-two-factor-designs.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STA 4211 Course Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html"><i class="fa fa-check"></i><b>1</b> Comparing Two Treatments or Populations</a>
<ul>
<li class="chapter" data-level="1.1" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#linear-functions-of-random-variables"><i class="fa fa-check"></i><b>1.1</b> Linear Functions of Random Variables</a></li>
<li class="chapter" data-level="1.2" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#students-t-distribution-for-making-inference-on-population-means"><i class="fa fa-check"></i><b>1.2</b> Student’s <span class="math inline">\(t\)</span>-Distribution for Making Inference on Population Means</a></li>
<li class="chapter" data-level="1.3" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#inference-for-the-population-mean-difference"><i class="fa fa-check"></i><b>1.3</b> Inference for the Population Mean Difference</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#inference-for-the-population-mean-difference-for-paired-samples"><i class="fa fa-check"></i><b>1.3.1</b> Inference for the Population Mean Difference for Paired Samples</a></li>
<li class="chapter" data-level="1.3.2" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#inference-for-the-population-mean-difference-for-independent-samples"><i class="fa fa-check"></i><b>1.3.2</b> Inference for the Population Mean Difference for Independent Samples</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#inference-for-the-population-variance-ratios"><i class="fa fa-check"></i><b>1.4</b> Inference for the Population Variance Ratios</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#inferences-for-variance-ratios-for-independent-samples"><i class="fa fa-check"></i><b>1.4.1</b> Inferences for Variance Ratios for Independent Samples</a></li>
<li class="chapter" data-level="1.4.2" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#test-for-equal-variances-with-paired-samples"><i class="fa fa-check"></i><b>1.4.2</b> Test for Equal Variances with Paired Samples</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#examples"><i class="fa fa-check"></i><b>1.5</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>2</b> Introduction</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction.html"><a href="introduction.html#terminology"><i class="fa fa-check"></i><b>2.1</b> Terminology</a></li>
<li class="chapter" data-level="2.2" data-path="introduction.html"><a href="introduction.html#basics-of-controlled-experiments"><i class="fa fa-check"></i><b>2.2</b> Basics of Controlled Experiments</a></li>
<li class="chapter" data-level="2.3" data-path="introduction.html"><a href="introduction.html#completely-randomized-design-crd"><i class="fa fa-check"></i><b>2.3</b> Completely Randomized Design (CRD)</a></li>
<li class="chapter" data-level="2.4" data-path="introduction.html"><a href="introduction.html#randomized-complete-block-design-rcbd-or-rbd"><i class="fa fa-check"></i><b>2.4</b> Randomized Complete Block Design (RCBD or RBD)</a></li>
<li class="chapter" data-level="2.5" data-path="introduction.html"><a href="introduction.html#overview-of-some-standard-experimental-designs"><i class="fa fa-check"></i><b>2.5</b> Overview of Some Standard Experimental Designs</a></li>
<li class="chapter" data-level="2.6" data-path="introduction.html"><a href="introduction.html#overview-of-observational-study-designs"><i class="fa fa-check"></i><b>2.6</b> Overview of Observational Study Designs</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="single-factor-studies.html"><a href="single-factor-studies.html"><i class="fa fa-check"></i><b>3</b> Single Factor Studies</a>
<ul>
<li class="chapter" data-level="3.1" data-path="single-factor-studies.html"><a href="single-factor-studies.html#models-with-r2-factor-levels"><i class="fa fa-check"></i><b>3.1</b> Models with <span class="math inline">\(r=2\)</span> Factor Levels</a></li>
<li class="chapter" data-level="3.2" data-path="single-factor-studies.html"><a href="single-factor-studies.html#three-model-formulations"><i class="fa fa-check"></i><b>3.2</b> Three Model Formulations</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="single-factor-studies.html"><a href="single-factor-studies.html#cell-means-model"><i class="fa fa-check"></i><b>3.2.1</b> Cell Means Model</a></li>
<li class="chapter" data-level="3.2.2" data-path="single-factor-studies.html"><a href="single-factor-studies.html#treatment-effects-model"><i class="fa fa-check"></i><b>3.2.2</b> Treatment Effects Model</a></li>
<li class="chapter" data-level="3.2.3" data-path="single-factor-studies.html"><a href="single-factor-studies.html#reference-group-model"><i class="fa fa-check"></i><b>3.2.3</b> Reference Group Model</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="single-factor-studies.html"><a href="single-factor-studies.html#the-analysis-of-variance-and-f-test"><i class="fa fa-check"></i><b>3.3</b> The Analysis of Variance and <span class="math inline">\(F\)</span>-test</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="single-factor-studies.html"><a href="single-factor-studies.html#general-linear-test-approach"><i class="fa fa-check"></i><b>3.3.1</b> General Linear Test Approach</a></li>
<li class="chapter" data-level="3.3.2" data-path="single-factor-studies.html"><a href="single-factor-studies.html#power-calculations"><i class="fa fa-check"></i><b>3.3.2</b> Power Calculations</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="single-factor-studies.html"><a href="single-factor-studies.html#technical-details"><i class="fa fa-check"></i><b>3.4</b> Technical Details</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="single-factor-studies.html"><a href="single-factor-studies.html#least-squares-estimation-for-the-cell-means-model-regression-approach"><i class="fa fa-check"></i><b>3.4.1</b> Least Squares Estimation for the Cell Means Model (Regression Approach)</a></li>
<li class="chapter" data-level="3.4.2" data-path="single-factor-studies.html"><a href="single-factor-studies.html#scalar-estimation-for-the-cell-means-model"><i class="fa fa-check"></i><b>3.4.2</b> Scalar Estimation for the Cell Means Model</a></li>
<li class="chapter" data-level="3.4.3" data-path="single-factor-studies.html"><a href="single-factor-studies.html#estimation-for-the-treatment-effects-model"><i class="fa fa-check"></i><b>3.4.3</b> Estimation for the Treatment Effects Model</a></li>
<li class="chapter" data-level="3.4.4" data-path="single-factor-studies.html"><a href="single-factor-studies.html#least-squares-estimation-regression-approach"><i class="fa fa-check"></i><b>3.4.4</b> Least Squares Estimation (Regression Approach)</a></li>
<li class="chapter" data-level="3.4.5" data-path="single-factor-studies.html"><a href="single-factor-studies.html#the-analysis-of-variance"><i class="fa fa-check"></i><b>3.4.5</b> The Analysis of Variance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html"><i class="fa fa-check"></i><b>4</b> Analysis of Treatment Means</a>
<ul>
<li class="chapter" data-level="4.1" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#individual-treatment-means"><i class="fa fa-check"></i><b>4.1</b> Individual Treatment Means</a></li>
<li class="chapter" data-level="4.2" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#comparing-two-treatment-means"><i class="fa fa-check"></i><b>4.2</b> Comparing Two Treatment Means</a></li>
<li class="chapter" data-level="4.3" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#contrasts-among-treatment-means"><i class="fa fa-check"></i><b>4.3</b> Contrasts Among Treatment Means</a></li>
<li class="chapter" data-level="4.4" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#simultaneous-comparisons"><i class="fa fa-check"></i><b>4.4</b> Simultaneous Comparisons</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#tukeys-honest-significant-difference-hsd"><i class="fa fa-check"></i><b>4.4.1</b> Tukey’s Honest Significant Difference (HSD)</a></li>
<li class="chapter" data-level="4.4.2" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#scheffes-method-for-multiple-comparisons"><i class="fa fa-check"></i><b>4.4.2</b> Scheffe’s Method for Multiple Comparisons</a></li>
<li class="chapter" data-level="4.4.3" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#bonferroni-method-for-multiple-comparisons"><i class="fa fa-check"></i><b>4.4.3</b> Bonferroni Method for Multiple Comparisons</a></li>
<li class="chapter" data-level="4.4.4" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#multiple-range-methods"><i class="fa fa-check"></i><b>4.4.4</b> Multiple Range Methods</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html"><i class="fa fa-check"></i><b>5</b> Alternative Tests for Treatment Effects</a>
<ul>
<li class="chapter" data-level="5.1" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#randomizationpermutation-tests"><i class="fa fa-check"></i><b>5.1</b> Randomization/Permutation Tests</a></li>
<li class="chapter" data-level="5.2" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#tests-for-equal-error-variances"><i class="fa fa-check"></i><b>5.2</b> Tests for Equal Error Variances</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#hartleys-test"><i class="fa fa-check"></i><b>5.2.1</b> Hartley’s Test</a></li>
<li class="chapter" data-level="5.2.2" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#levenes-test"><i class="fa fa-check"></i><b>5.2.2</b> Levene’s Test</a></li>
<li class="chapter" data-level="5.2.3" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#bartletts-test"><i class="fa fa-check"></i><b>5.2.3</b> Bartlett’s Test</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#remedial-measures"><i class="fa fa-check"></i><b>5.3</b> Remedial Measures</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#weighted-least-squares-and-welchs-test"><i class="fa fa-check"></i><b>5.3.1</b> Weighted Least Squares and Welch’s Test</a></li>
<li class="chapter" data-level="5.3.2" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#post-hoc-comparisons-with-unequal-variances"><i class="fa fa-check"></i><b>5.3.2</b> Post-hoc Comparisons with Unequal Variances</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#nonparametric-test-for-non-normal-data"><i class="fa fa-check"></i><b>5.4</b> Nonparametric Test for Non-normal Data</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html"><i class="fa fa-check"></i><b>6</b> Balanced Two Factor Designs</a>
<ul>
<li class="chapter" data-level="6.1" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#introduction-1"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#two-factor-analysis-of-variance"><i class="fa fa-check"></i><b>6.2</b> Two Factor Analysis of Variance</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#cell-means-and-factor-effects-models"><i class="fa fa-check"></i><b>6.2.1</b> Cell Means and Factor Effects Models</a></li>
<li class="chapter" data-level="6.2.2" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#least-squaresmaximum-likelihood-estimators"><i class="fa fa-check"></i><b>6.2.2</b> Least Squares/Maximum Likelihood Estimators</a></li>
<li class="chapter" data-level="6.2.3" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#sums-of-squares-and-the-analysis-of-variance"><i class="fa fa-check"></i><b>6.2.3</b> Sums of Squares and the Analysis of Variance</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#factor-effect-contrasts"><i class="fa fa-check"></i><b>6.3</b> Factor Effect Contrasts</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#contrasts-when-there-is-no-interaction"><i class="fa fa-check"></i><b>6.3.1</b> Contrasts when there is No Interaction</a></li>
<li class="chapter" data-level="6.3.2" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#contrasts-when-interaction-is-present"><i class="fa fa-check"></i><b>6.3.2</b> Contrasts when Interaction is Present</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="two-factor-designs-with-1-observation-per-treatment.html"><a href="two-factor-designs-with-1-observation-per-treatment.html"><i class="fa fa-check"></i><b>7</b> Two-Factor Designs with 1 Observation per Treatment</a></li>
<li class="chapter" data-level="8" data-path="unbalanced-two-factor-analysis-of-variance.html"><a href="unbalanced-two-factor-analysis-of-variance.html"><i class="fa fa-check"></i><b>8</b> Unbalanced Two-Factor Analysis of Variance</a>
<ul>
<li class="chapter" data-level="8.1" data-path="unbalanced-two-factor-analysis-of-variance.html"><a href="unbalanced-two-factor-analysis-of-variance.html#statistical-model-and-the-analysis-of-variance"><i class="fa fa-check"></i><b>8.1</b> Statistical Model and the Analysis of Variance</a></li>
<li class="chapter" data-level="8.2" data-path="unbalanced-two-factor-analysis-of-variance.html"><a href="unbalanced-two-factor-analysis-of-variance.html#least-squares-estimators-and-contrastslinear-functions-among-means"><i class="fa fa-check"></i><b>8.2</b> Least Squares Estimators and Contrasts/Linear Functions Among Means</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="higher-order-models.html"><a href="higher-order-models.html"><i class="fa fa-check"></i><b>9</b> Higher Order Models</a>
<ul>
<li class="chapter" data-level="9.1" data-path="higher-order-models.html"><a href="higher-order-models.html#three-factor-models---mean-structure"><i class="fa fa-check"></i><b>9.1</b> Three Factor Models - Mean Structure</a></li>
<li class="chapter" data-level="9.2" data-path="higher-order-models.html"><a href="higher-order-models.html#statistical-model-and-the-analysis-of-variance-1"><i class="fa fa-check"></i><b>9.2</b> Statistical Model and the Analysis of Variance</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="block-designs.html"><a href="block-designs.html"><i class="fa fa-check"></i><b>10</b> Block Designs</a>
<ul>
<li class="chapter" data-level="10.1" data-path="block-designs.html"><a href="block-designs.html#randomized-block-and-repeated-measures-designs"><i class="fa fa-check"></i><b>10.1</b> Randomized Block and Repeated Measures Designs</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="block-designs.html"><a href="block-designs.html#model-structure-and-estimators"><i class="fa fa-check"></i><b>10.1.1</b> Model Structure and Estimators</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="block-designs.html"><a href="block-designs.html#analysis-of-variance-and-the-f-test"><i class="fa fa-check"></i><b>10.2</b> Analysis of Variance and the <span class="math inline">\(F\)</span>-test</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="block-designs.html"><a href="block-designs.html#checking-model-assumptions"><i class="fa fa-check"></i><b>10.2.1</b> Checking Model Assumptions</a></li>
<li class="chapter" data-level="10.2.2" data-path="block-designs.html"><a href="block-designs.html#relative-efficiency-and-within-subject-variance-covariance-matrix"><i class="fa fa-check"></i><b>10.2.2</b> Relative Efficiency and Within-Subject Variance-Covariance Matrix</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="block-designs.html"><a href="block-designs.html#latin-square-designs"><i class="fa fa-check"></i><b>10.3</b> Latin Square Designs</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html"><i class="fa fa-check"></i><b>11</b> Random and Mixed Effects Models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#way-random-effects-model"><i class="fa fa-check"></i><b>11.1</b> 1-Way Random Effects Model</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#analysis-of-variance"><i class="fa fa-check"></i><b>11.1.1</b> Analysis of Variance</a></li>
<li class="chapter" data-level="11.1.2" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#estimating-the-population-mean-mu_bullet"><i class="fa fa-check"></i><b>11.1.2</b> Estimating the Population Mean <span class="math inline">\(\mu_{\bullet}\)</span></a></li>
<li class="chapter" data-level="11.1.3" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#estimating-the-intraclass-correlation-coefficient"><i class="fa fa-check"></i><b>11.1.3</b> Estimating the Intraclass Correlation Coefficient</a></li>
<li class="chapter" data-level="11.1.4" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#estimating-the-within-group-variance"><i class="fa fa-check"></i><b>11.1.4</b> Estimating the Within Group Variance</a></li>
<li class="chapter" data-level="11.1.5" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#estimating-the-between-group-variance"><i class="fa fa-check"></i><b>11.1.5</b> Estimating the Between Group Variance</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#two-way-random-effects-model"><i class="fa fa-check"></i><b>11.2</b> Two-Way Random Effects Model</a></li>
<li class="chapter" data-level="11.3" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#two-way-mixed-effects-model"><i class="fa fa-check"></i><b>11.3</b> Two-Way Mixed Effects Model</a></li>
<li class="chapter" data-level="11.4" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#three-way-mixed-effects-models"><i class="fa fa-check"></i><b>11.4</b> Three-Way Mixed Effects Models</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="nested-designs.html"><a href="nested-designs.html"><i class="fa fa-check"></i><b>12</b> Nested Designs</a>
<ul>
<li class="chapter" data-level="12.1" data-path="nested-designs.html"><a href="nested-designs.html#estimators-and-the-analysis-of-variance"><i class="fa fa-check"></i><b>12.1</b> Estimators and the Analysis of Variance</a></li>
<li class="chapter" data-level="12.2" data-path="nested-designs.html"><a href="nested-designs.html#tests-contrasts-and-pairwise-comparisons"><i class="fa fa-check"></i><b>12.2</b> Tests, Contrasts, and Pairwise Comparisons</a></li>
<li class="chapter" data-level="12.3" data-path="nested-designs.html"><a href="nested-designs.html#repeated-measures-design"><i class="fa fa-check"></i><b>12.3</b> Repeated Measures Design</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="nested-designs.html"><a href="nested-designs.html#model-structure"><i class="fa fa-check"></i><b>12.3.1</b> Model Structure</a></li>
<li class="chapter" data-level="12.3.2" data-path="nested-designs.html"><a href="nested-designs.html#analysis-of-variance-and-f-tests"><i class="fa fa-check"></i><b>12.3.2</b> Analysis of Variance and <span class="math inline">\(F\)</span>-tests</a></li>
<li class="chapter" data-level="12.3.3" data-path="nested-designs.html"><a href="nested-designs.html#treatment-comparisons"><i class="fa fa-check"></i><b>12.3.3</b> Treatment Comparisons</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-covariance-ancova.html"><a href="analysis-of-covariance-ancova.html"><i class="fa fa-check"></i><b>13</b> Analysis of Covariance (ANCOVA)</a>
<ul>
<li class="chapter" data-level="13.1" data-path="analysis-of-covariance-ancova.html"><a href="analysis-of-covariance-ancova.html#additive-model"><i class="fa fa-check"></i><b>13.1</b> Additive Model</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="analysis-of-covariance-ancova.html"><a href="analysis-of-covariance-ancova.html#adjusted-means"><i class="fa fa-check"></i><b>13.1.1</b> Adjusted means</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="analysis-of-covariance-ancova.html"><a href="analysis-of-covariance-ancova.html#interaction-model"><i class="fa fa-check"></i><b>13.2</b> Interaction Model</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="response-surface-and-mixture-designs.html"><a href="response-surface-and-mixture-designs.html"><i class="fa fa-check"></i><b>14</b> Response Surface and Mixture Designs</a>
<ul>
<li class="chapter" data-level="14.1" data-path="response-surface-and-mixture-designs.html"><a href="response-surface-and-mixture-designs.html#response-surface-designs"><i class="fa fa-check"></i><b>14.1</b> Response Surface Designs</a></li>
<li class="chapter" data-level="14.2" data-path="response-surface-and-mixture-designs.html"><a href="response-surface-and-mixture-designs.html#mixture-models"><i class="fa fa-check"></i><b>14.2</b> Mixture Models</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Design and Analysis of Experiments</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="alternative-tests-for-treatment-effects" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Alternative Tests for Treatment Effects<a href="alternative-tests-for-treatment-effects.html#alternative-tests-for-treatment-effects" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this chapter, we consider tests for the equality of variances among treatments/groups, as well as alternatives to the <span class="math inline">\(F\)</span>-test that are used in practice.</p>
<p>The tests for equal variances are <strong>Levene’s Test</strong>, <strong>Hartley’s Test</strong>, and <strong>Bartlett’s Test</strong>.</p>
<p>Alternatives to the <span class="math inline">\(F\)</span>-test are <strong>Randomization/Permutation Tests</strong>,
the <strong>Kruskal-Wallis Test</strong>, and <strong>Welch’s Test</strong>. Also, <strong>Weighted Least Squares</strong>
can be implemented with unequal variances.</p>
<p>Three departures of the model assumptions are briefly described below.</p>
<ul>
<li><strong>Non-normal Errors</strong> - This is generally not too problematic for the <span class="math inline">\(F\)</span>-test as long as data are not too far from normal with reasonable sample sizes</li>
<li><strong>Unequal Error Variances</strong> - As long as the sample sizes are approximately equal this is not a large problem for the <span class="math inline">\(F\)</span>-test, but can be an issue with very unbalanced designs.</li>
<li><strong>Non-independence of Error Terms</strong> This can cause issues for the <span class="math inline">\(F\)</span>-test. If each unit receives each treatment, we can get a stronger test based on a Repeated Measures Design.</li>
</ul>
<div id="randomizationpermutation-tests" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Randomization/Permutation Tests<a href="alternative-tests-for-treatment-effects.html#randomizationpermutation-tests" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>These tests are based on resampling, and make no assumptions on the distribution of the error terms. The test treats the units observed in the study as a finite population of units with fixed error terms <span class="math inline">\(\epsilon_{ij}\)</span>. The model and hypothesis are of the following forms.</p>
<p><span class="math display">\[
Y_{ij}=\mu_{\bullet} + \tau_i + \epsilon_{ij} \qquad \qquad  H_0:\tau_1=\cdots = \tau_r=0
\]</span>
The idea is that if this null hypothesis true, the observed values are due only to the units themselves and not to treatment/group differences. A statistic, such as
<span class="math inline">\(F^*\)</span> or <span class="math inline">\(SSTR\)</span> is computed and saved. Then,
many permutations of the <span class="math inline">\(n_T\)</span> responses are randomly assigned to the treatment labels of sizes <span class="math inline">\(n_1,\ldots,n_r\)</span>. The statistic is computed for each permutation and saved.
The <span class="math inline">\(P\)</span>-value is the number of more extreme values than the observed statistic plus 1,
divided by the number of permutations plus 1. That is, the observed value counts in both the numerator and denominator. Often the number of permutations is 9999 in practice.</p>
<p>This test is applied to the lifeboat training data here.</p>
<p><strong>Example 4.1 - Virtual Training for a Lifeboat Launching Task</strong></p>
<p>Here we will apply the Randomization test to the Lifeboat training data.
For the original sample, <span class="math inline">\(SSTR=65.664\)</span>. Note that for each permutation, the total sum of squares will be the same, <span class="math inline">\(SSTO=331.479\)</span>, so we can simply save <span class="math inline">\(SSTR\)</span> from each permuation, as opposed to computing <span class="math inline">\(F^*\)</span>. The R code and output are given below.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="alternative-tests-for-treatment-effects.html#cb118-1" tabindex="-1"></a>vt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/virtual_training.csv&quot;</span>)</span>
<span id="cb118-2"><a href="alternative-tests-for-treatment-effects.html#cb118-2" tabindex="-1"></a><span class="fu">head</span>(vt,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##   grp.trt procKnow
## 1       1   4.5614
## 2       1   6.6593</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="alternative-tests-for-treatment-effects.html#cb120-1" tabindex="-1"></a><span class="fu">attach</span>(vt)</span>
<span id="cb120-2"><a href="alternative-tests-for-treatment-effects.html#cb120-2" tabindex="-1"></a></span>
<span id="cb120-3"><a href="alternative-tests-for-treatment-effects.html#cb120-3" tabindex="-1"></a><span class="do">### Randomization Test</span></span>
<span id="cb120-4"><a href="alternative-tests-for-treatment-effects.html#cb120-4" tabindex="-1"></a>n.trt <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(procKnow, grp.trt, length))  <span class="do">### Obtain n_1,...,n_4</span></span>
<span id="cb120-5"><a href="alternative-tests-for-treatment-effects.html#cb120-5" tabindex="-1"></a>mean.trt <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(procKnow, grp.trt, mean)) <span class="do">### Obtain ybar_1,...,ybar_4</span></span>
<span id="cb120-6"><a href="alternative-tests-for-treatment-effects.html#cb120-6" tabindex="-1"></a>mean.all <span class="ot">&lt;-</span> <span class="fu">mean</span>(procKnow)                             <span class="do">### Obtain ybar</span></span>
<span id="cb120-7"><a href="alternative-tests-for-treatment-effects.html#cb120-7" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">length</span>(n.trt)                                     <span class="do">### r = #trts</span></span>
<span id="cb120-8"><a href="alternative-tests-for-treatment-effects.html#cb120-8" tabindex="-1"></a>n_T <span class="ot">&lt;-</span> <span class="fu">sum</span>(n.trt)                                      <span class="do">### n_T=Total sample size</span></span>
<span id="cb120-9"><a href="alternative-tests-for-treatment-effects.html#cb120-9" tabindex="-1"></a>(SSTR.obs <span class="ot">&lt;-</span> <span class="fu">sum</span>(n.trt <span class="sc">*</span> (mean.trt <span class="sc">-</span> mean.all)<span class="sc">^</span><span class="dv">2</span>))     <span class="do">### Compute the observed SSTR</span></span></code></pre></div>
<pre><code>## [1] 65.66393</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="alternative-tests-for-treatment-effects.html#cb122-1" tabindex="-1"></a>N.perm <span class="ot">&lt;-</span> <span class="dv">9999</span>                                         <span class="do">### # of permutation samples</span></span>
<span id="cb122-2"><a href="alternative-tests-for-treatment-effects.html#cb122-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)                                         <span class="do">### Set seed for reproducibility</span></span>
<span id="cb122-3"><a href="alternative-tests-for-treatment-effects.html#cb122-3" tabindex="-1"></a>SSTR.perm <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, N.perm)                            <span class="do">### Placeholder for SSTR&#39;s</span></span>
<span id="cb122-4"><a href="alternative-tests-for-treatment-effects.html#cb122-4" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N.perm) {</span>
<span id="cb122-5"><a href="alternative-tests-for-treatment-effects.html#cb122-5" tabindex="-1"></a>  perm <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n_T, n_T, <span class="at">replace=</span><span class="cn">FALSE</span>)            <span class="do">## Random permutation of 1:n_T</span></span>
<span id="cb122-6"><a href="alternative-tests-for-treatment-effects.html#cb122-6" tabindex="-1"></a>  Y.perm <span class="ot">&lt;-</span> procKnow[perm]                             <span class="do">## &quot;Sorts&quot; Y values by perm</span></span>
<span id="cb122-7"><a href="alternative-tests-for-treatment-effects.html#cb122-7" tabindex="-1"></a>  mean.trt.perm <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(Y.perm, grp.trt, mean))  <span class="do">## Obtain Perm trt means </span></span>
<span id="cb122-8"><a href="alternative-tests-for-treatment-effects.html#cb122-8" tabindex="-1"></a>  SSTR.perm[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(n.trt <span class="sc">*</span> (mean.trt.perm <span class="sc">-</span> mean.all)<span class="sc">^</span><span class="dv">2</span>)  <span class="do">## SSTR for perm sample</span></span>
<span id="cb122-9"><a href="alternative-tests-for-treatment-effects.html#cb122-9" tabindex="-1"></a>}</span>
<span id="cb122-10"><a href="alternative-tests-for-treatment-effects.html#cb122-10" tabindex="-1"></a></span>
<span id="cb122-11"><a href="alternative-tests-for-treatment-effects.html#cb122-11" tabindex="-1"></a>(perm.pvalue <span class="ot">&lt;-</span> (<span class="fu">sum</span>(SSTR.perm <span class="sc">&gt;=</span> SSTR.obs) <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> (N.perm <span class="sc">+</span> <span class="dv">1</span>))  <span class="do">## Permutation P-value</span></span></code></pre></div>
<pre><code>## [1] 0.005</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="alternative-tests-for-treatment-effects.html#cb124-1" tabindex="-1"></a><span class="do">## Histogram with vertical line at observed SSTR</span></span>
<span id="cb124-2"><a href="alternative-tests-for-treatment-effects.html#cb124-2" tabindex="-1"></a><span class="fu">hist</span>(SSTR.perm, <span class="at">breaks=</span><span class="st">&quot;Scott&quot;</span>, <span class="at">col=</span><span class="st">&quot;orange&quot;</span>, <span class="at">border=</span><span class="st">&quot;blue4&quot;</span>)</span>
<span id="cb124-3"><a href="alternative-tests-for-treatment-effects.html#cb124-3" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> SSTR.obs, <span class="at">col=</span><span class="st">&quot;green4&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_STA4211Notes1_files/figure-html/ch0401-1.png" width="672" /></p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="alternative-tests-for-treatment-effects.html#cb125-1" tabindex="-1"></a><span class="fu">detach</span>(vt)</span></code></pre></div>
<p>The <span class="math inline">\(P\)</span>-value is 0.005, which is well below 0.05. Only 49 permutations out of 9999 had larger values of <span class="math inline">\(SSTR\)</span> than the observed data. There is strong evidence of treatment effects.
<span class="math display">\[\nabla \]</span></p>
</div>
<div id="tests-for-equal-error-variances" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Tests for Equal Error Variances<a href="alternative-tests-for-treatment-effects.html#tests-for-equal-error-variances" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, we consider three widely used tests of equal variances among the treatments/groups. They are based on various assumptions and do not always provide the same conclusion. The three tests covered here are <strong>Hartley’s Test</strong>, <strong>Levene’s Test</strong>,
and <strong>Bartlett’s Test</strong>. All tests are testing the following hypotheses.</p>
<p><span class="math display">\[
H_0:\sigma_1^2=\cdots = \sigma_r^2 \qquad
H_A: \mbox{ Not all } \sigma_i^2 \mbox{ are equal}
\]</span></p>
<div id="hartleys-test" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Hartley’s Test<a href="alternative-tests-for-treatment-effects.html#hartleys-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This test is dependent on the errors being normally distributed.
Further, its derivation is based on equal sample sizes.
It uses a special table of critical values available in many textbooks and online. There is a R package that purports to generate the critical values, but I have had issues with certain sample sizes/numbers of treatments in obtaining results.</p>
<p>The test statistic <span class="math inline">\((H)\)</span> is simply the ratio of the largest to smallest variance (not standard deviation), and the critical values are indexed by the number of treatments/groups <span class="math inline">\((r)\)</span>
and the number of degrees of freedom for each sample variance <span class="math inline">\((n-1)\)</span>, where <span class="math inline">\(n\)</span> is the number of units per treatment.</p>
<p><strong>Example 4.2 - Virtual Training for a Lifeboat Launching Task</strong></p>
<p>For the lifeboat training experiment, there were <span class="math inline">\(r=4\)</span> treatments
and each sample size was <span class="math inline">\(n=16\)</span>. The sample standard deviations are given below.
The critical value for this test with <span class="math inline">\(\alpha=0.05\)</span>, <span class="math inline">\(r=4\)</span>, and <span class="math inline">\(n-1=15\)</span>
is <span class="math inline">\(H_{.95;4,15}=4.01\)</span>.</p>
<p><span class="math display">\[
s_1=1.94 \quad s_2=1.43 \quad s_3=2.82 \quad s_4=1.99
\qquad H^*=\frac{\max\left(s_i^2\right)}{\min\left(s_i^2\right)}=
\frac{(2.82)^2}{(1.43)^2}=3.89
\]</span></p>
<p>The test statistic is just below the critical value, so we fail to reject the hypothesis of equal variances.</p>
<p><span class="math display">\[ \nabla \]</span></p>
</div>
<div id="levenes-test" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Levene’s Test<a href="alternative-tests-for-treatment-effects.html#levenes-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This test, also known as the Brown-Forsythe test is robust to outliers
and does not require equal sample sizes. There are various versions, based on whether
deviations from group means or medians are used.
For each observation, we compute <span class="math inline">\(d_{ij}\)</span> as described here.</p>
<p><span class="math display">\[
d_{ij}= \left|Y_{ij}-\tilde{Y}_i\right| \qquad  
\tilde{Y}_i=\mbox{median}\left(Y_{i1},\ldots ,Y_{in_i}\right)
\]</span></p>
<p>Then an Analysis of Variance is applied to the <span class="math inline">\(d_{ij}\)</span>, with <span class="math inline">\(\overline{d}_{i\bullet}\)</span>
and <span class="math inline">\(\overline{d}_{\bullet\bullet}\)</span> being the treatment and overall means.</p>
<p><span class="math display">\[
SSTR_L = \sum_{i=1}^rn_i\left(\overline{d}_{i\bullet}-
\overline{d}_{\bullet\bullet}\right)^2  \qquad df_{TR}=r-1
\]</span></p>
<p><span class="math display">\[
SSE_L = \sum_{i=1}^r\sum_{j=1}^{n_i}\left(d_{ij}-\overline{d}_{i\bullet}\right)^2
\qquad df_E = n_T-r
\]</span></p>
<p>Then, just as when we tested for equality of means, we compute the <span class="math inline">\(F\)</span>-statistic and compare it with <span class="math inline">\(F_{1-\alpha;r-1,n_T-r}\)</span>.</p>
<p><span class="math display">\[
\mbox{Test Statistic:} \quad F_L^* = \frac{\left[\frac{SSTR_L}{r-1}\right]}
           {\left[\frac{SSE_L}{n_T-r}\right]} \qquad
\mbox{Rejection Region:} \quad F_L^* \ge F_{1-\alpha;r-1,n_T-r}
\]</span></p>
<p><strong>Example 4.3 - Virtual Training for a Lifeboat Launching Task </strong></p>
<p>We will first create the <span class="math inline">\(d_{ij}\)</span> “brute-force”, then use the <strong>leveneTest</strong> function in the
<strong>car</strong> package.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="alternative-tests-for-treatment-effects.html#cb126-1" tabindex="-1"></a>vt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/virtual_training.csv&quot;</span>)</span>
<span id="cb126-2"><a href="alternative-tests-for-treatment-effects.html#cb126-2" tabindex="-1"></a>n.trt <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(vt<span class="sc">$</span>procKnow, vt<span class="sc">$</span>grp.trt, length))      <span class="do">## n_1,...,n_4</span></span>
<span id="cb126-3"><a href="alternative-tests-for-treatment-effects.html#cb126-3" tabindex="-1"></a>med.trt <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(vt<span class="sc">$</span>procKnow, vt<span class="sc">$</span>grp.trt, median))    <span class="do">## med_1,...,med_4</span></span>
<span id="cb126-4"><a href="alternative-tests-for-treatment-effects.html#cb126-4" tabindex="-1"></a>vt<span class="sc">$</span>med.trt <span class="ot">&lt;-</span> <span class="fu">rep</span>(med.trt, n.trt)                    <span class="do">## Repeat med_1 n_1 times, ...</span></span>
<span id="cb126-5"><a href="alternative-tests-for-treatment-effects.html#cb126-5" tabindex="-1"></a><span class="fu">head</span>(vt, <span class="dv">3</span>); <span class="fu">tail</span>(vt, <span class="dv">3</span>)                  </span></code></pre></div>
<pre><code>##   grp.trt procKnow med.trt
## 1       1   4.5614 5.67085
## 2       1   6.6593 5.67085
## 3       1   5.6427 5.67085</code></pre>
<pre><code>##    grp.trt procKnow med.trt
## 62       4   3.2286  6.8485
## 63       4   6.5520  6.8485
## 64       4   9.8754  6.8485</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="alternative-tests-for-treatment-effects.html#cb129-1" tabindex="-1"></a>vt<span class="sc">$</span>d <span class="ot">&lt;-</span> <span class="fu">abs</span>(vt<span class="sc">$</span>procKnow<span class="sc">-</span>vt<span class="sc">$</span>med.trt)                  <span class="do">## Compute d_ij</span></span>
<span id="cb129-2"><a href="alternative-tests-for-treatment-effects.html#cb129-2" tabindex="-1"></a></span>
<span id="cb129-3"><a href="alternative-tests-for-treatment-effects.html#cb129-3" tabindex="-1"></a>lev.mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(d <span class="sc">~</span> <span class="fu">factor</span>(grp.trt), <span class="at">data=</span>vt)          <span class="do">## Run aov function on d_ij&#39;s</span></span>
<span id="cb129-4"><a href="alternative-tests-for-treatment-effects.html#cb129-4" tabindex="-1"></a><span class="fu">anova</span>(lev.mod)                                       <span class="do">## Levene&#39;s F-test output</span></span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: d
##                 Df  Sum Sq Mean Sq F value Pr(&gt;F)
## factor(grp.trt)  3  11.108  3.7026  2.1463 0.1038
## Residuals       60 103.506  1.7251</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="alternative-tests-for-treatment-effects.html#cb131-1" tabindex="-1"></a><span class="do">## leveneTest (using Y_ij&#39;s) from car package</span></span>
<span id="cb131-2"><a href="alternative-tests-for-treatment-effects.html#cb131-2" tabindex="-1"></a><span class="fu">leveneTest</span>(procKnow <span class="sc">~</span> <span class="fu">factor</span>(grp.trt), <span class="st">&quot;median&quot;</span>, <span class="at">data=</span>vt)  </span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##       Df F value Pr(&gt;F)
## group  3  2.1463 0.1038
##       60</code></pre>
<p>We fail to reject the null hypothesis of equal variances.
Note that we ran the <strong>leveneTest</strong> function on the <span class="math inline">\(Y_{ij}\)</span> values, not on the with the <span class="math inline">\(d_{ij}\)</span> values (it creates them internally).
<span class="math display">\[ \nabla \]</span></p>
</div>
<div id="bartletts-test" class="section level3 hasAnchor" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Bartlett’s Test<a href="alternative-tests-for-treatment-effects.html#bartletts-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Bartlett’s test is based on the residuals being normally distributed and can be used
in applications beyond ANOVA models, including regression models with categorical
predictors. It makes use of the individual variances
<span class="math inline">\(\left\{s_i^2\right\}\)</span> and the pooled <span class="math inline">\(MSE\)</span> to obtain
a chi-square statistic that is defined here.</p>
<p><span class="math display">\[
\mbox{Test Statistic:} \quad X_B^2 =
\frac{1}{C}\left[\left(n_T-r\right)\ln(MSE)-\sum_{i=1}^r\left(n_i-1\right)\ln\left(s_i^2\right)\right]
\]</span>
<span class="math display">\[
\mbox{where:}\quad
C=1+\frac{1}{3(r-1)}\left[\left(\sum_{i=1}^r\frac{1}{n_i-1}\right)-\left(\frac{1}{n_T-r}\right)\right]
\]</span></p>
<p><span class="math display">\[
\mbox{Rejection Region:} \quad
X_B^2 \ge \chi_{1-\alpha;r-1}^2 \qquad
P = P\left(\chi_{r-1}^2 \ge X_B^2\right)
\]</span></p>
<p><strong>Example 4.4 - Virtual Training for a Lifeboat Launching Task</strong></p>
<p>For the lifeboat training experiment, there were <span class="math inline">\(r=4\)</span> treatments
and each sample size was <span class="math inline">\(n=16\)</span>. The sample variances are given below.
The critical value for this test with <span class="math inline">\(\alpha=0.05\)</span> and <span class="math inline">\(r=4\)</span>
is <span class="math inline">\(\chi_{.95;4-1}=7.815\)</span>.</p>
<p><span class="math display">\[
s_1^2=3.764 \quad s_2^2=2.045 \quad s_3^2=7.952 \quad s_4^2=3.960
\qquad MSE=4.430
\]</span></p>
<p><span class="math display">\[
\left(n_T-r\right)\ln(MSE) = 89.304 \qquad
\sum_{i=1}^r\left(n_i-1\right)\ln\left(s_i^2\right)=82.358
\]</span></p>
<p><span class="math display">\[
C=1+\frac{1}{3(r-1)}\left[\left(\sum_{i=1}^r\frac{1}{n_i-1}\right)-\left(\frac{1}{n_T-r}\right)\right]=1+\frac{1}{9}\left[\frac{4}{16-1}-\frac{1}{64-4}\right]=1.028
\]</span></p>
<p><span class="math display">\[
\mbox{Test Statistic:} \quad X_B^2 = \frac{1}{1.028}(89.304-82.358)=6.757 \qquad
P=P\left(\chi_3^2 \ge 6.757\right)=.0801
\]</span></p>
<p>Finally, we use the <strong>bartlett.test</strong> function in R to conduct the test.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="alternative-tests-for-treatment-effects.html#cb133-1" tabindex="-1"></a>vt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/virtual_training.csv&quot;</span>)</span>
<span id="cb133-2"><a href="alternative-tests-for-treatment-effects.html#cb133-2" tabindex="-1"></a></span>
<span id="cb133-3"><a href="alternative-tests-for-treatment-effects.html#cb133-3" tabindex="-1"></a><span class="fu">bartlett.test</span>(procKnow <span class="sc">~</span> <span class="fu">factor</span>(grp.trt), <span class="at">data=</span>vt)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  procKnow by factor(grp.trt)
## Bartlett&#39;s K-squared = 6.7626, df = 3, p-value = 0.07986</code></pre>
<p><span class="math display">\[
\nabla
\]</span></p>
</div>
</div>
<div id="remedial-measures" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Remedial Measures<a href="alternative-tests-for-treatment-effects.html#remedial-measures" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, several procedures are considered for issues of normality and/or unequal variances among the error terms. Methods
will include <strong>Weighted Least Squares</strong> and <strong>Welch’s Test</strong> when the errors are normal, but the error variances are unequal (heteroscedastic).</p>
<p>When variances are non-normal and heteroscedastic, transformations can be applied to <span class="math inline">\(Y\)</span> that may solve both problems. These include the <strong>Box-Cox Transformation</strong>, and were covered in the Linear Regression course.</p>
<p>When the distributions are highly skewed, non-parametric tests can be conducted based on ranks. We will describe the <strong>Kruskal-Wallis Test</strong>.</p>
<div id="weighted-least-squares-and-welchs-test" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Weighted Least Squares and Welch’s Test<a href="alternative-tests-for-treatment-effects.html#weighted-least-squares-and-welchs-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Consider the following scenario and simulation.</p>
<ul>
<li>There are <span class="math inline">\(r=3\)</span> Treatments with equal means <span class="math inline">\(\left(\mu_1=\mu_2=\mu_3\right)\)</span></li>
<li>The Treatments have unequal standard deviations (and thus variances)</li>
<li>The Treatments have equal or unequal sample sizes</li>
</ul>
<p>Note that the null hypothesis <span class="math inline">\(H_0:\mu_1=\mu_2=\mu_3\)</span> holds, so optimally, the rejection rate based on the <span class="math inline">\(F\)</span>-test with significance level <span class="math inline">\(\alpha\)</span> should be approximately <span class="math inline">\(\alpha\)</span>. We will simulate datasets for the following scenarios, all with <span class="math inline">\(\mu=100\)</span> for all treatments, and normal error terms.</p>
<ul>
<li><strong>Scenario 1</strong> - <span class="math inline">\(n_1=n_2=n_3=20\quad \sigma_1=\sigma_2=\sigma_3=20\)</span> (standard assumptions)</li>
<li><strong>Scenario 2</strong> - <span class="math inline">\(n_1=n_2=n_3=20 \quad \sigma_1=10,\sigma_2=20,\sigma_3=30\)</span></li>
<li><strong>Scenario 3</strong> - <span class="math inline">\(n_1=10,n_2=20,n_3=30 \quad \sigma_1=10,\sigma_2=20,\sigma_3=30\)</span></li>
<li><strong>Scenario 4</strong> - <span class="math inline">\(n_1=30,n_2=20,n_3=10 \quad \sigma_1=10,\sigma_2=20,\sigma_3=30\)</span></li>
</ul>
<p>Each scenario will be run, and the rejection rate will be reported in each case. The program below is the same for each scenario with only the inputs for <strong>n</strong> and <strong>sigma</strong> changing.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="alternative-tests-for-treatment-effects.html#cb135-1" tabindex="-1"></a><span class="do">## Scenario 3</span></span>
<span id="cb135-2"><a href="alternative-tests-for-treatment-effects.html#cb135-2" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">100</span>,<span class="dv">3</span>)</span>
<span id="cb135-3"><a href="alternative-tests-for-treatment-effects.html#cb135-3" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">30</span>)   <span class="do">## Change these for various scenarios</span></span>
<span id="cb135-4"><a href="alternative-tests-for-treatment-effects.html#cb135-4" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">30</span>)       <span class="do">## Change these for various scenarios</span></span>
<span id="cb135-5"><a href="alternative-tests-for-treatment-effects.html#cb135-5" tabindex="-1"></a>y.grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">200</span>,.<span class="dv">025</span>)</span>
<span id="cb135-6"><a href="alternative-tests-for-treatment-effects.html#cb135-6" tabindex="-1"></a></span>
<span id="cb135-7"><a href="alternative-tests-for-treatment-effects.html#cb135-7" tabindex="-1"></a><span class="fu">plot</span>(y.grid, <span class="fu">dnorm</span>(y.grid,mu[<span class="dv">1</span>],sigma[<span class="dv">1</span>]), <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">col=</span><span class="st">&quot;red4&quot;</span>,<span class="at">lwd=</span><span class="fl">1.5</span>,</span>
<span id="cb135-8"><a href="alternative-tests-for-treatment-effects.html#cb135-8" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;y&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;density&quot;</span>)</span>
<span id="cb135-9"><a href="alternative-tests-for-treatment-effects.html#cb135-9" tabindex="-1"></a><span class="fu">lines</span>(y.grid, <span class="fu">dnorm</span>(y.grid,mu[<span class="dv">2</span>],sigma[<span class="dv">2</span>]), <span class="at">col=</span><span class="st">&quot;blue4&quot;</span>,<span class="at">lwd=</span><span class="fl">1.5</span>)</span>
<span id="cb135-10"><a href="alternative-tests-for-treatment-effects.html#cb135-10" tabindex="-1"></a><span class="fu">lines</span>(y.grid, <span class="fu">dnorm</span>(y.grid,mu[<span class="dv">3</span>],sigma[<span class="dv">3</span>]), <span class="at">col=</span><span class="st">&quot;green4&quot;</span>,<span class="at">lwd=</span><span class="fl">1.5</span>)</span>
<span id="cb135-11"><a href="alternative-tests-for-treatment-effects.html#cb135-11" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;n=10,sigma=10&quot;</span>,<span class="st">&quot;n=20,sigma=20&quot;</span>,<span class="st">&quot;n=30,sigma=30&quot;</span>),</span>
<span id="cb135-12"><a href="alternative-tests-for-treatment-effects.html#cb135-12" tabindex="-1"></a>     <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;red4&quot;</span>, <span class="st">&quot;blue4&quot;</span>, <span class="st">&quot;green4&quot;</span>), <span class="at">lty=</span><span class="dv">1</span>, <span class="at">lwd=</span><span class="fl">1.5</span>)</span></code></pre></div>
<p><img src="bookdownproj_STA4211Notes1_files/figure-html/ch0404-1.png" width="672" /></p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="alternative-tests-for-treatment-effects.html#cb136-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">32611</span>)</span>
<span id="cb136-2"><a href="alternative-tests-for-treatment-effects.html#cb136-2" tabindex="-1"></a>N.samp <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb136-3"><a href="alternative-tests-for-treatment-effects.html#cb136-3" tabindex="-1"></a>n_T <span class="ot">&lt;-</span> <span class="fu">sum</span>(n)</span>
<span id="cb136-4"><a href="alternative-tests-for-treatment-effects.html#cb136-4" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">length</span>(n)</span>
<span id="cb136-5"><a href="alternative-tests-for-treatment-effects.html#cb136-5" tabindex="-1"></a>trt.grp <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="fu">c</span>(n[<span class="dv">1</span>],n[<span class="dv">2</span>],n[<span class="dv">3</span>]))</span>
<span id="cb136-6"><a href="alternative-tests-for-treatment-effects.html#cb136-6" tabindex="-1"></a>F.stat <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,N.samp)</span>
<span id="cb136-7"><a href="alternative-tests-for-treatment-effects.html#cb136-7" tabindex="-1"></a></span>
<span id="cb136-8"><a href="alternative-tests-for-treatment-effects.html#cb136-8" tabindex="-1"></a><span class="cf">for</span> (i1 <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N.samp) {  </span>
<span id="cb136-9"><a href="alternative-tests-for-treatment-effects.html#cb136-9" tabindex="-1"></a>  y1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n[<span class="dv">1</span>],mu[<span class="dv">1</span>],sigma[<span class="dv">1</span>])</span>
<span id="cb136-10"><a href="alternative-tests-for-treatment-effects.html#cb136-10" tabindex="-1"></a>  y2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n[<span class="dv">2</span>],mu[<span class="dv">2</span>],sigma[<span class="dv">2</span>])</span>
<span id="cb136-11"><a href="alternative-tests-for-treatment-effects.html#cb136-11" tabindex="-1"></a>  y3 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n[<span class="dv">3</span>],mu[<span class="dv">3</span>],sigma[<span class="dv">3</span>])</span>
<span id="cb136-12"><a href="alternative-tests-for-treatment-effects.html#cb136-12" tabindex="-1"></a>  y123 <span class="ot">&lt;-</span> <span class="fu">c</span>(y1,y2,y3)</span>
<span id="cb136-13"><a href="alternative-tests-for-treatment-effects.html#cb136-13" tabindex="-1"></a>  ybar1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(y1); var1 <span class="ot">&lt;-</span> <span class="fu">var</span>(y1)</span>
<span id="cb136-14"><a href="alternative-tests-for-treatment-effects.html#cb136-14" tabindex="-1"></a>  ybar2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(y2); var2 <span class="ot">&lt;-</span> <span class="fu">var</span>(y2)</span>
<span id="cb136-15"><a href="alternative-tests-for-treatment-effects.html#cb136-15" tabindex="-1"></a>  ybar3 <span class="ot">&lt;-</span> <span class="fu">mean</span>(y3); var3 <span class="ot">&lt;-</span> <span class="fu">var</span>(y3)</span>
<span id="cb136-16"><a href="alternative-tests-for-treatment-effects.html#cb136-16" tabindex="-1"></a>  ybar123 <span class="ot">&lt;-</span> <span class="fu">mean</span>(y123)</span>
<span id="cb136-17"><a href="alternative-tests-for-treatment-effects.html#cb136-17" tabindex="-1"></a>  SSTR <span class="ot">&lt;-</span> n[<span class="dv">1</span>]<span class="sc">*</span>(ybar1<span class="sc">-</span>ybar123)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> n[<span class="dv">2</span>]<span class="sc">*</span>(ybar2<span class="sc">-</span>ybar123)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> </span>
<span id="cb136-18"><a href="alternative-tests-for-treatment-effects.html#cb136-18" tabindex="-1"></a>          n[<span class="dv">3</span>]<span class="sc">*</span>(ybar3<span class="sc">-</span>ybar123)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb136-19"><a href="alternative-tests-for-treatment-effects.html#cb136-19" tabindex="-1"></a>  SSE <span class="ot">&lt;-</span> (n[<span class="dv">1</span>]<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span>var1 <span class="sc">+</span> (n[<span class="dv">2</span>]<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span>var2 <span class="sc">+</span> (n[<span class="dv">3</span>]<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span>var3</span>
<span id="cb136-20"><a href="alternative-tests-for-treatment-effects.html#cb136-20" tabindex="-1"></a>  F.stat[i1] <span class="ot">&lt;-</span> ( (SSTR<span class="sc">/</span>(r<span class="dv">-1</span>)) <span class="sc">/</span> (SSE<span class="sc">/</span>(n_T<span class="sc">-</span>r)) )</span>
<span id="cb136-21"><a href="alternative-tests-for-treatment-effects.html#cb136-21" tabindex="-1"></a>}</span>
<span id="cb136-22"><a href="alternative-tests-for-treatment-effects.html#cb136-22" tabindex="-1"></a></span>
<span id="cb136-23"><a href="alternative-tests-for-treatment-effects.html#cb136-23" tabindex="-1"></a><span class="fu">summary</span>(F.stat)</span></code></pre></div>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## 4.730e-05 1.601e-01 4.145e-01 6.918e-01 9.044e-01 1.322e+01</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="alternative-tests-for-treatment-effects.html#cb138-1" tabindex="-1"></a><span class="fu">mean</span>(F.stat <span class="sc">&gt;=</span> <span class="fu">qf</span>(.<span class="dv">95</span>,r<span class="dv">-1</span>,n_T<span class="sc">-</span>r))</span></code></pre></div>
<pre><code>## [1] 0.022</code></pre>
<p>Each scenario was run on 10000 simulated data sets with <span class="math inline">\(\alpha=0.05\)</span>. The following results were obtained based on the seed 32611.</p>
<ul>
<li><strong>Scenario 1</strong> - Equal variances, Equal sample sizes. Rejection Rate = .0513</li>
<li><strong>Scenario 2</strong> - Unequal variances, Equal sample sizes. Rejection Rate = .0573</li>
<li><strong>Scenario 3</strong> - Increasing variances, Increasing sample sizes. Rejection Rate = .0220.</li>
<li><strong>Scenario 4</strong> - Increasing variances, Decreasing sample sizes. Rejection Rate = .1637</li>
</ul>
<p>The primary result is that as long as sample sizes are equal (or very similar), the <span class="math inline">\(F\)</span>-test performs well whether the variances are equal or not (both Scenarios 1 and 2 have rejection rates close to <span class="math inline">\(\alpha\)</span>).</p>
<p>When the sample sizes are positively correlated with the variance (Scenario 3),
the rejection rate was well below <span class="math inline">\(\alpha\)</span> <span class="math inline">\((.0220&lt;.05)\)</span>. Thus, when the larger (smaller) samples correspond to the larger (smaller) variances the <span class="math inline">\(F\)</span>-test rejects less often than it should.</p>
<p>When the sample sizes are negatively correlated with the variance (Scenario 4),
the rejection rate was well above <span class="math inline">\(\alpha\)</span> <span class="math inline">\((.1637&gt;.05)\)</span>. Thus, when the smaller (larger) samples correspond to the larger (smaller) variances the <span class="math inline">\(F\)</span>-test rejects more often than it should.</p>
<p><strong>Estimated Weighted Least Squares</strong> can be used when the error variances are unequal. The estimated weights for the individual measurements is the reciprocal of the variance of the measurements within that treatment/group, <span class="math inline">\(w_{ij}=1/s_i^2\)</span>. It is much easier doing direct computations in matrix form than in scalar form. A sketch of the method is given below for the cell means model with balanced data: <span class="math inline">\(n_1=\cdots=n_r=n\)</span>, although it can be easily generalized for unequal sample sizes.
Let <span class="math inline">\(I_n\)</span> be the <span class="math inline">\(n\times n\)</span> identity matrix and <span class="math inline">\(0_n\)</span>
be the <span class="math inline">\(n\times n\)</span> matrix of <span class="math inline">\(0^s\)</span>. The <span class="math inline">\(n_T\times r\)</span> matrix <span class="math inline">\(X\)</span> and
the <span class="math inline">\(n_T\times 1\)</span> vector <span class="math inline">\(Y\)</span> are described in Chapter 2.</p>
<p><span class="math display">\[
\hat{V}=
\begin{bmatrix}
s_1^2I_n &amp; 0_n &amp; \cdots &amp; 0_n \\
0_n &amp; s_2^2I_n &amp; \cdots &amp; 0_n \\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0_n &amp; 0_n &amp; \cdots &amp; s_r^2I_n \\
\end{bmatrix}
\qquad
X^*=\hat{V}^{-1/2}X
\qquad
Y^*=\hat{V}^{-1/2}Y
\]</span></p>
<p><span class="math display">\[
H^*=
X^*\left(X^{*&#39;}X^*\right)
^{-1}X^{*&#39;}
\qquad
SSE_W(F)=Y^{*&#39;}\left(I_{n_T}-H^*\right)Y^* \quad df_E(F)=n_T-r
\]</span>
Under the null hypothesis <span class="math inline">\(H_0:\mu_1=\cdots\mu_r=\mu\)</span>, the <span class="math inline">\(X_0\)</span> matrix is the <span class="math inline">\(n_T\times 1\)</span> vector of <span class="math inline">\(1^s\)</span>. In this (null) case we obtain the reduced <span class="math inline">\(SSE\)</span> below.</p>
<p><span class="math display">\[
X_0^*=\hat{V}^{-1/2}X_0 \quad
H_0^*=
X_0^*\left(X_0^{*&#39;}X_0^*\right)
^{-1}X_0^{*&#39;}
\qquad
SSE_W(R)=Y^{*&#39;}\left(I_{n_T}-H_0^*\right)Y^* \quad df_E(R)=n_T-1
\]</span>
The test statistic and rejection region for the general linear test are given below.</p>
<p><span class="math display">\[
\mbox{Test Statistic:} \quad F_{EWLS}^*=
\frac{ \left[\frac{\left(SSE_W(R)-SSE_W(F)\right)}
      {\left(n_T-1\right)-\left(n_T-r\right)}\right]}
      {\left[\frac{SSE_W(F)}{n_T-r}\right]}
\qquad
\mbox{Rejection Region:} F_{EWLS}^* \ge F_{1-\alpha,r-1,n_T-r}
\]</span></p>
<p><strong>Example 4.5 - Virtual Training for a Lifeboat Launching Task</strong></p>
<p>For the lifeboat training experiment, there were <span class="math inline">\(r=4\)</span> treatments
and each sample size was <span class="math inline">\(n=16\)</span>. The following R code
runs the matrix form of the general linear test and
obtains the sample standard deviation by treatment and creates <span class="math inline">\(\hat{V}^{-1/2}\)</span> matrix
and runs the generalized linear test directly. Then the model is fit
using the <strong>weight</strong> command in the <strong>aov</strong> function.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="alternative-tests-for-treatment-effects.html#cb140-1" tabindex="-1"></a>vt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/virtual_training.csv&quot;</span>)</span>
<span id="cb140-2"><a href="alternative-tests-for-treatment-effects.html#cb140-2" tabindex="-1"></a><span class="do">### Matrix form</span></span>
<span id="cb140-3"><a href="alternative-tests-for-treatment-effects.html#cb140-3" tabindex="-1"></a>Vhat_12 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">64</span><span class="sc">^</span><span class="dv">2</span>),<span class="at">ncol=</span><span class="dv">64</span>)        <span class="do">## Construct estimated V^{-1/2} matrix</span></span>
<span id="cb140-4"><a href="alternative-tests-for-treatment-effects.html#cb140-4" tabindex="-1"></a>trt.sd <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(vt<span class="sc">$</span>procKnow, vt<span class="sc">$</span>grp.trt, sd))    <span class="do">## Obtain s_1,...,s_4</span></span>
<span id="cb140-5"><a href="alternative-tests-for-treatment-effects.html#cb140-5" tabindex="-1"></a><span class="do">## V^{-1/2} matrix = diag{1/s_i}</span></span>
<span id="cb140-6"><a href="alternative-tests-for-treatment-effects.html#cb140-6" tabindex="-1"></a>Vhat_12[<span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>] <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">/</span>trt.sd[<span class="dv">1</span>])<span class="sc">*</span><span class="fu">diag</span>(<span class="dv">16</span>)             </span>
<span id="cb140-7"><a href="alternative-tests-for-treatment-effects.html#cb140-7" tabindex="-1"></a>Vhat_12[<span class="dv">17</span><span class="sc">:</span><span class="dv">32</span>,<span class="dv">17</span><span class="sc">:</span><span class="dv">32</span>] <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">/</span>trt.sd[<span class="dv">2</span>])<span class="sc">*</span><span class="fu">diag</span>(<span class="dv">16</span>)</span>
<span id="cb140-8"><a href="alternative-tests-for-treatment-effects.html#cb140-8" tabindex="-1"></a>Vhat_12[<span class="dv">33</span><span class="sc">:</span><span class="dv">48</span>,<span class="dv">33</span><span class="sc">:</span><span class="dv">48</span>] <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">/</span>trt.sd[<span class="dv">3</span>])<span class="sc">*</span><span class="fu">diag</span>(<span class="dv">16</span>)</span>
<span id="cb140-9"><a href="alternative-tests-for-treatment-effects.html#cb140-9" tabindex="-1"></a>Vhat_12[<span class="dv">49</span><span class="sc">:</span><span class="dv">64</span>,<span class="dv">49</span><span class="sc">:</span><span class="dv">64</span>] <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">/</span>trt.sd[<span class="dv">4</span>])<span class="sc">*</span><span class="fu">diag</span>(<span class="dv">16</span>)</span>
<span id="cb140-10"><a href="alternative-tests-for-treatment-effects.html#cb140-10" tabindex="-1"></a></span>
<span id="cb140-11"><a href="alternative-tests-for-treatment-effects.html#cb140-11" tabindex="-1"></a>one <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">16</span>),<span class="at">ncol=</span><span class="dv">1</span>)         <span class="do">## 16x1 vector of 1&#39;s</span></span>
<span id="cb140-12"><a href="alternative-tests-for-treatment-effects.html#cb140-12" tabindex="-1"></a>zero <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">16</span>),<span class="at">ncol=</span><span class="dv">1</span>)        <span class="do">## 16x1 vector of 0&#39;s</span></span>
<span id="cb140-13"><a href="alternative-tests-for-treatment-effects.html#cb140-13" tabindex="-1"></a><span class="do">## Construct X matrix for cell means model</span></span>
<span id="cb140-14"><a href="alternative-tests-for-treatment-effects.html#cb140-14" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">rbind</span>(one,zero,zero,zero),</span>
<span id="cb140-15"><a href="alternative-tests-for-treatment-effects.html#cb140-15" tabindex="-1"></a>           <span class="fu">rbind</span>(zero,one,zero,zero),</span>
<span id="cb140-16"><a href="alternative-tests-for-treatment-effects.html#cb140-16" tabindex="-1"></a>           <span class="fu">rbind</span>(zero,zero,one,zero),</span>
<span id="cb140-17"><a href="alternative-tests-for-treatment-effects.html#cb140-17" tabindex="-1"></a>           <span class="fu">rbind</span>(zero,zero,zero,one))</span>
<span id="cb140-18"><a href="alternative-tests-for-treatment-effects.html#cb140-18" tabindex="-1"></a>Y <span class="ot">&lt;-</span> vt<span class="sc">$</span>procKnow</span>
<span id="cb140-19"><a href="alternative-tests-for-treatment-effects.html#cb140-19" tabindex="-1"></a>Xstar <span class="ot">&lt;-</span> Vhat_12 <span class="sc">%*%</span> X                                     <span class="do">## X*</span></span>
<span id="cb140-20"><a href="alternative-tests-for-treatment-effects.html#cb140-20" tabindex="-1"></a>Ystar <span class="ot">&lt;-</span> Vhat_12 <span class="sc">%*%</span> Y                                     <span class="do">## Y*</span></span>
<span id="cb140-21"><a href="alternative-tests-for-treatment-effects.html#cb140-21" tabindex="-1"></a>Hstar <span class="ot">&lt;-</span> Xstar <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">t</span>(Xstar)<span class="sc">%*%</span>Xstar) <span class="sc">%*%</span> <span class="fu">t</span>(Xstar)    <span class="do">## H*</span></span>
<span id="cb140-22"><a href="alternative-tests-for-treatment-effects.html#cb140-22" tabindex="-1"></a>I_64 <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="dv">64</span>)                                           <span class="do">## I_64</span></span>
<span id="cb140-23"><a href="alternative-tests-for-treatment-effects.html#cb140-23" tabindex="-1"></a>SSE_W.F <span class="ot">&lt;-</span> <span class="fu">t</span>(Ystar) <span class="sc">%*%</span> (I_64<span class="sc">-</span>Hstar) <span class="sc">%*%</span> Ystar             <span class="do">## SSE_W(F)</span></span>
<span id="cb140-24"><a href="alternative-tests-for-treatment-effects.html#cb140-24" tabindex="-1"></a>dfE.F <span class="ot">&lt;-</span> <span class="dv">64-4</span>                                              <span class="do">## df_E(F)</span></span>
<span id="cb140-25"><a href="alternative-tests-for-treatment-effects.html#cb140-25" tabindex="-1"></a></span>
<span id="cb140-26"><a href="alternative-tests-for-treatment-effects.html#cb140-26" tabindex="-1"></a>X_0 <span class="ot">&lt;-</span> <span class="fu">rbind</span>(one,one,one,one)                                      <span class="do">## X_0</span></span>
<span id="cb140-27"><a href="alternative-tests-for-treatment-effects.html#cb140-27" tabindex="-1"></a>Xstar_0 <span class="ot">&lt;-</span> Vhat_12 <span class="sc">%*%</span> X_0                                         <span class="do">## X_0*</span></span>
<span id="cb140-28"><a href="alternative-tests-for-treatment-effects.html#cb140-28" tabindex="-1"></a>Hstar_0 <span class="ot">&lt;-</span> Xstar_0 <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">t</span>(Xstar_0)<span class="sc">%*%</span>Xstar_0) <span class="sc">%*%</span> <span class="fu">t</span>(Xstar_0)  <span class="do">## H_0*</span></span>
<span id="cb140-29"><a href="alternative-tests-for-treatment-effects.html#cb140-29" tabindex="-1"></a>SSE_W.R <span class="ot">&lt;-</span> <span class="fu">t</span>(Ystar) <span class="sc">%*%</span> (I_64<span class="sc">-</span>Hstar_0) <span class="sc">%*%</span> Ystar                   <span class="do">## SSE_W(R)</span></span>
<span id="cb140-30"><a href="alternative-tests-for-treatment-effects.html#cb140-30" tabindex="-1"></a>dfE.R <span class="ot">&lt;-</span> <span class="dv">64-1</span>                                                      <span class="do">## df_E(R)</span></span>
<span id="cb140-31"><a href="alternative-tests-for-treatment-effects.html#cb140-31" tabindex="-1"></a></span>
<span id="cb140-32"><a href="alternative-tests-for-treatment-effects.html#cb140-32" tabindex="-1"></a><span class="do">## EWLS F-test and Output</span></span>
<span id="cb140-33"><a href="alternative-tests-for-treatment-effects.html#cb140-33" tabindex="-1"></a>F_EWLS <span class="ot">&lt;-</span> ((SSE_W.R<span class="sc">-</span>SSE_W.F) <span class="sc">/</span> (dfE.R<span class="sc">-</span>dfE.F)) <span class="sc">/</span> (SSE_W.F<span class="sc">/</span>dfE.F)</span>
<span id="cb140-34"><a href="alternative-tests-for-treatment-effects.html#cb140-34" tabindex="-1"></a>WLS.out <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dfE.F,dfE.R,SSE_W.F,SSE_W.R,F_EWLS,<span class="fu">qf</span>(.<span class="dv">95</span>,dfE.R<span class="sc">-</span>dfE.F,dfE.F),</span>
<span id="cb140-35"><a href="alternative-tests-for-treatment-effects.html#cb140-35" tabindex="-1"></a>                 <span class="dv">1</span><span class="sc">-</span><span class="fu">pf</span>(F_EWLS,dfE.R<span class="sc">-</span>dfE.F,dfE.F))</span>
<span id="cb140-36"><a href="alternative-tests-for-treatment-effects.html#cb140-36" tabindex="-1"></a><span class="fu">colnames</span>(WLS.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;df(F)&quot;</span>, <span class="st">&quot;df(R)&quot;</span>, <span class="st">&quot;SSE(F)&quot;</span>, <span class="st">&quot;SSE(R)&quot;</span>, <span class="st">&quot;F*&quot;</span>,<span class="st">&quot;F(.95)&quot;</span>, <span class="st">&quot;P(&gt;F*)&quot;</span>)</span>
<span id="cb140-37"><a href="alternative-tests-for-treatment-effects.html#cb140-37" tabindex="-1"></a><span class="fu">rownames</span>(WLS.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;EWLS&quot;</span>)</span>
<span id="cb140-38"><a href="alternative-tests-for-treatment-effects.html#cb140-38" tabindex="-1"></a><span class="fu">round</span>(WLS.out,<span class="dv">4</span>)</span></code></pre></div>
<pre><code>##      df(F) df(R) SSE(F)  SSE(R)     F* F(.95) P(&gt;F*)
## EWLS    60    63     60 81.3196 7.1065 2.7581  4e-04</code></pre>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="alternative-tests-for-treatment-effects.html#cb142-1" tabindex="-1"></a><span class="do">##################################################################</span></span>
<span id="cb142-2"><a href="alternative-tests-for-treatment-effects.html#cb142-2" tabindex="-1"></a><span class="do">## Using aov function with treatment variances as weights</span></span>
<span id="cb142-3"><a href="alternative-tests-for-treatment-effects.html#cb142-3" tabindex="-1"></a><span class="do">## Obtain treatment sample sizes and variances  </span></span>
<span id="cb142-4"><a href="alternative-tests-for-treatment-effects.html#cb142-4" tabindex="-1"></a>n.trt <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(vt<span class="sc">$</span>procKnow, vt<span class="sc">$</span>grp.trt, length))</span>
<span id="cb142-5"><a href="alternative-tests-for-treatment-effects.html#cb142-5" tabindex="-1"></a>var.trt <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(vt<span class="sc">$</span>procKnow, vt<span class="sc">$</span>grp.trt, var))</span>
<span id="cb142-6"><a href="alternative-tests-for-treatment-effects.html#cb142-6" tabindex="-1"></a></span>
<span id="cb142-7"><a href="alternative-tests-for-treatment-effects.html#cb142-7" tabindex="-1"></a><span class="do">## String out weights = 1/var so that weight i is replicated n_i times</span></span>
<span id="cb142-8"><a href="alternative-tests-for-treatment-effects.html#cb142-8" tabindex="-1"></a>vt<span class="sc">$</span>virt.wt <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">/</span>var.trt, n.trt)</span>
<span id="cb142-9"><a href="alternative-tests-for-treatment-effects.html#cb142-9" tabindex="-1"></a></span>
<span id="cb142-10"><a href="alternative-tests-for-treatment-effects.html#cb142-10" tabindex="-1"></a><span class="do">## Weighted Least Squares ANOVA</span></span>
<span id="cb142-11"><a href="alternative-tests-for-treatment-effects.html#cb142-11" tabindex="-1"></a>aov.wt <span class="ot">&lt;-</span> <span class="fu">aov</span>(procKnow <span class="sc">~</span> <span class="fu">factor</span>(grp.trt), <span class="at">weight=</span>virt.wt, <span class="at">data=</span>vt)</span>
<span id="cb142-12"><a href="alternative-tests-for-treatment-effects.html#cb142-12" tabindex="-1"></a><span class="fu">anova</span>(aov.wt)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: procKnow
##                 Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## factor(grp.trt)  3  21.32  7.1065  7.1065 0.0003655 ***
## Residuals       60  60.00  1.0000                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="alternative-tests-for-treatment-effects.html#cb144-1" tabindex="-1"></a><span class="do">## Ordinary Least Squares ANOVA</span></span>
<span id="cb144-2"><a href="alternative-tests-for-treatment-effects.html#cb144-2" tabindex="-1"></a>aov.nwt <span class="ot">&lt;-</span> <span class="fu">aov</span>(procKnow <span class="sc">~</span> <span class="fu">factor</span>(grp.trt), <span class="at">data=</span>vt)</span>
<span id="cb144-3"><a href="alternative-tests-for-treatment-effects.html#cb144-3" tabindex="-1"></a><span class="fu">anova</span>(aov.nwt)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: procKnow
##                 Df  Sum Sq Mean Sq F value   Pr(&gt;F)   
## factor(grp.trt)  3  65.664 21.8880  4.9406 0.003931 **
## Residuals       60 265.815  4.4302                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><span class="math display">\[ \nabla \]</span></p>
<p><strong>Welch’s Test</strong> was developed to handle the issues that arise in Scenarios 3 and 4 above.
The method involves computing a weighted <span class="math inline">\(F\)</span>-statistic for testing for treatment effects. The weights for the treatment means are the reciprocals of their variances,
<span class="math inline">\(w_i=n_i/s_i^2\)</span>. The procedure (which is easy to run in a spreadsheet or statistical package) computes the weighted <span class="math inline">\(F\)</span>-statistic and generates multiples of that statistic and the error degrees of freedom to achieve an approximate <span class="math inline">\(F\)</span>-distribution for the test statistic.</p>
<p>A sketch of the calculations is given below. Note that all calculations are based on the treatment/group sample sizes, means, and variances.</p>
<p><span class="math display">\[
w_i = \frac{n_i}{s_i^2}  \quad w_{\bullet}=\sum_{i=1}^rw_i \quad
C_W=\sum_{i=1}^r\left[\frac{1}{n_i-1}\left(1-\frac{w_i}{w_{\bullet}}\right)
\right] \quad m_W=\left[1+\frac{2(r-2)}{r^2-1}C_W\right]^{-1}
\]</span></p>
<p><span class="math display">\[
F^*=\frac{1}{r-1}\left[\sum_{i=1}^rw_i\left(\overline{y}_{i\bullet}\right)^2
- \frac{\left(\sum_{i=1}^rw_i\overline{y}_{i\bullet}\right)^2}{w_{\bullet}}\right]
\qquad\qquad \nu_W=\frac{r^2-1}{3C_W}
\]</span></p>
<p><span class="math display">\[
F_W=m_WF^* \stackrel{\cdot}{\sim}F_{r-1,\nu_W}
\]</span></p>
<p><strong>Example 4.6 - Virtual Training for a Lifeboat Launching Task</strong></p>
<p>For the lifeboat training experiment, there were <span class="math inline">\(r=4\)</span> treatments
and each sample size was <span class="math inline">\(n=16\)</span>. The following R code produces Welch’s
<span class="math inline">\(F_W\)</span>-test directly from the treatment means, variances, and sample sizes as well as using the <strong>oneway.test</strong> function in R.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="alternative-tests-for-treatment-effects.html#cb146-1" tabindex="-1"></a>vt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/virtual_training.csv&quot;</span>)</span>
<span id="cb146-2"><a href="alternative-tests-for-treatment-effects.html#cb146-2" tabindex="-1"></a></span>
<span id="cb146-3"><a href="alternative-tests-for-treatment-effects.html#cb146-3" tabindex="-1"></a><span class="do">### Brute-Force Computation of Welch&#39;s F_W-test</span></span>
<span id="cb146-4"><a href="alternative-tests-for-treatment-effects.html#cb146-4" tabindex="-1"></a>vt.n <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(vt<span class="sc">$</span>procKnow,vt<span class="sc">$</span>grp.trt,length))</span>
<span id="cb146-5"><a href="alternative-tests-for-treatment-effects.html#cb146-5" tabindex="-1"></a>vt.mean <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(vt<span class="sc">$</span>procKnow,vt<span class="sc">$</span>grp.trt,mean))</span>
<span id="cb146-6"><a href="alternative-tests-for-treatment-effects.html#cb146-6" tabindex="-1"></a>vt.var <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(vt<span class="sc">$</span>procKnow,vt<span class="sc">$</span>grp.trt,var))</span>
<span id="cb146-7"><a href="alternative-tests-for-treatment-effects.html#cb146-7" tabindex="-1"></a>vt.r <span class="ot">&lt;-</span> <span class="fu">length</span>(vt.n)</span>
<span id="cb146-8"><a href="alternative-tests-for-treatment-effects.html#cb146-8" tabindex="-1"></a>vt.n_T <span class="ot">&lt;-</span> <span class="fu">sum</span>(vt.n)</span>
<span id="cb146-9"><a href="alternative-tests-for-treatment-effects.html#cb146-9" tabindex="-1"></a>vt.wt <span class="ot">&lt;-</span> vt.n <span class="sc">/</span> vt.var</span>
<span id="cb146-10"><a href="alternative-tests-for-treatment-effects.html#cb146-10" tabindex="-1"></a>vt.wt.sum <span class="ot">&lt;-</span> <span class="fu">sum</span>(vt.wt)</span>
<span id="cb146-11"><a href="alternative-tests-for-treatment-effects.html#cb146-11" tabindex="-1"></a>vt.C_W <span class="ot">&lt;-</span> <span class="fu">sum</span>((<span class="dv">1</span><span class="sc">/</span>(vt.n<span class="dv">-1</span>)) <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>vt.wt<span class="sc">/</span>vt.wt.sum)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb146-12"><a href="alternative-tests-for-treatment-effects.html#cb146-12" tabindex="-1"></a>vt.m_W <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> vt.C_W<span class="sc">*</span><span class="dv">2</span><span class="sc">*</span>(vt.r<span class="dv">-2</span>)<span class="sc">/</span>(vt.r<span class="sc">^</span><span class="dv">2-1</span>))</span>
<span id="cb146-13"><a href="alternative-tests-for-treatment-effects.html#cb146-13" tabindex="-1"></a>vt.Fstar <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">/</span>(vt.r<span class="dv">-1</span>)) <span class="sc">*</span> (<span class="fu">sum</span>(vt.wt<span class="sc">*</span>vt.mean<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> (<span class="fu">sum</span>(vt.wt<span class="sc">*</span>vt.mean)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>vt.wt.sum)</span>
<span id="cb146-14"><a href="alternative-tests-for-treatment-effects.html#cb146-14" tabindex="-1"></a>vt.nu_W <span class="ot">&lt;-</span> (vt.r<span class="sc">^</span><span class="dv">2-1</span>) <span class="sc">/</span> (<span class="dv">3</span><span class="sc">*</span>vt.C_W)</span>
<span id="cb146-15"><a href="alternative-tests-for-treatment-effects.html#cb146-15" tabindex="-1"></a>vt.F_W <span class="ot">&lt;-</span> vt.m_W <span class="sc">*</span> vt.Fstar</span>
<span id="cb146-16"><a href="alternative-tests-for-treatment-effects.html#cb146-16" tabindex="-1"></a></span>
<span id="cb146-17"><a href="alternative-tests-for-treatment-effects.html#cb146-17" tabindex="-1"></a>welch.out <span class="ot">&lt;-</span> <span class="fu">cbind</span>(vt.r<span class="dv">-1</span>,vt.nu_W,vt.F_W,<span class="fu">qf</span>(.<span class="dv">95</span>,vt.r<span class="dv">-1</span>,vt.nu_W),<span class="dv">1</span><span class="sc">-</span><span class="fu">pf</span>(vt.F_W,vt.r<span class="dv">-1</span>,vt.nu_W))</span>
<span id="cb146-18"><a href="alternative-tests-for-treatment-effects.html#cb146-18" tabindex="-1"></a><span class="fu">colnames</span>(welch.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;df1&quot;</span>, <span class="st">&quot;df2&quot;</span>, <span class="st">&quot;F_W*&quot;</span>, <span class="st">&quot;F(.95)&quot;</span>, <span class="st">&quot;P(&gt;F_W*)&quot;</span>)</span>
<span id="cb146-19"><a href="alternative-tests-for-treatment-effects.html#cb146-19" tabindex="-1"></a><span class="fu">rownames</span>(welch.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Welch&#39;s F-test&quot;</span>)</span>
<span id="cb146-20"><a href="alternative-tests-for-treatment-effects.html#cb146-20" tabindex="-1"></a><span class="fu">round</span>(welch.out,<span class="dv">4</span>)</span></code></pre></div>
<pre><code>##                df1     df2  F_W* F(.95) P(&gt;F_W*)
## Welch&#39;s F-test   3 32.5622 6.827 2.8957   0.0011</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="alternative-tests-for-treatment-effects.html#cb148-1" tabindex="-1"></a><span class="do">### Using oneway.test function</span></span>
<span id="cb148-2"><a href="alternative-tests-for-treatment-effects.html#cb148-2" tabindex="-1"></a><span class="fu">oneway.test</span>(procKnow <span class="sc">~</span> <span class="fu">factor</span>(grp.trt), <span class="at">var.equal=</span><span class="cn">FALSE</span>, <span class="at">data=</span>vt)</span></code></pre></div>
<pre><code>## 
##  One-way analysis of means (not assuming equal variances)
## 
## data:  procKnow and factor(grp.trt)
## F = 6.827, num df = 3.000, denom df = 32.562, p-value = 0.001072</code></pre>
</div>
<div id="post-hoc-comparisons-with-unequal-variances" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Post-hoc Comparisons with Unequal Variances<a href="alternative-tests-for-treatment-effects.html#post-hoc-comparisons-with-unequal-variances" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <strong>Games-Howell</strong> method can be used to make pairwise comparisons among all pairs of treatments when variances are unequal. Like Tukey’s method, it makes use of the studentized range distribution. It makes use of <strong>Satterthwaite’s approximation</strong> for the degrees of freedom for each pair of means.</p>
<p><span class="math display">\[
\nu_{ii&#39;}=\frac{\left(\frac{s_i^2}{n_i}+\frac{s_{i&#39;}^2}{n_{i&#39;}}\right)^2}
{\frac{\left(\frac{s_i^2}{n_i}\right)^2}{n_i-1} + \frac{\left(\frac{s_{i&#39;}^2}{n_{i&#39;}}\right)^2}{n_{i&#39;}-1}}
\qquad \qquad
GH_{ii&#39;}=\frac{q_{1-\alpha;r,\nu_{ii&#39;}}}{\sqrt{2}}\sqrt{\frac{s_i^2}{n_i}+\frac{s_{i&#39;}^2}{n_{i&#39;}}}
\]</span></p>
<p>Conclude <span class="math inline">\(\mu_i\ne\mu_{i&#39;}\)</span> if <span class="math inline">\(\left|\overline{y}_{i\bullet}-\overline{y}_{i&#39;\bullet}\right| \ge GH_{ii&#39;}\)</span>.
Simultaneous <span class="math inline">\((1-\alpha)100\%\)</span> Confidence Intervals for <span class="math inline">\(\mu_i-\mu_{i&#39;}\)</span>
are of the form
<span class="math inline">\(\left(\overline{y}_{i\bullet}-\overline{y}_{i&#39;\bullet}\right)\pm GH_{ii&#39;}\)</span>.</p>
<p><strong>Example 4.7 - Virtual Training for a Lifeboat Launching Task</strong></p>
<p>For the lifeboat training experiment, there were <span class="math inline">\(r=4\)</span> treatments
and each sample size was <span class="math inline">\(n=16\)</span>. The following R code computes Simultaneous 95% Confidence Intervals and adjusted <span class="math inline">\(P\)</span>-values based on the Games-Howell method.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="alternative-tests-for-treatment-effects.html#cb150-1" tabindex="-1"></a>vt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/virtual_training.csv&quot;</span>)</span>
<span id="cb150-2"><a href="alternative-tests-for-treatment-effects.html#cb150-2" tabindex="-1"></a><span class="fu">head</span>(vt,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##   grp.trt procKnow
## 1       1   4.5614
## 2       1   6.6593</code></pre>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="alternative-tests-for-treatment-effects.html#cb152-1" tabindex="-1"></a><span class="do">### Brute-Force Computation of Games-Howell Comparisons</span></span>
<span id="cb152-2"><a href="alternative-tests-for-treatment-effects.html#cb152-2" tabindex="-1"></a>games_howell <span class="ot">&lt;-</span> <span class="cf">function</span>(y,trt,alpha) {</span>
<span id="cb152-3"><a href="alternative-tests-for-treatment-effects.html#cb152-3" tabindex="-1"></a></span>
<span id="cb152-4"><a href="alternative-tests-for-treatment-effects.html#cb152-4" tabindex="-1"></a>ybar <span class="ot">&lt;-</span> <span class="fu">mean</span>(y)</span>
<span id="cb152-5"><a href="alternative-tests-for-treatment-effects.html#cb152-5" tabindex="-1"></a>ybar.trt <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(y,trt,mean))</span>
<span id="cb152-6"><a href="alternative-tests-for-treatment-effects.html#cb152-6" tabindex="-1"></a>var.trt <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(y,trt,var))</span>
<span id="cb152-7"><a href="alternative-tests-for-treatment-effects.html#cb152-7" tabindex="-1"></a>rep.trt <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(y,trt,length))</span>
<span id="cb152-8"><a href="alternative-tests-for-treatment-effects.html#cb152-8" tabindex="-1"></a>num.trt <span class="ot">&lt;-</span> <span class="fu">length</span>(ybar.trt)</span>
<span id="cb152-9"><a href="alternative-tests-for-treatment-effects.html#cb152-9" tabindex="-1"></a>num.pairs <span class="ot">&lt;-</span> num.trt<span class="sc">*</span>(num.trt<span class="dv">-1</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb152-10"><a href="alternative-tests-for-treatment-effects.html#cb152-10" tabindex="-1"></a>sse <span class="ot">&lt;-</span> <span class="fu">sum</span>((rep.trt<span class="dv">-1</span>)<span class="sc">*</span>var.trt)</span>
<span id="cb152-11"><a href="alternative-tests-for-treatment-effects.html#cb152-11" tabindex="-1"></a>mse <span class="ot">&lt;-</span> sse<span class="sc">/</span>(<span class="fu">sum</span>(rep.trt)<span class="sc">-</span>num.trt)</span>
<span id="cb152-12"><a href="alternative-tests-for-treatment-effects.html#cb152-12" tabindex="-1"></a></span>
<span id="cb152-13"><a href="alternative-tests-for-treatment-effects.html#cb152-13" tabindex="-1"></a>i1.i2 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">2</span><span class="sc">*</span>num.pairs),<span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb152-14"><a href="alternative-tests-for-treatment-effects.html#cb152-14" tabindex="-1"></a>ybar.diff <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,num.pairs)</span>
<span id="cb152-15"><a href="alternative-tests-for-treatment-effects.html#cb152-15" tabindex="-1"></a>gh.df <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,num.pairs)</span>
<span id="cb152-16"><a href="alternative-tests-for-treatment-effects.html#cb152-16" tabindex="-1"></a>gh.msd <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,num.pairs)</span>
<span id="cb152-17"><a href="alternative-tests-for-treatment-effects.html#cb152-17" tabindex="-1"></a>gh.LL <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,num.pairs)</span>
<span id="cb152-18"><a href="alternative-tests-for-treatment-effects.html#cb152-18" tabindex="-1"></a>gh.UL <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,num.pairs)</span>
<span id="cb152-19"><a href="alternative-tests-for-treatment-effects.html#cb152-19" tabindex="-1"></a>gh.adjpv <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,num.pairs)</span>
<span id="cb152-20"><a href="alternative-tests-for-treatment-effects.html#cb152-20" tabindex="-1"></a>pair <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb152-21"><a href="alternative-tests-for-treatment-effects.html#cb152-21" tabindex="-1"></a></span>
<span id="cb152-22"><a href="alternative-tests-for-treatment-effects.html#cb152-22" tabindex="-1"></a><span class="cf">for</span>(i1 <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>num.trt) {</span>
<span id="cb152-23"><a href="alternative-tests-for-treatment-effects.html#cb152-23" tabindex="-1"></a>  <span class="cf">for</span> (i2 <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(i1<span class="dv">-1</span>)) {</span>
<span id="cb152-24"><a href="alternative-tests-for-treatment-effects.html#cb152-24" tabindex="-1"></a>    pair <span class="ot">&lt;-</span> pair <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb152-25"><a href="alternative-tests-for-treatment-effects.html#cb152-25" tabindex="-1"></a>    i1.i2[pair,] <span class="ot">&lt;-</span> <span class="fu">cbind</span>(i1,i2)</span>
<span id="cb152-26"><a href="alternative-tests-for-treatment-effects.html#cb152-26" tabindex="-1"></a>    ybar.diff[pair] <span class="ot">&lt;-</span> ybar.trt[i1] <span class="sc">-</span> ybar.trt[i2]</span>
<span id="cb152-27"><a href="alternative-tests-for-treatment-effects.html#cb152-27" tabindex="-1"></a>    gh.df[pair] <span class="ot">&lt;-</span> </span>
<span id="cb152-28"><a href="alternative-tests-for-treatment-effects.html#cb152-28" tabindex="-1"></a>      (var.trt[i1]<span class="sc">/</span>rep.trt[i1] <span class="sc">+</span> var.trt[i2]<span class="sc">/</span>rep.trt[i2])<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> </span>
<span id="cb152-29"><a href="alternative-tests-for-treatment-effects.html#cb152-29" tabindex="-1"></a>      ((var.trt[i1]<span class="sc">/</span>rep.trt[i1])<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(rep.trt[i1]<span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb152-30"><a href="alternative-tests-for-treatment-effects.html#cb152-30" tabindex="-1"></a>       (var.trt[i2]<span class="sc">/</span>rep.trt[i2])<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(rep.trt[i2]<span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb152-31"><a href="alternative-tests-for-treatment-effects.html#cb152-31" tabindex="-1"></a>    gh.msd[pair] <span class="ot">&lt;-</span> </span>
<span id="cb152-32"><a href="alternative-tests-for-treatment-effects.html#cb152-32" tabindex="-1"></a>      (<span class="fu">qtukey</span>(<span class="dv">1</span><span class="sc">-</span>alpha,num.trt,gh.df[pair])<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">2</span>)) <span class="sc">*</span></span>
<span id="cb152-33"><a href="alternative-tests-for-treatment-effects.html#cb152-33" tabindex="-1"></a>      <span class="fu">sqrt</span>(var.trt[i1]<span class="sc">/</span>rep.trt[i1]<span class="sc">+</span>var.trt[i2]<span class="sc">/</span>rep.trt[i2])</span>
<span id="cb152-34"><a href="alternative-tests-for-treatment-effects.html#cb152-34" tabindex="-1"></a>    gh.LL[pair] <span class="ot">&lt;-</span> ybar.diff[pair]<span class="sc">-</span>gh.msd[pair]</span>
<span id="cb152-35"><a href="alternative-tests-for-treatment-effects.html#cb152-35" tabindex="-1"></a>    gh.UL[pair] <span class="ot">&lt;-</span> ybar.diff[pair]<span class="sc">+</span>gh.msd[pair]</span>
<span id="cb152-36"><a href="alternative-tests-for-treatment-effects.html#cb152-36" tabindex="-1"></a>    gh.q <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">2</span>)<span class="sc">*</span>ybar.diff[pair]<span class="sc">/</span><span class="fu">sqrt</span>(var.trt[i1]<span class="sc">/</span>rep.trt[i1]<span class="sc">+</span>var.trt[i2]<span class="sc">/</span>rep.trt[i2])</span>
<span id="cb152-37"><a href="alternative-tests-for-treatment-effects.html#cb152-37" tabindex="-1"></a>    gh.adjpv[pair] <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">ptukey</span>(<span class="fu">abs</span>(gh.q),num.trt,gh.df[pair])</span>
<span id="cb152-38"><a href="alternative-tests-for-treatment-effects.html#cb152-38" tabindex="-1"></a>    }</span>
<span id="cb152-39"><a href="alternative-tests-for-treatment-effects.html#cb152-39" tabindex="-1"></a>  }</span>
<span id="cb152-40"><a href="alternative-tests-for-treatment-effects.html#cb152-40" tabindex="-1"></a>gh.out <span class="ot">&lt;-</span> <span class="fu">cbind</span>(i1.i2,ybar.diff,gh.df,gh.msd,gh.LL,gh.UL,gh.adjpv)</span>
<span id="cb152-41"><a href="alternative-tests-for-treatment-effects.html#cb152-41" tabindex="-1"></a><span class="fu">colnames</span>(gh.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Trt i&quot;</span>, <span class="st">&quot;Trt i&#39;&quot;</span>, <span class="st">&quot;Ybar diff&quot;</span>,<span class="st">&quot;df&quot;</span>, <span class="st">&quot;MSD&quot;</span>, <span class="st">&quot;LL&quot;</span>, <span class="st">&quot;UL&quot;</span>, <span class="st">&quot;Adj P&quot;</span>)</span>
<span id="cb152-42"><a href="alternative-tests-for-treatment-effects.html#cb152-42" tabindex="-1"></a><span class="fu">round</span>(gh.out,<span class="dv">4</span>)</span>
<span id="cb152-43"><a href="alternative-tests-for-treatment-effects.html#cb152-43" tabindex="-1"></a>}</span>
<span id="cb152-44"><a href="alternative-tests-for-treatment-effects.html#cb152-44" tabindex="-1"></a></span>
<span id="cb152-45"><a href="alternative-tests-for-treatment-effects.html#cb152-45" tabindex="-1"></a><span class="fu">games_howell</span>(vt<span class="sc">$</span>procKnow, vt<span class="sc">$</span>grp.trt, .<span class="dv">05</span>)</span></code></pre></div>
<pre><code>##      Trt i Trt i&#39; Ybar diff      df    MSD      LL     UL  Adj P
## [1,]     2      1    2.7778 27.5847 1.6466  1.1312 4.4244 0.0005
## [2,]     3      1    1.8056 26.5999 2.3440 -0.5384 4.1495 0.1759
## [3,]     3      2   -0.9722 22.2357 2.1931 -3.1654 1.2209 0.6150
## [4,]     4      1    1.9444 29.9806 1.8893  0.0552 3.8337 0.0418
## [5,]     4      2   -0.8333 27.2301 1.6756 -2.5089 0.8422 0.5340
## [6,]     4      3    0.1389 26.9707 2.3614 -2.2226 2.5003 0.9985</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="alternative-tests-for-treatment-effects.html#cb154-1" tabindex="-1"></a><span class="do">### Using the gamesHowellTest function in PMCMRplus package (gives adjusted P-values)</span></span>
<span id="cb154-2"><a href="alternative-tests-for-treatment-effects.html#cb154-2" tabindex="-1"></a><span class="fu">gamesHowellTest</span>(procKnow <span class="sc">~</span> grp.trt, <span class="at">data=</span>vt)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using Games-Howell test</code></pre>
<pre><code>## data: procKnow by grp.trt</code></pre>
<pre><code>##   1       2       3      
## 2 0.00046 -       -      
## 3 0.17589 0.61503 -      
## 4 0.04183 0.53405 0.99848</code></pre>
<pre><code>## 
## P value adjustment method: none</code></pre>
<pre><code>## alternative hypothesis: two.sided</code></pre>
<p>Treatment 2 (Monitor/Keyboard) is significantly higher than Treatment 1 (Lecture/Materials)
and Treatment 4 (Head Mounted Display/Wearable sensors) is significantly higher than Treatment 1.</p>
<p><span class="math display">\[
\nabla
\]</span></p>
<p>Finally, we simulate Welch’s Test for Scenario 4 described previously where <span class="math inline">\(\mu_1=\mu_2=\mu_3=100\)</span>, <span class="math inline">\(\sigma_1=10,\sigma_2=20,\sigma_3=30\)</span>,
and <span class="math inline">\(n_1=30,n_2=20,n_3=10\)</span>.</p>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
##  0.000788  0.419304  1.053916  1.754281  2.301317 37.070308</code></pre>
<pre><code>## [1] 0.1637</code></pre>
<pre><code>## [1] 0.0562</code></pre>
<p>The ANOVA <span class="math inline">\(F\)</span>-test rejected the null hypothesis in 16.37% of the samples,
while Welch’s <span class="math inline">\(F_W\)</span>-test rejected it in 5.62% of the samples, much closer to the target of 5%.</p>
</div>
</div>
<div id="nonparametric-test-for-non-normal-data" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Nonparametric Test for Non-normal Data<a href="alternative-tests-for-treatment-effects.html#nonparametric-test-for-non-normal-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <strong>Kruskal-Wallis Test</strong> is a rank based test used in cases where the errors are not normally distributed. In particular, outlying observations, which have large impacts on the means and standard deviations have smaller impact when measurements are replaced by ranks.</p>
<p>The <span class="math inline">\(n_T\)</span> observations are ranked from 1 (smallest) to <span class="math inline">\(n_T\)</span> (largest), with ties being given the average of the ranks they would have received if not exactly equal.
For instance, if two observations tie for the smallest value, they would each receive the
rank of 1.5, and the next smallest observation would get the rank of 3. The sum of the ranks is <span class="math inline">\(1+\cdots+n_T=n_T\left(n_T+1\right)/2\)</span>.</p>
<p>Once the individual measurements are ranked, rank sums are obtained for each treatment/group, as well as the Kruskal-Wallis <span class="math inline">\(H\)</span>-statistic, which under the null hypothesis of equal medians <span class="math inline">\(H_0:M_1=\cdots=M_r\)</span> follows a chi-square distribution with <span class="math inline">\(r-1\)</span> degrees of freedom approximately.</p>
<p><span class="math display">\[
R_{ij} = \mbox{rank}\left(Y_{ij}\right) \mbox{ among } Y_{11},\ldots Y_{rn_r}
\qquad R_{i\bullet} = \sum_{j=1}^{n_i}R_{ij}
\]</span>
<span class="math display">\[
\mbox{Test Statistic:} \quad
H^*=\left[\frac{12}{n_T\left(n_T+1\right)}\sum_{i=1}^r\frac{R_{i\bullet}^2}{n_i}\right] -
3\left(n_T+1\right)
\]</span>
<span class="math display">\[
\mbox{Rejection Region:} \quad H^* \ge \chi_{r-1}^2   \qquad
P=P\left(\chi_{r-1}^2 \geq H^*\right)
\]</span>
When there are ties, an adjustment can be made to <span class="math inline">\(H^*\)</span>, that rarely makes a large effect.
Let the number of groups with ties be <span class="math inline">\(g\)</span> and let the <span class="math inline">\(k^{th}\)</span> group have <span class="math inline">\(t_k\)</span> tied observations. Then, the adjusted test statistic is given below.</p>
<p><span class="math display">\[
\mbox{Test Statistic:} \quad
H^{*&#39;} =
\frac{H^*}
{\left[1-
\frac{\sum_{k=1}^g\left(t_k-1\right)t_k\left(t_k+1\right)}
{\left(n_T-1\right)n_T\left(n_T+1\right)}
\right]}
\]</span></p>
<p>When the null hypothesis of equal medians is rejected,
approximate Confidence Intervals for the differences in mean ranks among the <span class="math inline">\(g=r(r-1)/2\)</span> pairs of treatments are computed as follows.</p>
<p><span class="math display">\[
\left(\overline{R}_{i\bullet}-\overline{R}_{i&#39;\bullet}\right) \pm
z_{1-\alpha/(2g)} \sqrt{\frac{n_T\left(n_T+1\right)}{2}
\left(\frac{1}{n_i}+\frac{1}{n_{i&#39;}}\right)}
\]</span></p>
<p><strong>Example 4.8 - Virtual Training for a Lifeboat Launching Task</strong></p>
<p>For the lifeboat training experiment, there were <span class="math inline">\(r=4\)</span> treatments
and each sample size was <span class="math inline">\(n=16\)</span>. We will directly compute the ranks, test, and multiple comparisons. Then the <strong>kruskal.test</strong> function will be used. Note that the <strong>rank</strong> function in R correctly adjusts ranks for ties. The null hypothesis is that the population medians are equal for the <span class="math inline">\(r=4\)</span> treatments.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="alternative-tests-for-treatment-effects.html#cb163-1" tabindex="-1"></a>vt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/virtual_training.csv&quot;</span>)</span>
<span id="cb163-2"><a href="alternative-tests-for-treatment-effects.html#cb163-2" tabindex="-1"></a><span class="fu">head</span>(vt,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##   grp.trt procKnow
## 1       1   4.5614
## 2       1   6.6593</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="alternative-tests-for-treatment-effects.html#cb165-1" tabindex="-1"></a><span class="do">### Direct calculations</span></span>
<span id="cb165-2"><a href="alternative-tests-for-treatment-effects.html#cb165-2" tabindex="-1"></a>    </span>
<span id="cb165-3"><a href="alternative-tests-for-treatment-effects.html#cb165-3" tabindex="-1"></a>vt<span class="sc">$</span>rankY <span class="ot">&lt;-</span> <span class="fu">rank</span>(vt<span class="sc">$</span>procKnow)                               <span class="do">## Ranks of Y values</span></span>
<span id="cb165-4"><a href="alternative-tests-for-treatment-effects.html#cb165-4" tabindex="-1"></a>sum.rank <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(vt<span class="sc">$</span>rankY, vt<span class="sc">$</span>grp.trt, sum))   <span class="do">## Rank sums R_1,...,R_4</span></span>
<span id="cb165-5"><a href="alternative-tests-for-treatment-effects.html#cb165-5" tabindex="-1"></a>n.rank <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(vt<span class="sc">$</span>rankY, vt<span class="sc">$</span>grp.trt, length))   <span class="do">## n_1,...,n_4</span></span>
<span id="cb165-6"><a href="alternative-tests-for-treatment-effects.html#cb165-6" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">length</span>(n.rank)                                         </span>
<span id="cb165-7"><a href="alternative-tests-for-treatment-effects.html#cb165-7" tabindex="-1"></a>n_T <span class="ot">&lt;-</span> <span class="fu">sum</span>(n.rank)</span>
<span id="cb165-8"><a href="alternative-tests-for-treatment-effects.html#cb165-8" tabindex="-1"></a></span>
<span id="cb165-9"><a href="alternative-tests-for-treatment-effects.html#cb165-9" tabindex="-1"></a>KW.stat <span class="ot">&lt;-</span> (<span class="dv">12</span><span class="sc">/</span>(n_T<span class="sc">*</span>(n_T<span class="sc">+</span><span class="dv">1</span>))) <span class="sc">*</span> <span class="fu">sum</span>(sum.rank<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n.rank) <span class="sc">-</span> <span class="dv">3</span><span class="sc">*</span>(n_T<span class="sc">+</span><span class="dv">1</span>)  <span class="do">## K-W H* statistic</span></span>
<span id="cb165-10"><a href="alternative-tests-for-treatment-effects.html#cb165-10" tabindex="-1"></a><span class="do">## Set-up and print output</span></span>
<span id="cb165-11"><a href="alternative-tests-for-treatment-effects.html#cb165-11" tabindex="-1"></a>KW.out <span class="ot">&lt;-</span> <span class="fu">cbind</span>(KW.stat, r<span class="dv">-1</span>, <span class="fu">qchisq</span>(.<span class="dv">95</span>,r<span class="dv">-1</span>), <span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(KW.stat,r<span class="dv">-1</span>))</span>
<span id="cb165-12"><a href="alternative-tests-for-treatment-effects.html#cb165-12" tabindex="-1"></a><span class="fu">colnames</span>(KW.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;KW stat&quot;</span>, <span class="st">&quot;df&quot;</span>, <span class="st">&quot;X2(.95)&quot;</span>, <span class="st">&quot;P(&gt;KW)&quot;</span>)</span>
<span id="cb165-13"><a href="alternative-tests-for-treatment-effects.html#cb165-13" tabindex="-1"></a><span class="fu">rownames</span>(KW.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Kruskal-Wallis Test&quot;</span>)</span>
<span id="cb165-14"><a href="alternative-tests-for-treatment-effects.html#cb165-14" tabindex="-1"></a><span class="fu">round</span>(KW.out,<span class="dv">4</span>)</span></code></pre></div>
<pre><code>##                     KW stat df X2(.95) P(&gt;KW)
## Kruskal-Wallis Test 12.9151  3  7.8147 0.0048</code></pre>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="alternative-tests-for-treatment-effects.html#cb167-1" tabindex="-1"></a><span class="do">## Function for pairwise comparisons of medians</span></span>
<span id="cb167-2"><a href="alternative-tests-for-treatment-effects.html#cb167-2" tabindex="-1"></a>KW.CI <span class="ot">&lt;-</span> <span class="cf">function</span>(y, trt, alpha) {</span>
<span id="cb167-3"><a href="alternative-tests-for-treatment-effects.html#cb167-3" tabindex="-1"></a>rank.y <span class="ot">&lt;-</span> <span class="fu">rank</span>(y)</span>
<span id="cb167-4"><a href="alternative-tests-for-treatment-effects.html#cb167-4" tabindex="-1"></a>rank.trt <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(rank.y,trt,mean))</span>
<span id="cb167-5"><a href="alternative-tests-for-treatment-effects.html#cb167-5" tabindex="-1"></a>rep.trt <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(rank.y,trt,length))</span>
<span id="cb167-6"><a href="alternative-tests-for-treatment-effects.html#cb167-6" tabindex="-1"></a>num.trt <span class="ot">&lt;-</span> <span class="fu">length</span>(rank.trt)</span>
<span id="cb167-7"><a href="alternative-tests-for-treatment-effects.html#cb167-7" tabindex="-1"></a>num.pairs <span class="ot">&lt;-</span> num.trt<span class="sc">*</span>(num.trt<span class="dv">-1</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb167-8"><a href="alternative-tests-for-treatment-effects.html#cb167-8" tabindex="-1"></a></span>
<span id="cb167-9"><a href="alternative-tests-for-treatment-effects.html#cb167-9" tabindex="-1"></a>i1.i2 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">2</span><span class="sc">*</span>num.pairs),<span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb167-10"><a href="alternative-tests-for-treatment-effects.html#cb167-10" tabindex="-1"></a>rbar.diff <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,num.pairs)</span>
<span id="cb167-11"><a href="alternative-tests-for-treatment-effects.html#cb167-11" tabindex="-1"></a>r.msd <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,num.pairs)</span>
<span id="cb167-12"><a href="alternative-tests-for-treatment-effects.html#cb167-12" tabindex="-1"></a>r.LL <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,num.pairs)</span>
<span id="cb167-13"><a href="alternative-tests-for-treatment-effects.html#cb167-13" tabindex="-1"></a>r.UL <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,num.pairs)</span>
<span id="cb167-14"><a href="alternative-tests-for-treatment-effects.html#cb167-14" tabindex="-1"></a>r.adjpv <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,num.pairs)</span>
<span id="cb167-15"><a href="alternative-tests-for-treatment-effects.html#cb167-15" tabindex="-1"></a>pair <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb167-16"><a href="alternative-tests-for-treatment-effects.html#cb167-16" tabindex="-1"></a></span>
<span id="cb167-17"><a href="alternative-tests-for-treatment-effects.html#cb167-17" tabindex="-1"></a><span class="cf">for</span>(i1 <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>num.trt) {</span>
<span id="cb167-18"><a href="alternative-tests-for-treatment-effects.html#cb167-18" tabindex="-1"></a>  <span class="cf">for</span> (i2 <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(i1<span class="dv">-1</span>)) {</span>
<span id="cb167-19"><a href="alternative-tests-for-treatment-effects.html#cb167-19" tabindex="-1"></a>    pair <span class="ot">&lt;-</span> pair <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb167-20"><a href="alternative-tests-for-treatment-effects.html#cb167-20" tabindex="-1"></a>    i1.i2[pair,] <span class="ot">&lt;-</span> <span class="fu">cbind</span>(i1,i2)</span>
<span id="cb167-21"><a href="alternative-tests-for-treatment-effects.html#cb167-21" tabindex="-1"></a>    rbar.diff[pair] <span class="ot">&lt;-</span> rank.trt[i1] <span class="sc">-</span> rank.trt[i2]</span>
<span id="cb167-22"><a href="alternative-tests-for-treatment-effects.html#cb167-22" tabindex="-1"></a>    r.msd[pair] <span class="ot">&lt;-</span> </span>
<span id="cb167-23"><a href="alternative-tests-for-treatment-effects.html#cb167-23" tabindex="-1"></a>      <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>num.pairs)) <span class="sc">*</span></span>
<span id="cb167-24"><a href="alternative-tests-for-treatment-effects.html#cb167-24" tabindex="-1"></a>      <span class="fu">sqrt</span>((n_T<span class="sc">*</span>(n_T<span class="sc">+</span><span class="dv">1</span>)<span class="sc">/</span><span class="dv">12</span>)<span class="sc">*</span>(<span class="dv">1</span><span class="sc">/</span>rep.trt[i1]<span class="sc">+</span><span class="dv">1</span><span class="sc">/</span>rep.trt[i2]))</span>
<span id="cb167-25"><a href="alternative-tests-for-treatment-effects.html#cb167-25" tabindex="-1"></a>    r.LL[pair] <span class="ot">&lt;-</span> rbar.diff[pair]<span class="sc">-</span>r.msd[pair]</span>
<span id="cb167-26"><a href="alternative-tests-for-treatment-effects.html#cb167-26" tabindex="-1"></a>    r.UL[pair] <span class="ot">&lt;-</span> rbar.diff[pair]<span class="sc">+</span>r.msd[pair]</span>
<span id="cb167-27"><a href="alternative-tests-for-treatment-effects.html#cb167-27" tabindex="-1"></a>     r.pv<span class="ot">&lt;-</span> </span>
<span id="cb167-28"><a href="alternative-tests-for-treatment-effects.html#cb167-28" tabindex="-1"></a>      <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(<span class="fu">abs</span>(rbar.diff[pair]<span class="sc">/</span><span class="fu">sqrt</span>((n_T<span class="sc">*</span>(n_T<span class="sc">+</span><span class="dv">1</span>)<span class="sc">/</span><span class="dv">12</span>)<span class="sc">*</span>(<span class="dv">1</span><span class="sc">/</span>rep.trt[i1]<span class="sc">+</span><span class="dv">1</span><span class="sc">/</span>rep.trt[i2])))))</span>
<span id="cb167-29"><a href="alternative-tests-for-treatment-effects.html#cb167-29" tabindex="-1"></a>    r.adjpv[pair] <span class="ot">&lt;-</span> <span class="fu">min</span>(<span class="dv">1</span>,num.pairs<span class="sc">*</span>r.pv)</span>
<span id="cb167-30"><a href="alternative-tests-for-treatment-effects.html#cb167-30" tabindex="-1"></a>    }</span>
<span id="cb167-31"><a href="alternative-tests-for-treatment-effects.html#cb167-31" tabindex="-1"></a>  }</span>
<span id="cb167-32"><a href="alternative-tests-for-treatment-effects.html#cb167-32" tabindex="-1"></a>r.out <span class="ot">&lt;-</span> <span class="fu">cbind</span>(i1.i2,rbar.diff,r.msd,r.LL,r.UL,r.adjpv)</span>
<span id="cb167-33"><a href="alternative-tests-for-treatment-effects.html#cb167-33" tabindex="-1"></a><span class="fu">colnames</span>(r.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Trt i&quot;</span>, <span class="st">&quot;Trt i&#39;&quot;</span>, <span class="st">&quot;Rank diff&quot;</span>, <span class="st">&quot;MSD&quot;</span>, <span class="st">&quot;LL&quot;</span>, <span class="st">&quot;UL&quot;</span>, <span class="st">&quot;Adj P&quot;</span>)</span>
<span id="cb167-34"><a href="alternative-tests-for-treatment-effects.html#cb167-34" tabindex="-1"></a><span class="fu">round</span>(r.out,<span class="dv">4</span>)</span>
<span id="cb167-35"><a href="alternative-tests-for-treatment-effects.html#cb167-35" tabindex="-1"></a>}</span>
<span id="cb167-36"><a href="alternative-tests-for-treatment-effects.html#cb167-36" tabindex="-1"></a></span>
<span id="cb167-37"><a href="alternative-tests-for-treatment-effects.html#cb167-37" tabindex="-1"></a><span class="fu">KW.CI</span>(vt<span class="sc">$</span>procKnow, vt<span class="sc">$</span>grp.trt, <span class="fl">0.05</span>)</span></code></pre></div>
<pre><code>##      Trt i Trt i&#39; Rank diff     MSD       LL      UL  Adj P
## [1,]     2      1    22.625 17.3671   5.2579 39.9921 0.0035
## [2,]     3      1    16.875 17.3671  -0.4921 34.2421 0.0622
## [3,]     3      2    -5.750 17.3671 -23.1171 11.6171 1.0000
## [4,]     4      1    15.250 17.3671  -2.1171 32.6171 0.1231
## [5,]     4      2    -7.375 17.3671 -24.7421  9.9921 1.0000
## [6,]     4      3    -1.625 17.3671 -18.9921 15.7421 1.0000</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="alternative-tests-for-treatment-effects.html#cb169-1" tabindex="-1"></a><span class="do">### kruskal.test function</span></span>
<span id="cb169-2"><a href="alternative-tests-for-treatment-effects.html#cb169-2" tabindex="-1"></a></span>
<span id="cb169-3"><a href="alternative-tests-for-treatment-effects.html#cb169-3" tabindex="-1"></a><span class="fu">kruskal.test</span>(procKnow <span class="sc">~</span> grp.trt, <span class="at">data=</span>vt)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  procKnow by grp.trt
## Kruskal-Wallis chi-squared = 12.915, df = 3, p-value = 0.004824</code></pre>
<p>The test concludes that the medians are not all equal. Based on the simultaneous comparisons, conclude that the median for treatment 2 (Monitor/Keyboard) is significantly higher than that for treatment 1 (Lecture/Materials). No other medians are significantly different.</p>
<p><span class="math display">\[\nabla \]</span></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="analysis-of-treatment-means.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="balanced-two-factor-designs.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  },
  "link": "https://github.com/LarryWinner/STA4211-Notes1.git/edit/main/%s",
  "text": "Edit"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
