<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Block Designs | Design and Analysis of Experiments</title>
  <meta name="description" content="This is a course on Experimental Design and Analysis." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Block Designs | Design and Analysis of Experiments" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a course on Experimental Design and Analysis." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Block Designs | Design and Analysis of Experiments" />
  
  <meta name="twitter:description" content="This is a course on Experimental Design and Analysis." />
  

<meta name="author" content="Larry Winner" />


<meta name="date" content="2026-06-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="higher-order-models.html"/>
<link rel="next" href="random-and-mixed-effects-models.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STA 4211 Course Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html"><i class="fa fa-check"></i><b>1</b> Comparing Two Treatments or Populations</a>
<ul>
<li class="chapter" data-level="1.1" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#linear-functions-of-random-variables"><i class="fa fa-check"></i><b>1.1</b> Linear Functions of Random Variables</a></li>
<li class="chapter" data-level="1.2" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#students-t-distribution-for-making-inference-on-population-means"><i class="fa fa-check"></i><b>1.2</b> Student’s <span class="math inline">\(t\)</span>-Distribution for Making Inference on Population Means</a></li>
<li class="chapter" data-level="1.3" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#inference-for-the-population-mean-difference"><i class="fa fa-check"></i><b>1.3</b> Inference for the Population Mean Difference</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#inference-for-the-population-mean-difference-for-paired-samples"><i class="fa fa-check"></i><b>1.3.1</b> Inference for the Population Mean Difference for Paired Samples</a></li>
<li class="chapter" data-level="1.3.2" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#inference-for-the-population-mean-difference-for-independent-samples"><i class="fa fa-check"></i><b>1.3.2</b> Inference for the Population Mean Difference for Independent Samples</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#inference-for-the-population-variance-ratios"><i class="fa fa-check"></i><b>1.4</b> Inference for the Population Variance Ratios</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#inferences-for-variance-ratios-for-independent-samples"><i class="fa fa-check"></i><b>1.4.1</b> Inferences for Variance Ratios for Independent Samples</a></li>
<li class="chapter" data-level="1.4.2" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#test-for-equal-variances-with-paired-samples"><i class="fa fa-check"></i><b>1.4.2</b> Test for Equal Variances with Paired Samples</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="comparing-two-treatments-or-populations.html"><a href="comparing-two-treatments-or-populations.html#examples"><i class="fa fa-check"></i><b>1.5</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>2</b> Introduction</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction.html"><a href="introduction.html#terminology"><i class="fa fa-check"></i><b>2.1</b> Terminology</a></li>
<li class="chapter" data-level="2.2" data-path="introduction.html"><a href="introduction.html#basics-of-controlled-experiments"><i class="fa fa-check"></i><b>2.2</b> Basics of Controlled Experiments</a></li>
<li class="chapter" data-level="2.3" data-path="introduction.html"><a href="introduction.html#completely-randomized-design-crd"><i class="fa fa-check"></i><b>2.3</b> Completely Randomized Design (CRD)</a></li>
<li class="chapter" data-level="2.4" data-path="introduction.html"><a href="introduction.html#randomized-complete-block-design-rcbd-or-rbd"><i class="fa fa-check"></i><b>2.4</b> Randomized Complete Block Design (RCBD or RBD)</a></li>
<li class="chapter" data-level="2.5" data-path="introduction.html"><a href="introduction.html#overview-of-some-standard-experimental-designs"><i class="fa fa-check"></i><b>2.5</b> Overview of Some Standard Experimental Designs</a></li>
<li class="chapter" data-level="2.6" data-path="introduction.html"><a href="introduction.html#overview-of-observational-study-designs"><i class="fa fa-check"></i><b>2.6</b> Overview of Observational Study Designs</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="single-factor-studies.html"><a href="single-factor-studies.html"><i class="fa fa-check"></i><b>3</b> Single Factor Studies</a>
<ul>
<li class="chapter" data-level="3.1" data-path="single-factor-studies.html"><a href="single-factor-studies.html#models-with-r2-factor-levels"><i class="fa fa-check"></i><b>3.1</b> Models with <span class="math inline">\(r=2\)</span> Factor Levels</a></li>
<li class="chapter" data-level="3.2" data-path="single-factor-studies.html"><a href="single-factor-studies.html#three-model-formulations"><i class="fa fa-check"></i><b>3.2</b> Three Model Formulations</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="single-factor-studies.html"><a href="single-factor-studies.html#cell-means-model"><i class="fa fa-check"></i><b>3.2.1</b> Cell Means Model</a></li>
<li class="chapter" data-level="3.2.2" data-path="single-factor-studies.html"><a href="single-factor-studies.html#treatment-effects-model"><i class="fa fa-check"></i><b>3.2.2</b> Treatment Effects Model</a></li>
<li class="chapter" data-level="3.2.3" data-path="single-factor-studies.html"><a href="single-factor-studies.html#reference-group-model"><i class="fa fa-check"></i><b>3.2.3</b> Reference Group Model</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="single-factor-studies.html"><a href="single-factor-studies.html#the-analysis-of-variance-and-f-test"><i class="fa fa-check"></i><b>3.3</b> The Analysis of Variance and <span class="math inline">\(F\)</span>-test</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="single-factor-studies.html"><a href="single-factor-studies.html#general-linear-test-approach"><i class="fa fa-check"></i><b>3.3.1</b> General Linear Test Approach</a></li>
<li class="chapter" data-level="3.3.2" data-path="single-factor-studies.html"><a href="single-factor-studies.html#power-calculations"><i class="fa fa-check"></i><b>3.3.2</b> Power Calculations</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="single-factor-studies.html"><a href="single-factor-studies.html#technical-details"><i class="fa fa-check"></i><b>3.4</b> Technical Details</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="single-factor-studies.html"><a href="single-factor-studies.html#least-squares-estimation-for-the-cell-means-model-regression-approach"><i class="fa fa-check"></i><b>3.4.1</b> Least Squares Estimation for the Cell Means Model (Regression Approach)</a></li>
<li class="chapter" data-level="3.4.2" data-path="single-factor-studies.html"><a href="single-factor-studies.html#scalar-estimation-for-the-cell-means-model"><i class="fa fa-check"></i><b>3.4.2</b> Scalar Estimation for the Cell Means Model</a></li>
<li class="chapter" data-level="3.4.3" data-path="single-factor-studies.html"><a href="single-factor-studies.html#estimation-for-the-treatment-effects-model"><i class="fa fa-check"></i><b>3.4.3</b> Estimation for the Treatment Effects Model</a></li>
<li class="chapter" data-level="3.4.4" data-path="single-factor-studies.html"><a href="single-factor-studies.html#least-squares-estimation-regression-approach"><i class="fa fa-check"></i><b>3.4.4</b> Least Squares Estimation (Regression Approach)</a></li>
<li class="chapter" data-level="3.4.5" data-path="single-factor-studies.html"><a href="single-factor-studies.html#the-analysis-of-variance"><i class="fa fa-check"></i><b>3.4.5</b> The Analysis of Variance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html"><i class="fa fa-check"></i><b>4</b> Analysis of Treatment Means</a>
<ul>
<li class="chapter" data-level="4.1" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#individual-treatment-means"><i class="fa fa-check"></i><b>4.1</b> Individual Treatment Means</a></li>
<li class="chapter" data-level="4.2" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#comparing-two-treatment-means"><i class="fa fa-check"></i><b>4.2</b> Comparing Two Treatment Means</a></li>
<li class="chapter" data-level="4.3" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#contrasts-among-treatment-means"><i class="fa fa-check"></i><b>4.3</b> Contrasts Among Treatment Means</a></li>
<li class="chapter" data-level="4.4" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#simultaneous-comparisons"><i class="fa fa-check"></i><b>4.4</b> Simultaneous Comparisons</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#tukeys-honest-significant-difference-hsd"><i class="fa fa-check"></i><b>4.4.1</b> Tukey’s Honest Significant Difference (HSD)</a></li>
<li class="chapter" data-level="4.4.2" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#scheffes-method-for-multiple-comparisons"><i class="fa fa-check"></i><b>4.4.2</b> Scheffe’s Method for Multiple Comparisons</a></li>
<li class="chapter" data-level="4.4.3" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#bonferroni-method-for-multiple-comparisons"><i class="fa fa-check"></i><b>4.4.3</b> Bonferroni Method for Multiple Comparisons</a></li>
<li class="chapter" data-level="4.4.4" data-path="analysis-of-treatment-means.html"><a href="analysis-of-treatment-means.html#multiple-range-methods"><i class="fa fa-check"></i><b>4.4.4</b> Multiple Range Methods</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html"><i class="fa fa-check"></i><b>5</b> Alternative Tests for Treatment Effects</a>
<ul>
<li class="chapter" data-level="5.1" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#randomizationpermutation-tests"><i class="fa fa-check"></i><b>5.1</b> Randomization/Permutation Tests</a></li>
<li class="chapter" data-level="5.2" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#tests-for-equal-error-variances"><i class="fa fa-check"></i><b>5.2</b> Tests for Equal Error Variances</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#hartleys-test"><i class="fa fa-check"></i><b>5.2.1</b> Hartley’s Test</a></li>
<li class="chapter" data-level="5.2.2" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#levenes-test"><i class="fa fa-check"></i><b>5.2.2</b> Levene’s Test</a></li>
<li class="chapter" data-level="5.2.3" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#bartletts-test"><i class="fa fa-check"></i><b>5.2.3</b> Bartlett’s Test</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#remedial-measures"><i class="fa fa-check"></i><b>5.3</b> Remedial Measures</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#weighted-least-squares-and-welchs-test"><i class="fa fa-check"></i><b>5.3.1</b> Weighted Least Squares and Welch’s Test</a></li>
<li class="chapter" data-level="5.3.2" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#post-hoc-comparisons-with-unequal-variances"><i class="fa fa-check"></i><b>5.3.2</b> Post-hoc Comparisons with Unequal Variances</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="alternative-tests-for-treatment-effects.html"><a href="alternative-tests-for-treatment-effects.html#nonparametric-test-for-non-normal-data"><i class="fa fa-check"></i><b>5.4</b> Nonparametric Test for Non-normal Data</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html"><i class="fa fa-check"></i><b>6</b> Balanced Two Factor Designs</a>
<ul>
<li class="chapter" data-level="6.1" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#introduction-1"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#two-factor-analysis-of-variance"><i class="fa fa-check"></i><b>6.2</b> Two Factor Analysis of Variance</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#cell-means-and-factor-effects-models"><i class="fa fa-check"></i><b>6.2.1</b> Cell Means and Factor Effects Models</a></li>
<li class="chapter" data-level="6.2.2" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#least-squaresmaximum-likelihood-estimators"><i class="fa fa-check"></i><b>6.2.2</b> Least Squares/Maximum Likelihood Estimators</a></li>
<li class="chapter" data-level="6.2.3" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#sums-of-squares-and-the-analysis-of-variance"><i class="fa fa-check"></i><b>6.2.3</b> Sums of Squares and the Analysis of Variance</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#factor-effect-contrasts"><i class="fa fa-check"></i><b>6.3</b> Factor Effect Contrasts</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#contrasts-when-there-is-no-interaction"><i class="fa fa-check"></i><b>6.3.1</b> Contrasts when there is No Interaction</a></li>
<li class="chapter" data-level="6.3.2" data-path="balanced-two-factor-designs.html"><a href="balanced-two-factor-designs.html#contrasts-when-interaction-is-present"><i class="fa fa-check"></i><b>6.3.2</b> Contrasts when Interaction is Present</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="two-factor-designs-with-1-observation-per-treatment.html"><a href="two-factor-designs-with-1-observation-per-treatment.html"><i class="fa fa-check"></i><b>7</b> Two-Factor Designs with 1 Observation per Treatment</a></li>
<li class="chapter" data-level="8" data-path="unbalanced-two-factor-analysis-of-variance.html"><a href="unbalanced-two-factor-analysis-of-variance.html"><i class="fa fa-check"></i><b>8</b> Unbalanced Two-Factor Analysis of Variance</a>
<ul>
<li class="chapter" data-level="8.1" data-path="unbalanced-two-factor-analysis-of-variance.html"><a href="unbalanced-two-factor-analysis-of-variance.html#statistical-model-and-the-analysis-of-variance"><i class="fa fa-check"></i><b>8.1</b> Statistical Model and the Analysis of Variance</a></li>
<li class="chapter" data-level="8.2" data-path="unbalanced-two-factor-analysis-of-variance.html"><a href="unbalanced-two-factor-analysis-of-variance.html#least-squares-estimators-and-contrastslinear-functions-among-means"><i class="fa fa-check"></i><b>8.2</b> Least Squares Estimators and Contrasts/Linear Functions Among Means</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="higher-order-models.html"><a href="higher-order-models.html"><i class="fa fa-check"></i><b>9</b> Higher Order Models</a>
<ul>
<li class="chapter" data-level="9.1" data-path="higher-order-models.html"><a href="higher-order-models.html#three-factor-models---mean-structure"><i class="fa fa-check"></i><b>9.1</b> Three Factor Models - Mean Structure</a></li>
<li class="chapter" data-level="9.2" data-path="higher-order-models.html"><a href="higher-order-models.html#statistical-model-and-the-analysis-of-variance-1"><i class="fa fa-check"></i><b>9.2</b> Statistical Model and the Analysis of Variance</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="block-designs.html"><a href="block-designs.html"><i class="fa fa-check"></i><b>10</b> Block Designs</a>
<ul>
<li class="chapter" data-level="10.1" data-path="block-designs.html"><a href="block-designs.html#randomized-block-and-repeated-measures-designs"><i class="fa fa-check"></i><b>10.1</b> Randomized Block and Repeated Measures Designs</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="block-designs.html"><a href="block-designs.html#model-structure-and-estimators"><i class="fa fa-check"></i><b>10.1.1</b> Model Structure and Estimators</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="block-designs.html"><a href="block-designs.html#analysis-of-variance-and-the-f-test"><i class="fa fa-check"></i><b>10.2</b> Analysis of Variance and the <span class="math inline">\(F\)</span>-test</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="block-designs.html"><a href="block-designs.html#checking-model-assumptions"><i class="fa fa-check"></i><b>10.2.1</b> Checking Model Assumptions</a></li>
<li class="chapter" data-level="10.2.2" data-path="block-designs.html"><a href="block-designs.html#relative-efficiency-and-within-subject-variance-covariance-matrix"><i class="fa fa-check"></i><b>10.2.2</b> Relative Efficiency and Within-Subject Variance-Covariance Matrix</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="block-designs.html"><a href="block-designs.html#latin-square-designs"><i class="fa fa-check"></i><b>10.3</b> Latin Square Designs</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html"><i class="fa fa-check"></i><b>11</b> Random and Mixed Effects Models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#way-random-effects-model"><i class="fa fa-check"></i><b>11.1</b> 1-Way Random Effects Model</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#analysis-of-variance"><i class="fa fa-check"></i><b>11.1.1</b> Analysis of Variance</a></li>
<li class="chapter" data-level="11.1.2" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#estimating-the-population-mean-mu_bullet"><i class="fa fa-check"></i><b>11.1.2</b> Estimating the Population Mean <span class="math inline">\(\mu_{\bullet}\)</span></a></li>
<li class="chapter" data-level="11.1.3" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#estimating-the-intraclass-correlation-coefficient"><i class="fa fa-check"></i><b>11.1.3</b> Estimating the Intraclass Correlation Coefficient</a></li>
<li class="chapter" data-level="11.1.4" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#estimating-the-within-group-variance"><i class="fa fa-check"></i><b>11.1.4</b> Estimating the Within Group Variance</a></li>
<li class="chapter" data-level="11.1.5" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#estimating-the-between-group-variance"><i class="fa fa-check"></i><b>11.1.5</b> Estimating the Between Group Variance</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#two-way-random-effects-model"><i class="fa fa-check"></i><b>11.2</b> Two-Way Random Effects Model</a></li>
<li class="chapter" data-level="11.3" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#two-way-mixed-effects-model"><i class="fa fa-check"></i><b>11.3</b> Two-Way Mixed Effects Model</a></li>
<li class="chapter" data-level="11.4" data-path="random-and-mixed-effects-models.html"><a href="random-and-mixed-effects-models.html#three-way-mixed-effects-models"><i class="fa fa-check"></i><b>11.4</b> Three-Way Mixed Effects Models</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="nested-designs.html"><a href="nested-designs.html"><i class="fa fa-check"></i><b>12</b> Nested Designs</a>
<ul>
<li class="chapter" data-level="12.1" data-path="nested-designs.html"><a href="nested-designs.html#estimators-and-the-analysis-of-variance"><i class="fa fa-check"></i><b>12.1</b> Estimators and the Analysis of Variance</a></li>
<li class="chapter" data-level="12.2" data-path="nested-designs.html"><a href="nested-designs.html#tests-contrasts-and-pairwise-comparisons"><i class="fa fa-check"></i><b>12.2</b> Tests, Contrasts, and Pairwise Comparisons</a></li>
<li class="chapter" data-level="12.3" data-path="nested-designs.html"><a href="nested-designs.html#repeated-measures-design"><i class="fa fa-check"></i><b>12.3</b> Repeated Measures Design</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="nested-designs.html"><a href="nested-designs.html#model-structure"><i class="fa fa-check"></i><b>12.3.1</b> Model Structure</a></li>
<li class="chapter" data-level="12.3.2" data-path="nested-designs.html"><a href="nested-designs.html#analysis-of-variance-and-f-tests"><i class="fa fa-check"></i><b>12.3.2</b> Analysis of Variance and <span class="math inline">\(F\)</span>-tests</a></li>
<li class="chapter" data-level="12.3.3" data-path="nested-designs.html"><a href="nested-designs.html#treatment-comparisons"><i class="fa fa-check"></i><b>12.3.3</b> Treatment Comparisons</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-covariance-ancova.html"><a href="analysis-of-covariance-ancova.html"><i class="fa fa-check"></i><b>13</b> Analysis of Covariance (ANCOVA)</a>
<ul>
<li class="chapter" data-level="13.1" data-path="analysis-of-covariance-ancova.html"><a href="analysis-of-covariance-ancova.html#additive-model"><i class="fa fa-check"></i><b>13.1</b> Additive Model</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="analysis-of-covariance-ancova.html"><a href="analysis-of-covariance-ancova.html#adjusted-means"><i class="fa fa-check"></i><b>13.1.1</b> Adjusted means</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="analysis-of-covariance-ancova.html"><a href="analysis-of-covariance-ancova.html#interaction-model"><i class="fa fa-check"></i><b>13.2</b> Interaction Model</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="response-surface-and-mixture-designs.html"><a href="response-surface-and-mixture-designs.html"><i class="fa fa-check"></i><b>14</b> Response Surface and Mixture Designs</a>
<ul>
<li class="chapter" data-level="14.1" data-path="response-surface-and-mixture-designs.html"><a href="response-surface-and-mixture-designs.html#response-surface-designs"><i class="fa fa-check"></i><b>14.1</b> Response Surface Designs</a></li>
<li class="chapter" data-level="14.2" data-path="response-surface-and-mixture-designs.html"><a href="response-surface-and-mixture-designs.html#mixture-models"><i class="fa fa-check"></i><b>14.2</b> Mixture Models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Design and Analysis of Experiments</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="block-designs" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter 10</span> Block Designs<a href="block-designs.html#block-designs" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In many experimental settings, it is possible to group experimental units into homogeneous groups or <strong>blocks</strong>, allowing each treatment to be assigned to individual units within each block. It is often possible to evaluate each treatment on the same individual unit or subject. The goal is to remove block-to-block variation and obtain more powerful tests for treatment effects. When individual units receive each treatment (preferably in random order), these are often referred to as <strong>Repeated Measures</strong>.</p>
<p>In other situations, it may be necessary to block on two or three factors to obtain better precision for studying treatment effects. These designs are <strong>Latin Squares</strong> for two blocking factors and <strong>Graeco-Latin Squares</strong> for three blocking factors. In many
situations, these designs are used to obtain “fair” comparisons of treatments, even if the factors are not concluded in the analysis. This helps remove biases that can occur in the implementation of the experiment, particularly when individual subjects receive each treatment.</p>
<p>Some examples containing a single blocking factor are given below.</p>
<ul>
<li><strong>Agriculture</strong> - An experiment to compare <span class="math inline">\(r\)</span> varieties of fertilizer is conducted on <span class="math inline">\(b\)</span> blocks of land. Within each block, <span class="math inline">\(r\)</span> plots are obtained and one variety of fertilizer is applied to each plot.</li>
<li><strong>Industrial</strong> - An experiment to compare <span class="math inline">\(r\)</span> methods (or machines) to manufacture a product is conducted on <span class="math inline">\(b\)</span> batches of raw material. Each batch is broken into <span class="math inline">\(r\)</span> sub-batches and each treatment is applied to one sub-batch within the batch.</li>
<li><strong>Pharmaceutical</strong> - An experiment is conducted to compare bioavailability among <span class="math inline">\(r\)</span> formulations of a drug product, by having each product measured on <span class="math inline">\(b\)</span> subjects. Subjects are given a particular sequence, and availability is measured for each formulation.</li>
</ul>
<p>In many cases, blocks are simply individual replications of an experiment on different days or at different locations. In other cases, individuals may be ordered based on an external measurement (e.g. severity, ability) and blocks may be formed by that criteria and the various treatments may be assigned to the group of individuals within these blocks.</p>
<p>Block designs can have a single treatment factor or combinations of multiple treatment factors. The larger the number of treatment levels, the less homogeneous will be the units within a block. In these cases <strong>Incomplete Block Designs</strong> can be utilized.</p>
<p>So far, when considering treatment factors, we have implicitly treated them as <strong>fixed factors</strong>, the levels observed in the experiment being the specific treatments of interest to researchers. In block designs, the blocks are very often <strong>random factors</strong>, representing a sample of all levels that could have been selected. These include: plots of land, batches of raw material, subjects in bioequivalence studies, and in virtually all repeated measures settings. The primary goal in all of these experiments is to compare the treatment effects as we have done in previous chapters. Fortunately, the <span class="math inline">\(F\)</span>-test and methods for making contrasts among treatments are the same whether blocks are fixed or random.</p>
<div id="randomized-block-and-repeated-measures-designs" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Randomized Block and Repeated Measures Designs<a href="block-designs.html#randomized-block-and-repeated-measures-designs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section we introduce the model for the Randomized Complete Block Design.
This same model is used for the Repeated Measures Design, when each subject receives each
treatment. This is not the same as another type of Repeated Measures Design, where each subject receives only one treatment, but is measured longitudinally at multiple time points.</p>
<p>For this model, each of <span class="math inline">\(r\)</span> treatments are observed, once within each of <span class="math inline">\(b\)</span>
blocks or subjects,
for a total of <span class="math inline">\(n_T=rb\)</span> observations.
For this model, when treatments are applied to subjects in some time order,
we are assuming there are no order or carryover effects. More complex designs can be used when this is the case. In this section, we will use <strong>blocks</strong> and <strong>subjects</strong> interchangeably. In virtually all cases, subjects are treated as random, except in
settings where the only subjects of interest are included in the experiment.</p>
<p><strong>Note: This notation is NOT consistent with Kutner, et al.</strong></p>
<div id="model-structure-and-estimators" class="section level3 hasAnchor" number="10.1.1">
<h3><span class="header-section-number">10.1.1</span> Model Structure and Estimators<a href="block-designs.html#model-structure-and-estimators" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><span class="math display">\[
Y_{ij} = \mu_{\bullet\bullet} + \tau_i + \beta_j + \epsilon_{ij} \qquad
i=1,\ldots,r; \quad j=1,\ldots,b \qquad \epsilon_{ij} \sim NID\left(0,\sigma^2\right)
\]</span></p>
<p>We assume fixed treatment effects as before, and allow for either fixed or random block effects.</p>
<p><span class="math display">\[
\mbox{Overall Mean:} \quad  \mu_{\bullet\bullet}  \qquad \qquad
\hat{\mu}_{\bullet\bullet} = \frac{\sum_{i=1}^r\sum_{j=1}^bY_{ij}}{rb} =
\overline{Y}_{\bullet\bullet}
\]</span>
<span class="math display">\[
\mbox{Treatment Effects:} \quad \tau_i = \mu_{i\bullet}-\mu_{\bullet\bullet}
\qquad \hat{\tau}_i = \overline{Y}_{i\bullet} - \overline{Y}_{\bullet\bullet}
\qquad  \sum_{i=1}^r\tau_i=\sum_{i=1}^r\hat{\tau}_i=0
\]</span></p>
<p>We consider the block effects separately, considering the fixed and random effects cases.</p>
<p><span class="math display">\[
\mbox{Fixed Blocks:} \quad \beta_j=\mu_{\bullet j}-\mu_{\bullet\bullet}
\qquad \hat{\beta}_j = \overline{Y}_{\bullet j} - \overline{Y}_{\bullet\bullet}
\qquad  \sum_{j=1}^b\beta_j=\sum_{j=1}^b\hat{\beta}_j=0
\]</span>
For the fixed block case, we obtain the following model for <span class="math inline">\(Y_{ij}\)</span> and the treatment
means <span class="math inline">\(\overline{Y}_{i\bullet}\)</span>.</p>
<p><span class="math display">\[
E\left\{Y_{ij}\right\} =\mu_{\bullet\bullet} + \tau_i + \beta_j \qquad
V\left\{Y_{ij}\right\} = \sigma^2\qquad
\mbox{COV}\left\{Y_{ij},Y_{i&#39;j&#39;}\right\}=0 \quad \forall i\ne i&#39;,j\ne j&#39;
\]</span>
<span class="math display">\[
E\left\{\overline{Y}_{i\bullet}\right\}=
E\left\{\frac{1}{b}\sum_{j=1}^bY_{ij}\right\}=
\frac{1}{b}\sum_{j=1}^b
E\left\{Y_{ij}\right\}=
\frac{1}{b}\sum_{j=1}^b\left(\mu_{\bullet\bullet} + \tau_i + \beta_j\right)=
\mu_{\bullet\bullet} + \tau_i
\]</span>
<span class="math display">\[
V\left\{\overline{Y}_{i\bullet}\right\}=
V\left\{\frac{1}{b}\sum_{j=1}^bY_{ij}\right\}=
\frac{1}{b^2}\sum_{j=1}^b
V\left\{Y_{ij}\right\}=
\frac{1}{b^2}\sum_{j=1}^b\sigma^2=\frac{\sigma^2}{b}
\]</span></p>
<p><span class="math display">\[
\mbox{Random Blocks:} \quad
\beta_j \sim NID\left(0,\sigma_{\beta}^2\right)
\qquad  \mbox{COV}\left\{\beta_j,\epsilon_{ij}\right\}=0
\qquad \hat{\beta}_j = \overline{Y}_{\bullet j} - \overline{Y}_{\bullet\bullet}
\qquad  \sum_{j=1}^b\hat{\beta}_j=0
\]</span>
For the random block case, we obtain the following model for <span class="math inline">\(Y_{ij}\)</span> and the treatment
means <span class="math inline">\(\overline{Y}_{i\bullet}\)</span>.</p>
<p>The random block effects and the random errors are assumed independent.
By the structure of the estimators the estimated <span class="math inline">\(\beta_j\)</span> sum to zero, but it’s
the population of <span class="math inline">\(\beta_j\)</span> that has mean 0.
For the random block case, we obtain the following model for <span class="math inline">\(Y_{ij}\)</span>.</p>
<p><span class="math display">\[
E\left\{Y_{ij}\right\} =\mu_{\bullet\bullet} + \tau_i  \qquad
V\left\{Y_{ij}\right\} = \sigma_{\beta}^2 + \sigma^2
\qquad
\mbox{COV}\left\{Y_{ij},Y_{i&#39;j&#39;}\right\}=
\left\{ \begin{array}{r@{\quad:\quad}l}
    \sigma_{\beta}^2+\sigma^2 &amp; i=i&#39;,j=j&#39; \\
    \sigma_{\beta}^2 &amp; i\ne i&#39;,j=j&#39; \\
    0 &amp; \forall i,i&#39;, j\ne j&#39;
    \end{array} \right.
\]</span></p>
<p>Two measurements (for different treatments) within the same block are correlated.
Measurements across different blocks are independent.</p>
<p><span class="math display">\[
E\left\{Y_{ij}\right\} =\mu_{\bullet\bullet} + \tau_i  \qquad
V\left\{Y_{ij}\right\} =
\sigma_{\beta}^2+\sigma^2\qquad
\mbox{COV}\left\{Y_{ij},Y_{i&#39;j}\right\}=\sigma_{\beta}^2 \quad \forall i\ne i&#39;
\]</span></p>
<p><span class="math display">\[
E\left\{\overline{Y}_{i\bullet}\right\}=
E\left\{\frac{1}{b}\sum_{j=1}^bY_{ij}\right\}=
\frac{1}{b}\sum_{j=1}^b
E\left\{Y_{ij}\right\}=
\frac{1}{b}\sum_{j=1}^b\left(\mu_{\bullet\bullet} + \tau_i\right)=
\mu_{\bullet\bullet} + \tau_i
\]</span>
<span class="math display">\[
V\left\{\overline{Y}_{i\bullet}\right\}=
V\left\{\frac{1}{b}\sum_{j=1}^bY_{ij}\right\}=
\frac{1}{b^2}\sum_{j=1}^b
V\left\{Y_{ij}\right\} =
\frac{1}{b^2}\sum_{j=1}^b\left[\sigma_{\beta}^2+\sigma^2\right]=\frac{\sigma_{\beta}^2+\sigma^2}{b}
\]</span>
The Covariance of two different treatment means <span class="math inline">\(\overline{Y}_{i\bullet}\)</span>
and <span class="math inline">\(\overline{Y}_{i&#39;\bullet}\)</span> is obtained
below.
<span class="math display">\[
\mbox{COV}\left\{\overline{Y}_{i\bullet},\overline{Y}_{i&#39;\bullet}\right\}=
\mbox{COV}\left\{\frac{1}{b}\sum_{j=1}^bY_{ij},\frac{1}{b}\sum_{j=1}^bY_{i&#39;j}\right\}=
\frac{1}{b^2}\mbox{COV}\left\{Y_{i1}+\cdots Y_{ib},Y_{i&#39;1}+\cdots +Y_{i&#39;b}\right\}=
\]</span></p>
<p><span class="math display">\[=\frac{1}{b^2}\left[b\sigma_{\beta}^2+b(b-1)(0)\right]=
\frac{\sigma_{\beta}^2}{b}
\]</span>
The fitted values and residuals are similar to other models described previously.</p>
<p><span class="math display">\[
\hat{Y}_{ij} = \hat{\mu}_{\bullet\bullet} + \hat{\tau}_i + \hat{\beta_j}
= \overline{Y}_{i\bullet} + \overline{Y}_{\bullet j} - \overline{Y}_{\bullet\bullet}
\qquad  e_{ij} = Y_{ij}-\hat{Y}_{ij} =
Y_{ij}-\overline{Y}_{i\bullet} - \overline{Y}_{\bullet j} + \overline{Y}_{\bullet\bullet}
\]</span></p>
<p>Before setting up the Analysis of Variance, we state the mean and variance structure for the treatment means for fixed and random blocks. In each case
<span class="math inline">\(E\left\{\overline{Y}_{i\bullet}\right\} = \mu+\tau_i\)</span>.</p>
<p><span class="math display">\[
\mbox{Fixed Blocks:} \quad
V\left\{\overline{Y}_{i\bullet}\right\}=\frac{\sigma^2}{b} \qquad
i\ne i&#39;: \quad
\mbox{COV}\left\{\overline{Y}_{i\bullet},\overline{Y}_{i&#39;\bullet}\right\}=0 \qquad
V\left\{\overline{Y}_{i\bullet}-\overline{Y}_{i&#39;\bullet}\right\}=\frac{2\sigma^2}{b}
\]</span></p>
<p><span class="math display">\[
\mbox{Random Blocks:} \quad
V\left\{\overline{Y}_{i\bullet}\right\}=\frac{\sigma_{\beta}^2+\sigma^2}{b} \qquad
i\ne i&#39;: \quad
\mbox{COV}\left\{\overline{Y}_{i\bullet},\overline{Y}_{i&#39;\bullet}\right\}=
\frac{\sigma_{\beta}^2}{b}\]</span></p>
<p><span class="math display">\[
V\left\{\overline{Y}_{i\bullet}-\overline{Y}_{i&#39;\bullet}\right\}=
2\left(\frac{\sigma_{\beta}^2+\sigma^2}{b}\right)-2\left(\frac{\sigma_{\beta}^2}{b}\right)=
\frac{2\sigma^2}{b}
\]</span></p>
<p>Thus, while the variances of the treatment means differ depending on whether blocks are fixed or random, the <strong>variances of the difference in the treatment means are the same</strong>.</p>
<p><strong>Example 10.1 - Sensory Analysis of Soy Sauce Recipes</strong></p>
<p>A study compared <span class="math inline">\(r=4\)</span> soy sauce recipes, each judged by a panel of <span class="math inline">\(b=8\)</span> trained raters <span class="citation">(<a href="#ref-fidaleo_2012">Fidaleo et al. 2012</a>)</span>.
The <span class="math inline">\(r=4\)</span> soy sauce recipes are given below, this being treated as a fixed factor (only recipes of interest).</p>
<ul>
<li><strong>Recipe 1</strong> - Original Soy Sauce</li>
<li><strong>Recipe 2</strong> - Electrodialyzed desalted Soy Sauce</li>
<li><strong>Recipe 3</strong> - Recipe 1 diluted at electric conductivity = 2.3 S/m</li>
<li><strong>Recipe 4</strong> - Recipe 2 re-salted to original level</li>
</ul>
<p>In sensory studies such as this, there is a debate among researchers whether raters (blocks) should be treated as a fixed or random factor.</p>
<ul>
<li><strong>Fixed Blocks</strong> - These are the only raters of interest to the researchers (possibly the only raters employed by this company).</li>
<li><strong>Random Blocks</strong> - The researchers are interested in generalizing these findings to a population of trained raters (these 8 raters being a sample from that population).</li>
</ul>
<p>Based on the sample values reported in this paper, we will construct population models for the fixed and random blocks cases. These were ratings on a 4-point scale (all numbers have been multiplied by 10 to keep variances from being so small). The response these are based on was appearance/color. Parameter values used are given here.</p>
<p><span class="math display">\[
\mu_{\bullet\bullet}=32 \qquad \tau_1=4 \quad \tau_2=3 \quad \tau_3=-13
\quad \tau_4=6  \qquad \sigma^2=11.56 \quad \sigma = 3.4
\]</span>
<span class="math display">\[
\mbox{Fixed Blocks:} \quad \beta_1,\ldots, \beta_8 = \mbox{ -5.30 to 5.30 by 1.514}
\qquad \mbox{Random Blocks:} \quad \sigma_{\beta}^2=13.76 \quad \sigma_{\beta}=3.71
\]</span>
The variance among block effects was chosen so that the following equality holds. This makes the models comparable with respect to variability in the block effects (see <span class="math inline">\(E\{MSBL\}\)</span> in the next sub-section).
<span class="math display">\[
\sigma_{\beta}^2 = \frac{\sum_{j=1}^8\beta_j^2}{8-1}=\frac{(-5.300)^2+\cdots+(5.300)^2}{7}=13.76
\]</span>
We will generate 100000 samples from this model (one for fixed block effects, one for random block effects). The algorithms are described here.</p>
<p><strong>Fixed Effects</strong></p>
<ul>
<li>Generate <span class="math inline">\(n_T=rb=4(8)\)</span> pseudo <span class="math inline">\(\epsilon_{11}, \ldots , \epsilon_{48} \sim NID\left(0,3.4^2\right)\)</span></li>
<li>Assign <span class="math inline">\(Y_{ij}^F=\mu_{\bullet\bullet} + \tau_i + \beta_j^F + \epsilon_{ij} \qquad
i=1,\ldots,4; \quad j=1,\ldots,8\)</span></li>
<li>Compute and save <span class="math inline">\(\overline{Y}_{1\bullet}^F,\ldots,\overline{Y}_{4\bullet}^F\)</span></li>
<li>Obtain (across samples) the mean and variance of
<span class="math inline">\(\overline{Y}_{1\bullet}^F,\ldots,\overline{Y}_{4\bullet}^F\)</span></li>
<li>Obtain (across samples) the mean and variance of the differences among
<span class="math inline">\(\overline{Y}_{1\bullet}^F,\ldots,\overline{Y}_{4\bullet}^F\)</span></li>
</ul>
<p><strong>Random Effects</strong></p>
<ul>
<li>Generate <span class="math inline">\(n_T=rb=4(8)\)</span> pseudo <span class="math inline">\(\epsilon_{11}, \ldots , \epsilon_{48} \sim NID\left(0,3.4^2\right)\)</span></li>
<li>Generate <span class="math inline">\(b=8\)</span> pseudo <span class="math inline">\(\beta_1^R,\ldots , \beta_8^R \sim NID\left(0,3.71^2\right)\)</span></li>
<li>Assign <span class="math inline">\(Y_{ij}^R=\mu_{\bullet\bullet} + \tau_i + \beta_j^R + \epsilon_{ij} \qquad
i=1,\ldots,4; \quad j=1,\ldots,8\)</span></li>
<li>Compute and save <span class="math inline">\(\overline{Y}_{1\bullet}^R,\ldots,\overline{Y}_{4\bullet}^R\)</span></li>
<li>Obtain (across samples) the mean and variance of
<span class="math inline">\(\overline{Y}_{1\bullet}^R,\ldots,\overline{Y}_{4\bullet}^R\)</span></li>
<li>Obtain (across samples) the mean and variance of the differences among
<span class="math inline">\(\overline{Y}_{1\bullet}^R,\ldots,\overline{Y}_{4\bullet}^R\)</span></li>
</ul>
<p>For each model (fixed and random blocks), the theoretical means for the
recipe means and for differences among the means are given below.</p>
<p><span class="math display">\[
E\{\overline{Y}_{i\bullet}\}=\mu_i=\mu_{\bullet\bullet}+ \tau_i  \qquad
E\{\overline{Y}_{i\bullet}-\overline{Y}_{i&#39;\bullet}\}=
\mu_i-\mu_{i&#39;} = \tau_i - \tau_{i&#39;}  
\]</span>
For fixed block effects, the theoretical variances of the recipe means and of the
differences among the means are given below.</p>
<p><span class="math display">\[
\sigma^2\{\overline{Y}_{i\bullet}\}=\frac{\sigma^2}{b}=\frac{11.56}{8}=1.445  \qquad
\sigma^2\{\overline{Y}_{i\bullet}-\overline{Y}_{i&#39;\bullet}\}=
\frac{2\sigma^2}{b}=\frac{2(11.56)}{8}=2.90  
\]</span>
For random block effects, the theoretical variances of the recipe means and of the
differences among the means are given below.</p>
<p><span class="math display">\[
\sigma^2\{\overline{Y}_{i\bullet}\}=\frac{\sigma_{\beta}^2+\sigma^2}{b}=\frac{13.76+11.56}{8}=3.165  \qquad
\sigma^2\{\overline{Y}_{i\bullet}-\overline{Y}_{i&#39;\bullet}\}=
\frac{2\sigma^2}{b}=\frac{2(11.56)}{8}=2.90  
\]</span></p>
<pre><code>## [1] -5.3000000 -3.7857143 -2.2714286 -0.7571429  0.7571429  2.2714286  3.7857143
## [8]  5.3000000</code></pre>
<pre><code>## [1] 13.75837</code></pre>
<pre><code>## [1] 3.709227</code></pre>
<pre><code>##             Mean(Fixed) Mean(Random) Var(Fixed) Var(Random)
## Ybar1            36.006       36.006      1.438       3.167
## Ybar2            34.998       34.997      1.439       3.154
## Ybar3            19.001       19.001      1.441       3.148
## Ybar4            37.997       37.997      1.446       3.157
## Ybar2-Ybar1      -1.009       -1.009      2.867       2.867
## Ybar3-Ybar1     -17.005      -17.005      2.892       2.892
## Ybar3-Ybar2     -15.997      -15.997      2.888       2.888
## Ybar4-Ybar1       1.990        1.990      2.878       2.878
## Ybar4-Ybar2       2.999        2.999      2.874       2.874
## Ybar4-Ybar3      18.996       18.996      2.889       2.889</code></pre>
<p>All of the empirical results are very close to the theoretical results (as they should be). The difference arises when considering
<span class="math inline">\(V\left\{\overline{Y}_{i\bullet}\right\}\)</span>
when block effects are generated as fixed effects versus when they are generated as random effects.</p>
<p><span class="math display">\[\nabla\]</span></p>
</div>
</div>
<div id="analysis-of-variance-and-the-f-test" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Analysis of Variance and the <span class="math inline">\(F\)</span>-test<a href="block-designs.html#analysis-of-variance-and-the-f-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We use the sums of squares as previously set up, with the Sum of Squares Error <span class="math inline">\(SSE\)</span>, technically being the Sum of Squares for the Treatment by Block Interaction as there is only one replicate per combination of Treatment and Block. The sums of squares, degrees of freedom, and expected mean squares are given here. In this model, we assume that there is no Treatment/Block interaction. Tukey’s One-Degree of Freedom Test for Non-Additivity can be used to check this assumption.</p>
<p><span class="math display">\[
\mbox{Total:} \quad SSTO = \sum_{i=1}^r\sum_{j=1}^b \left(Y_{ij}-\overline{Y}_{\bullet\bullet}\right)^2 \qquad \qquad df_{TO}=rb-1
\]</span>
<span class="math display">\[
\mbox{Treatments:} \quad SSTR =
b\sum_{i=1}^r \left(Y_{i\bullet}-\overline{Y}_{\bullet\bullet}\right)^2
\qquad \qquad df_{TR}=r-1
\]</span>
<span class="math display">\[
E\left\{MSTR\right\}=
\sigma^2+\frac{b\sum_{i=1}^r\tau_i^2}{r-1}
\]</span></p>
<p><span class="math display">\[
\mbox{Blocks:} \quad SSBL =
r\sum_{j=1}^b \left(Y_{\bullet j}-\overline{Y}_{\bullet\bullet}\right)^2
\qquad \qquad df_{BL}=b-1
\]</span>
<span class="math display">\[
\mbox{Fixed Blocks:} \quad
E\left\{MSBL\right\}=
\sigma^2+\frac{r\sum_{j=1}^b\beta_j^2}{b-1}  \qquad
\mbox{Random Blocks:} \quad
E\left\{MSBL\right\}=
\sigma^2+ r\sigma_{\beta}^2
\]</span></p>
<p><span class="math display">\[
\mbox{Error (TRxBL):} \quad
SSE = \sum_{i=1}^a\sum_{j=1}^b\left(Y_{ij}-\overline{Y}_{i\bullet} - \overline{Y}_{\bullet j} + \overline{Y}_{\bullet\bullet}\right)^2 \]</span>
<span class="math display">\[df_E=(r-1)(b-1) \qquad
E\left\{MSE\right\}=
\sigma^2
\]</span></p>
<p>To test for treatment effects, we compute the ratio of <span class="math inline">\(MSTR\)</span> to <span class="math inline">\(MSE\)</span> with the <span class="math inline">\(F\)</span>-test.
Software will automatically compute the <span class="math inline">\(F\)</span>-statistic for blocks as well,
but the primary interest is typically treatment effects. However, when blocks are random
it may be of interest to estimate <span class="math inline">\(\sigma_{\beta}^2\)</span>, the variance of the block effects.</p>
<p><span class="math display">\[
H_0: \tau_1=\ldots = \tau_r=0 \qquad
TS: F_{TR}^*=\frac{MSTR}{MSE} \qquad
RR: F_{TR}^* \ge F_{1-\alpha;r-1,(r-1)(b-1)}
\]</span></p>
<p>Any contrasts or pairwise comparisons can be carried out as in the Completely Randomized Design. For Tukey’s HSD for all possible comparisons,
we compute HSD, which will be the same for all pairs <span class="math inline">\(\left(n_i=b\right)\)</span> and can obtain simultaneous <span class="math inline">\((1-\alpha)100\%\)</span> Confidence Intervals for <span class="math inline">\(\tau_i - \tau_{i`}\)</span> as follows.</p>
<p><span class="math display">\[
HSD = q_{1-\alpha;r,(r-1)(b-1)}\sqrt{\frac{MSE}{b}}  
\]</span>
<span class="math display">\[
(1-\alpha)100\% \mbox{ CI for } \tau_i-\tau_{i&#39;}: \qquad
\left(\overline{Y}_{i\bullet}-\overline{Y}_{i&#39;\bullet}\right) \pm HSD
\]</span></p>
<p><strong>Example 10.2 - Methods of Presenting Weather Information to Pilots</strong></p>
<p>A study compared <span class="math inline">\(r=3\)</span> cockpit weather displays (treatments) for pilots in terms of information recall <span class="citation">(<a href="#ref-ohare_2009">O’Hare and Stenhouse 2009</a>)</span> There were <span class="math inline">\(b=23\)</span> pilots (blocks) who were exposed to each display on a flight simulator. The three displays are described below. The response <span class="math inline">\(Y\)</span>, is the percent of information correctly recalled by the pilot.</p>
<ul>
<li>Ordinary text - English phrases <span class="math inline">\((i=1)\)</span></li>
<li>Redesigned graphical display <span class="math inline">\((i=2)\)</span></li>
<li>Old graphical display <span class="math inline">\((i=3)\)</span></li>
</ul>
<p>Using R, we will set up the Analysis of Variance directly, then use the <strong>aov</strong> function along with <strong>TukeyHSD</strong> function to confirm results.</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="block-designs.html#cb315-1" tabindex="-1"></a>pwd <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/pilot_weatherdisplay.csv&quot;</span>)</span>
<span id="cb315-2"><a href="block-designs.html#cb315-2" tabindex="-1"></a><span class="fu">head</span>(pwd,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##   trt.y blk.y corrRecall
## 1     1     1   45.68415
## 2     1     2   63.76311
## 3     1     3   92.90009</code></pre>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="block-designs.html#cb317-1" tabindex="-1"></a><span class="fu">interaction.plot</span>(pwd<span class="sc">$</span>blk.y, pwd<span class="sc">$</span>trt.y, pwd<span class="sc">$</span>corrRecall,</span>
<span id="cb317-2"><a href="block-designs.html#cb317-2" tabindex="-1"></a>                 <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;green4&quot;</span>), <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb317-3"><a href="block-designs.html#cb317-3" tabindex="-1"></a>                 <span class="at">xlab=</span><span class="st">&quot;subject&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;correct values&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_STA4211Notes1_files/figure-html/ch0902-1.png" width="672" /></p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="block-designs.html#cb318-1" tabindex="-1"></a><span class="do">## Direct calculations</span></span>
<span id="cb318-2"><a href="block-designs.html#cb318-2" tabindex="-1"></a>all.mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(pwd<span class="sc">$</span>corrRecall)</span>
<span id="cb318-3"><a href="block-designs.html#cb318-3" tabindex="-1"></a>trt.mean <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(pwd<span class="sc">$</span>corrRecall, pwd<span class="sc">$</span>trt.y, mean))</span>
<span id="cb318-4"><a href="block-designs.html#cb318-4" tabindex="-1"></a>blk.mean <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(pwd<span class="sc">$</span>corrRecall, pwd<span class="sc">$</span>blk.y, mean))</span>
<span id="cb318-5"><a href="block-designs.html#cb318-5" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">length</span>(trt.mean)</span>
<span id="cb318-6"><a href="block-designs.html#cb318-6" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">length</span>(blk.mean)</span>
<span id="cb318-7"><a href="block-designs.html#cb318-7" tabindex="-1"></a></span>
<span id="cb318-8"><a href="block-designs.html#cb318-8" tabindex="-1"></a>SSTO <span class="ot">&lt;-</span> <span class="fu">sum</span>((pwd<span class="sc">$</span>corrRecall <span class="sc">-</span> all.mean)<span class="sc">^</span><span class="dv">2</span>); df_TO <span class="ot">&lt;-</span> r<span class="sc">*</span>b<span class="dv">-1</span></span>
<span id="cb318-9"><a href="block-designs.html#cb318-9" tabindex="-1"></a>SSTR <span class="ot">&lt;-</span> b<span class="sc">*</span><span class="fu">sum</span>((trt.mean<span class="sc">-</span>all.mean)<span class="sc">^</span><span class="dv">2</span>); df_TR <span class="ot">&lt;-</span> r<span class="dv">-1</span></span>
<span id="cb318-10"><a href="block-designs.html#cb318-10" tabindex="-1"></a>MSTR <span class="ot">&lt;-</span> SSTR <span class="sc">/</span> df_TR</span>
<span id="cb318-11"><a href="block-designs.html#cb318-11" tabindex="-1"></a>SSBL <span class="ot">&lt;-</span> r<span class="sc">*</span><span class="fu">sum</span>((blk.mean<span class="sc">-</span>all.mean)<span class="sc">^</span><span class="dv">2</span>); df_BL <span class="ot">&lt;-</span> b<span class="dv">-1</span></span>
<span id="cb318-12"><a href="block-designs.html#cb318-12" tabindex="-1"></a>MSBL <span class="ot">&lt;-</span> SSBL <span class="sc">/</span> df_BL</span>
<span id="cb318-13"><a href="block-designs.html#cb318-13" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> SSTO <span class="sc">-</span> SSTR <span class="sc">-</span> SSBL; df_E <span class="ot">&lt;-</span> df_TO <span class="sc">-</span> df_TR <span class="sc">-</span> df_BL</span>
<span id="cb318-14"><a href="block-designs.html#cb318-14" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> SSE <span class="sc">/</span> df_E</span>
<span id="cb318-15"><a href="block-designs.html#cb318-15" tabindex="-1"></a>Fstar <span class="ot">=</span> MSTR <span class="sc">/</span> MSE</span>
<span id="cb318-16"><a href="block-designs.html#cb318-16" tabindex="-1"></a></span>
<span id="cb318-17"><a href="block-designs.html#cb318-17" tabindex="-1"></a>aov.out1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df_TR, SSTR, MSTR, Fstar, <span class="fu">qf</span>(.<span class="dv">95</span>,df_TR, df_E),</span>
<span id="cb318-18"><a href="block-designs.html#cb318-18" tabindex="-1"></a>                  <span class="dv">1</span><span class="sc">-</span><span class="fu">pf</span>(Fstar,df_TR, df_E))</span>
<span id="cb318-19"><a href="block-designs.html#cb318-19" tabindex="-1"></a>aov.out2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df_BL, SSBL, MSBL, MSBL<span class="sc">/</span>MSE, <span class="fu">df</span>(.<span class="dv">95</span>,df_BL,df_E),</span>
<span id="cb318-20"><a href="block-designs.html#cb318-20" tabindex="-1"></a>                  <span class="dv">1</span><span class="sc">-</span><span class="fu">pf</span>(MSBL<span class="sc">/</span>MSE, df_BL, df_E))</span>
<span id="cb318-21"><a href="block-designs.html#cb318-21" tabindex="-1"></a>aov.out3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df_E, SSE, MSE, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>)</span>
<span id="cb318-22"><a href="block-designs.html#cb318-22" tabindex="-1"></a>aov.out4 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df_TO, SSTO, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>)</span>
<span id="cb318-23"><a href="block-designs.html#cb318-23" tabindex="-1"></a>aov.out <span class="ot">&lt;-</span> <span class="fu">rbind</span>(aov.out1, aov.out2, aov.out3, aov.out4)</span>
<span id="cb318-24"><a href="block-designs.html#cb318-24" tabindex="-1"></a><span class="fu">colnames</span>(aov.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;df&quot;</span>, <span class="st">&quot;SS&quot;</span>, <span class="st">&quot;MS&quot;</span>, <span class="st">&quot;F*&quot;</span>, <span class="st">&quot;F(.95)&quot;</span>, <span class="st">&quot;P(&gt;F*)&quot;</span>)</span>
<span id="cb318-25"><a href="block-designs.html#cb318-25" tabindex="-1"></a><span class="fu">rownames</span>(aov.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Treatments&quot;</span>, <span class="st">&quot;Blocks&quot;</span>, <span class="st">&quot;Error&quot;</span>, <span class="st">&quot;Total&quot;</span>)</span>
<span id="cb318-26"><a href="block-designs.html#cb318-26" tabindex="-1"></a><span class="fu">round</span>(aov.out,<span class="dv">4</span>)</span></code></pre></div>
<pre><code>##            df       SS        MS     F* F(.95) P(&gt;F*)
## Treatments  2  1582.86  791.4300 3.3300 3.2093  0.045
## Blocks     22 42814.57 1946.1167 8.1884 1.1164  0.000
## Error      44 10457.33  237.6667     NA     NA     NA
## Total      68 54854.76        NA     NA     NA     NA</code></pre>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="block-designs.html#cb320-1" tabindex="-1"></a>HSD <span class="ot">&lt;-</span> <span class="fu">qtukey</span>(.<span class="dv">95</span>, r, df_E) <span class="sc">*</span> <span class="fu">sqrt</span>(MSE<span class="sc">/</span>b)</span>
<span id="cb320-2"><a href="block-designs.html#cb320-2" tabindex="-1"></a>Tukey.out <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">10</span><span class="sc">*</span>r<span class="sc">*</span>(r<span class="dv">-1</span>)<span class="sc">/</span><span class="dv">2</span>),<span class="at">ncol=</span><span class="dv">10</span>)</span>
<span id="cb320-3"><a href="block-designs.html#cb320-3" tabindex="-1"></a></span>
<span id="cb320-4"><a href="block-designs.html#cb320-4" tabindex="-1"></a>row.count <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb320-5"><a href="block-designs.html#cb320-5" tabindex="-1"></a><span class="cf">for</span> (i1 <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>r) {</span>
<span id="cb320-6"><a href="block-designs.html#cb320-6" tabindex="-1"></a>  <span class="cf">for</span> (i2 <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(i1<span class="dv">-1</span>)) {</span>
<span id="cb320-7"><a href="block-designs.html#cb320-7" tabindex="-1"></a>    row.count <span class="ot">&lt;-</span> row.count <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb320-8"><a href="block-designs.html#cb320-8" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">1</span>] <span class="ot">&lt;-</span> i1</span>
<span id="cb320-9"><a href="block-designs.html#cb320-9" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">2</span>] <span class="ot">&lt;-</span> i2</span>
<span id="cb320-10"><a href="block-designs.html#cb320-10" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">3</span>] <span class="ot">&lt;-</span> trt.mean[i1]</span>
<span id="cb320-11"><a href="block-designs.html#cb320-11" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">4</span>] <span class="ot">&lt;-</span> trt.mean[i2]</span>
<span id="cb320-12"><a href="block-designs.html#cb320-12" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">5</span>] <span class="ot">&lt;-</span> trt.mean[i1] <span class="sc">-</span> trt.mean[i2]</span>
<span id="cb320-13"><a href="block-designs.html#cb320-13" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">2</span><span class="sc">*</span>MSE<span class="sc">/</span>b)</span>
<span id="cb320-14"><a href="block-designs.html#cb320-14" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">7</span>] <span class="ot">&lt;-</span> HSD</span>
<span id="cb320-15"><a href="block-designs.html#cb320-15" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">8</span>] <span class="ot">&lt;-</span> Tukey.out[row.count,<span class="dv">5</span>] <span class="sc">-</span> HSD</span>
<span id="cb320-16"><a href="block-designs.html#cb320-16" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">9</span>] <span class="ot">&lt;-</span> Tukey.out[row.count,<span class="dv">5</span>] <span class="sc">+</span> HSD</span>
<span id="cb320-17"><a href="block-designs.html#cb320-17" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">10</span>] <span class="ot">&lt;-</span> </span>
<span id="cb320-18"><a href="block-designs.html#cb320-18" tabindex="-1"></a>      <span class="dv">1</span><span class="sc">-</span><span class="fu">ptukey</span>(<span class="fu">abs</span>(Tukey.out[row.count,<span class="dv">5</span>])<span class="sc">/</span><span class="fu">sqrt</span>(MSE<span class="sc">/</span>b),r,df_E)</span>
<span id="cb320-19"><a href="block-designs.html#cb320-19" tabindex="-1"></a>  }</span>
<span id="cb320-20"><a href="block-designs.html#cb320-20" tabindex="-1"></a>}</span>
<span id="cb320-21"><a href="block-designs.html#cb320-21" tabindex="-1"></a><span class="fu">colnames</span>(Tukey.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;i&quot;</span>, <span class="st">&quot;i&#39;&quot;</span>, <span class="st">&quot;ybar_i&quot;</span>, <span class="st">&quot;ybar_i&#39;&quot;</span>, <span class="st">&quot;diff&quot;</span>, <span class="st">&quot;Std Err&quot;</span>, <span class="st">&quot;HSD&quot;</span>,</span>
<span id="cb320-22"><a href="block-designs.html#cb320-22" tabindex="-1"></a>                         <span class="st">&quot;LB&quot;</span>, <span class="st">&quot;UB&quot;</span>, <span class="st">&quot;p adj&quot;</span>)</span>
<span id="cb320-23"><a href="block-designs.html#cb320-23" tabindex="-1"></a><span class="fu">round</span>(Tukey.out,<span class="dv">4</span>)</span></code></pre></div>
<pre><code>##      i i&#39; ybar_i ybar_i&#39; diff Std Err     HSD       LB      UB  p adj
## [1,] 2  1   63.7    52.3 11.4  4.5461 11.0264   0.3736 22.4264 0.0413
## [2,] 3  1   55.6    52.3  3.3  4.5461 11.0264  -7.7264 14.3264 0.7495
## [3,] 3  2   55.6    63.7 -8.1  4.5461 11.0264 -19.1264  2.9264 0.1875</code></pre>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="block-designs.html#cb322-1" tabindex="-1"></a><span class="do">## Using aov and TukeyHSD</span></span>
<span id="cb322-2"><a href="block-designs.html#cb322-2" tabindex="-1"></a></span>
<span id="cb322-3"><a href="block-designs.html#cb322-3" tabindex="-1"></a>pwd.mod1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(corrRecall <span class="sc">~</span> <span class="fu">factor</span>(trt.y) <span class="sc">+</span> <span class="fu">factor</span>(blk.y), <span class="at">data=</span>pwd)</span>
<span id="cb322-4"><a href="block-designs.html#cb322-4" tabindex="-1"></a><span class="fu">anova</span>(pwd.mod1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: corrRecall
##               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## factor(trt.y)  2   1583  791.43  3.3300   0.04501 *  
## factor(blk.y) 22  42815 1946.12  8.1884 2.253e-09 ***
## Residuals     44  10457  237.67                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="block-designs.html#cb324-1" tabindex="-1"></a>HSD.trt.y <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(pwd.mod1, <span class="st">&quot;factor(trt.y)&quot;</span>)</span>
<span id="cb324-2"><a href="block-designs.html#cb324-2" tabindex="-1"></a>HSD.trt.y</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = corrRecall ~ factor(trt.y) + factor(blk.y), data = pwd)
## 
## $`factor(trt.y)`
##     diff         lwr       upr     p adj
## 2-1 11.4   0.3736119 22.426388 0.0413298
## 3-1  3.3  -7.7263883 14.326388 0.7495471
## 3-2 -8.1 -19.1263883  2.926388 0.1874886</code></pre>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="block-designs.html#cb326-1" tabindex="-1"></a><span class="fu">plot</span>(HSD.trt.y, <span class="at">las=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;green4&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_STA4211Notes1_files/figure-html/ch0902-2.png" width="672" />
Thus, there are differences among the three cockpit weather displays. In particular, pilots had higher recall with the redesigned graphical display <span class="math inline">\((i=2)\)</span> than the ordinary text display <span class="math inline">\((i=1)\)</span>.</p>
<p><span class="math display">\[\nabla\]</span></p>
<div id="checking-model-assumptions" class="section level3 hasAnchor" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Checking Model Assumptions<a href="block-designs.html#checking-model-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Some methods for checking model assumptions are given in this sub-section, involving the error terms for the model.</p>
<ul>
<li>Stripchart of residuals versus blocks to visually observe whether the variance of errors is constant across blocks (each block received each treatment)</li>
<li>Plots of residuals versus fitted values to observe whether residual variance is related to mean</li>
<li>Plot of residuals versus time order when experiment is conducted sequentially or when blocks are days to observe whether serial correlation is present</li>
<li>Block x Treatment Interactions - Can be tested using Tukey’s ODOFNA test. If significant, the remainder <span class="math inline">\(MSE^*\)</span> can be used after removing the 1 degree of freedom <span class="math inline">\(SS\)</span> for interaction</li>
</ul>
<p><strong>Example 10.3 - Methods of Presenting Weather Information to Pilots</strong></p>
<p>Here we give examples of the model checks, with the exception of residuals versus time order, as that does not pertain to this study.</p>
<pre><code>##   trt.y blk.y corrRecall
## 1     1     1   45.68415
## 2     1     2   63.76311
## 3     1     3   92.90009</code></pre>
<p><img src="bookdownproj_STA4211Notes1_files/figure-html/ch0903-1.png" width="672" /><img src="bookdownproj_STA4211Notes1_files/figure-html/ch0903-2.png" width="672" /></p>
<pre><code>## 
## Tukey test on 5% alpha-level:
## 
## Test statistic: 0.05092 
## Critival value: 4.067 
## The additivity hypothesis cannot be rejected.</code></pre>
<p>While a few blocks (pilots) have little spread in his/her residuals based on the stripchart, the spread is reasonably equal across the <span class="math inline">\(b=23\)</span> pilots. Plus, there are only <span class="math inline">\(r=3\)</span> residuals per pilot.</p>
<p>The plot of the residuals versus predicted values does not show any evidence of “funneling” out as the fitted values increase, so constant variance seems reasonable.</p>
<p>Tukey’s ODOFNA test gives a very small test statistic, well below its critical value. This provides no evidence of an interaction between treatment (display of weather information) and block (pilot).</p>
<p><span class="math display">\[\nabla\]</span></p>
</div>
<div id="relative-efficiency-and-within-subject-variance-covariance-matrix" class="section level3 hasAnchor" number="10.2.2">
<h3><span class="header-section-number">10.2.2</span> Relative Efficiency and Within-Subject Variance-Covariance Matrix<a href="block-designs.html#relative-efficiency-and-within-subject-variance-covariance-matrix" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this sub-section, we consider two measures that come up in Randomized Block and Repeated Measures Designs.</p>
<ul>
<li><strong>Relative Efficiency</strong> - A measure of the ratio of the error variance of the Completely Randomized Design (CRD) to the Randomized Block Design (RBD)</li>
<li><strong>Within Subject Variance-Covariance Matrix</strong> - When blocks/subjects are random, the measurements within subjects are correlated. The assumptions are of equal variances for the <span class="math inline">\(r\)</span> treatments and equal covariances among the <span class="math inline">\(r(r-1)/2\)</span> pairs of treatments.</li>
</ul>
<p>For <strong>Relative Efficiency</strong>, we label <span class="math inline">\(\sigma_{CRD}^2\)</span> to be the error variance for a model based on a Completely Randomized Design and
<span class="math inline">\(\sigma_{RBD}^2\)</span> the error variance for the Randomized Block Design.
Recall that the goal of the RBD is to reduce the error variance, thus making more precise estimates of contrasts (smaller standard errors).</p>
<p>We define the following ratios in terms of true (unknown) variances and estimated variances from the RBD.</p>
<p><span class="math display">\[
E=\frac{\sigma_{CRD}^2}{\sigma_{RBD}^2}    \qquad \qquad
\hat{E}=\frac{s_{CRD}^2}{s_{RBD}^2} =
\frac{(b-1)MSBL+b(r-1)MSE}{(br-1)MSE}
\]</span>
Note that <span class="math inline">\((b-1)+b(r-1)=br-1\)</span>, so that <span class="math inline">\(\hat{E}\)</span> is a weighted
average of <span class="math inline">\(MSBL/MSE\)</span> and 1. The larger the ratio of <span class="math inline">\(MSBL/MSE\)</span>, the larger will be <span class="math inline">\(\hat{E}\)</span>. Then, experiments with large variability among blocks relative to error variability are more efficient.</p>
<p>The Relative Efficiency measures the multiple of the number of blocks from the RBD that would need to be the treatment sample size in a CRD to have comparable standard errors for contrasts.</p>
<p>Suppose that an experiment run as a RBD had <span class="math inline">\(b=5\)</span> blocks had a Relative Efficiency of <span class="math inline">\(\hat{E}=2\)</span>. Then an experiment run as a CRD would need
<span class="math inline">\(n=2(5)=10\)</span> units per treatments to have comparable standard errors for treatment contrasts.</p>
<p>Some authors describe a degrees of freedom adjustment for the estimated Relative Efficiency. In many cases, it makes little difference,
the formula is given below, with <span class="math inline">\(r\)</span> being the number of treatments and <span class="math inline">\(b\)</span> being the number of blocks.</p>
<p><span class="math display">\[
df_{CRD}=r(b-1) \quad df_{RBD}=(r-1)(b-1)  \qquad
\hat{E}^*=
\frac{\left(df_{RBD}+1\right)\left(df_{CRD}+3\right)}
     {\left(df_{RBD}+3\right)\left(df_{CRD}+1\right)}
     \hat{E}
\]</span></p>
<p>When blocks/subjects are random, then the responses <span class="math inline">\(Y\)</span> within blocks are correlated as described at the beginning of the chapter.</p>
<p><span class="math display">\[
V\left\{Y_{ij}\right\}=\sigma_{\beta}^2+\sigma^2 = \sigma_i^2
\qquad\qquad
i\ne i&#39;: \quad \mbox{COV}\left\{Y_{ij},Y_{i&#39;j}\right\}=\sigma_{\beta}^2=\sigma_{ii&#39;}
\]</span></p>
<p>For this model to be appropriate we need the following assumptions.</p>
<p><span class="math display">\[
\sigma_1^2=\cdots =\sigma_r^2 \qquad \sigma_{12}=\cdots =\sigma_{r-1,r}
\]</span>
In matrix form, the within-subject Variance-Covariance matrix can be written as follows, with a similar set of assumptions.</p>
<p><span class="math display">\[
\Sigma =
\begin{bmatrix}
\sigma_1^2 &amp; \sigma_{12} &amp; \cdots &amp; \sigma_{1r} \\
\sigma_{21} &amp; \sigma_2^2 &amp; \cdots &amp; \sigma_{2r} \\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
\sigma_{r1} &amp; \sigma_{r2} &amp; \cdots &amp; \sigma_r^2 \\
\end{bmatrix}
=
\begin{bmatrix}
\sigma^2 &amp; \sigma_{ii&#39;} &amp; \cdots &amp; \sigma_{ii&#39;} \\
\sigma_{ii&#39;} &amp; \sigma^2 &amp; \cdots &amp; \sigma_{ii&#39;} \\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
\sigma_{ii&#39;} &amp; \sigma_{ii&#39;} &amp; \cdots &amp; \sigma^2 \\
\end{bmatrix}
\]</span>
The sample version of the Variance-Covariance matrix is computed as follows.</p>
<p><span class="math display">\[
S =
\begin{bmatrix}
s_1^2 &amp; s_{12} &amp; \cdots &amp; s_{1r} \\
s_{21} &amp; s_2^2 &amp; \cdots &amp; s_{2r} \\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
s_{r1} &amp; s_{r2} &amp; \cdots &amp; s_r^2 \\
\end{bmatrix}
\]</span>
<span class="math display">\[
s_i^2 =
\frac{\sum_{j=1}^b\left(Y_{ij}-\overline{Y}_{i\bullet}\right)^2}{b-1}
\qquad
s_{ii&#39;} =
\frac{\sum_{j=1}^b\left(Y_{ij}-\overline{Y}_{i\bullet}\right)
                  \left(Y_{i&#39;j}-\overline{Y}_{i&#39;\bullet}\right)}{b-1}
\]</span>
There are tests of whether the Population Variance-Covariance
meets this assumption based on the Sample Variance-Covariance matrix,
but are beyond the scope of this course. A visual inspection of <span class="math inline">\(S\)</span> should be able to detect large discrepancies. Other structures (including an unstructured form) can be implemented using mixed model software packages. Also, transformations on <span class="math inline">\(Y\)</span> can be implemented (such as the Box-Cox transformation).</p>
<p>We will use the <strong>cov</strong> function by looping through the treatments to obtain the Variance-Covariance matrix, keeping in mind that <span class="math inline">\(\hat{\mbox{COV}}\{Y_{ij},Y_{ij}\}=\hat{V}\{Y_{ij}\}\)</span>.</p>
<p><strong>Example 10.4 - Methods of Presenting Weather Information to Pilots</strong></p>
<p>Here we compute the Relative Efficiency and the Sample Variance-Covariance matrix for the pilot weather information study based on direct calculations.</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="block-designs.html#cb329-1" tabindex="-1"></a>pwd <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/pilot_weatherdisplay.csv&quot;</span>)</span>
<span id="cb329-2"><a href="block-designs.html#cb329-2" tabindex="-1"></a><span class="fu">head</span>(pwd,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##   trt.y blk.y corrRecall
## 1     1     1   45.68415
## 2     1     2   63.76311
## 3     1     3   92.90009</code></pre>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="block-designs.html#cb331-1" tabindex="-1"></a><span class="do">## Direct calculations - Relative Efficiency</span></span>
<span id="cb331-2"><a href="block-designs.html#cb331-2" tabindex="-1"></a>all.mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(pwd<span class="sc">$</span>corrRecall)</span>
<span id="cb331-3"><a href="block-designs.html#cb331-3" tabindex="-1"></a>trt.mean <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(pwd<span class="sc">$</span>corrRecall, pwd<span class="sc">$</span>trt.y, mean))</span>
<span id="cb331-4"><a href="block-designs.html#cb331-4" tabindex="-1"></a>blk.mean <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(pwd<span class="sc">$</span>corrRecall, pwd<span class="sc">$</span>blk.y, mean))</span>
<span id="cb331-5"><a href="block-designs.html#cb331-5" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">length</span>(trt.mean)</span>
<span id="cb331-6"><a href="block-designs.html#cb331-6" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">length</span>(blk.mean)</span>
<span id="cb331-7"><a href="block-designs.html#cb331-7" tabindex="-1"></a></span>
<span id="cb331-8"><a href="block-designs.html#cb331-8" tabindex="-1"></a>SSTO <span class="ot">&lt;-</span> <span class="fu">sum</span>((pwd<span class="sc">$</span>corrRecall <span class="sc">-</span> all.mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb331-9"><a href="block-designs.html#cb331-9" tabindex="-1"></a>df_TO <span class="ot">&lt;-</span> r<span class="sc">*</span>b<span class="dv">-1</span></span>
<span id="cb331-10"><a href="block-designs.html#cb331-10" tabindex="-1"></a>SSTR <span class="ot">&lt;-</span> b<span class="sc">*</span><span class="fu">sum</span>((trt.mean<span class="sc">-</span>all.mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb331-11"><a href="block-designs.html#cb331-11" tabindex="-1"></a>df_TR <span class="ot">&lt;-</span> r<span class="dv">-1</span></span>
<span id="cb331-12"><a href="block-designs.html#cb331-12" tabindex="-1"></a>MSTR <span class="ot">&lt;-</span> SSTR <span class="sc">/</span> df_TR</span>
<span id="cb331-13"><a href="block-designs.html#cb331-13" tabindex="-1"></a>SSBL <span class="ot">&lt;-</span> r<span class="sc">*</span><span class="fu">sum</span>((blk.mean<span class="sc">-</span>all.mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb331-14"><a href="block-designs.html#cb331-14" tabindex="-1"></a>df_BL <span class="ot">&lt;-</span> b<span class="dv">-1</span></span>
<span id="cb331-15"><a href="block-designs.html#cb331-15" tabindex="-1"></a>MSBL <span class="ot">&lt;-</span> SSBL <span class="sc">/</span> df_BL</span>
<span id="cb331-16"><a href="block-designs.html#cb331-16" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> SSTO <span class="sc">-</span> SSTR <span class="sc">-</span> SSBL</span>
<span id="cb331-17"><a href="block-designs.html#cb331-17" tabindex="-1"></a>df_E <span class="ot">&lt;-</span> df_TO <span class="sc">-</span> df_TR <span class="sc">-</span> df_BL</span>
<span id="cb331-18"><a href="block-designs.html#cb331-18" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> SSE <span class="sc">/</span> df_E</span>
<span id="cb331-19"><a href="block-designs.html#cb331-19" tabindex="-1"></a></span>
<span id="cb331-20"><a href="block-designs.html#cb331-20" tabindex="-1"></a>df_CRD <span class="ot">&lt;-</span> b<span class="sc">*</span>(r<span class="dv">-1</span>)</span>
<span id="cb331-21"><a href="block-designs.html#cb331-21" tabindex="-1"></a>df_RBD <span class="ot">&lt;-</span> df_E</span>
<span id="cb331-22"><a href="block-designs.html#cb331-22" tabindex="-1"></a></span>
<span id="cb331-23"><a href="block-designs.html#cb331-23" tabindex="-1"></a>E.hat <span class="ot">&lt;-</span> ((b<span class="dv">-1</span>)<span class="sc">*</span>MSBL <span class="sc">+</span> b<span class="sc">*</span>(r<span class="dv">-1</span>)<span class="sc">*</span>MSE) <span class="sc">/</span> ((b<span class="sc">*</span>r<span class="dv">-1</span>)<span class="sc">*</span>MSE)</span>
<span id="cb331-24"><a href="block-designs.html#cb331-24" tabindex="-1"></a>E.hat.star <span class="ot">&lt;-</span>  ( ((df_RBD<span class="sc">+</span><span class="dv">1</span>)<span class="sc">*</span>(df_CRD<span class="sc">+</span><span class="dv">3</span>))<span class="sc">/</span>((df_RBD<span class="sc">+</span><span class="dv">3</span>)<span class="sc">*</span>(df_CRD<span class="sc">+</span><span class="dv">1</span>)) ) <span class="sc">*</span> E.hat</span>
<span id="cb331-25"><a href="block-designs.html#cb331-25" tabindex="-1"></a></span>
<span id="cb331-26"><a href="block-designs.html#cb331-26" tabindex="-1"></a>E.out <span class="ot">&lt;-</span> <span class="fu">cbind</span>(b, r, MSBL, MSE, E.hat, df_CRD, df_RBD, E.hat.star)</span>
<span id="cb331-27"><a href="block-designs.html#cb331-27" tabindex="-1"></a><span class="fu">colnames</span>(E.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;b&quot;</span>, <span class="st">&quot;r&quot;</span>, <span class="st">&quot;MSBL&quot;</span>, <span class="st">&quot;MSE&quot;</span>, <span class="st">&quot;E-hat&quot;</span>, <span class="st">&quot;df_CRD&quot;</span>, <span class="st">&quot;df_RBD&quot;</span>, <span class="st">&quot;E-hat*&quot;</span>)</span>
<span id="cb331-28"><a href="block-designs.html#cb331-28" tabindex="-1"></a><span class="fu">round</span>(E.out,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##       b r     MSBL     MSE E-hat df_CRD df_RBD E-hat*
## [1,] 23 3 1946.117 237.667 3.326     46     44   3.32</code></pre>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="block-designs.html#cb333-1" tabindex="-1"></a><span class="do">## Setting up the Sample Variance-Covariance matrix</span></span>
<span id="cb333-2"><a href="block-designs.html#cb333-2" tabindex="-1"></a></span>
<span id="cb333-3"><a href="block-designs.html#cb333-3" tabindex="-1"></a>S.mat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">0</span>,r<span class="sc">^</span><span class="dv">2</span>), <span class="at">ncol=</span>r)</span>
<span id="cb333-4"><a href="block-designs.html#cb333-4" tabindex="-1"></a></span>
<span id="cb333-5"><a href="block-designs.html#cb333-5" tabindex="-1"></a><span class="cf">for</span> (i1 <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>r) {</span>
<span id="cb333-6"><a href="block-designs.html#cb333-6" tabindex="-1"></a>  <span class="cf">for</span> (i2 <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>r) {</span>
<span id="cb333-7"><a href="block-designs.html#cb333-7" tabindex="-1"></a>    S.mat[i1,i2] <span class="ot">&lt;-</span> <span class="fu">cov</span>(pwd<span class="sc">$</span>corrRecall[pwd<span class="sc">$</span>trt.y <span class="sc">==</span> i1],pwd<span class="sc">$</span>corrRecall[pwd<span class="sc">$</span>trt.y <span class="sc">==</span> i2])</span>
<span id="cb333-8"><a href="block-designs.html#cb333-8" tabindex="-1"></a>  }</span>
<span id="cb333-9"><a href="block-designs.html#cb333-9" tabindex="-1"></a>}</span>
<span id="cb333-10"><a href="block-designs.html#cb333-10" tabindex="-1"></a></span>
<span id="cb333-11"><a href="block-designs.html#cb333-11" tabindex="-1"></a><span class="fu">round</span>(S.mat, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##         [,1]    [,2]    [,3]
## [1,] 975.803 607.759 532.015
## [2,] 607.759 764.172 568.676
## [3,] 532.015 568.676 681.475</code></pre>
<p>The Relative Efficiency is <span class="math inline">\(\hat{E}=3.32\)</span>, which can be interpreted as, if this had been run as a Completely Randomized Design, with each pilot being only observed in one condition, there would need to be <span class="math inline">\(b\hat{E}=23(3.32)=76.4\approx 77\)</span> pilots per treatment
(<span class="math inline">\(n_T=3(77)=231\)</span> total) to have comparable standard errors for contrasts. This is an efficient design.</p>
<p>While the variances range from 681 to 976, and the covariances range from 532 to 607,
there is no strong evidence that the Variance-Covariance matrix is far from the assumed model (standard deviations range from 26 to 31).</p>
<p><span class="math display">\[\nabla\]</span></p>
</div>
</div>
<div id="latin-square-designs" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Latin Square Designs<a href="block-designs.html#latin-square-designs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When there are two blocking factors, a <strong>Latin Square Design</strong> can be used.
There will be a row blocking factor, a column blocking factor, and the treatment factor.
In a “true” Latin Square, each factor will have the same number of levels <span class="math inline">\((r)\)</span>.
When <span class="math inline">\(r\)</span> is small, this will cause very low error degrees of freedom <span class="math inline">\(\left(df_E=(r-1)(r-2)\right)\)</span>, so typically either the row and/or column blocking factor may be replicated and have <span class="math inline">\(kr\)</span> levels, where <span class="math inline">\(k\)</span> is an integer value.</p>
<p>The key idea in the Latin Square is that each treatment appears once in each row, and once in each column. This way, we can directly remove row and column effects to get more precise estimates of the treatment effects and contrasts among them. An example of a Latin Square is given below with <span class="math inline">\(r=6\)</span>, where rows and columns are blocking factors and labels <span class="math inline">\(A,\ldots,F\)</span> are the treatments.</p>
<table>
<caption><span id="tab:ch0905">Table 10.1: </span>Latin Square Design (r=6)</caption>
<tbody>
<tr class="odd">
<td align="left">Row</td>
<td align="left">1</td>
<td align="left">2</td>
<td align="left">3</td>
<td align="left">4</td>
<td align="left">5</td>
<td align="left">6</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="left">A</td>
<td align="left">B</td>
<td align="left">C</td>
<td align="left">D</td>
<td align="left">E</td>
<td align="left">F</td>
</tr>
<tr class="odd">
<td align="left">2</td>
<td align="left">B</td>
<td align="left">C</td>
<td align="left">D</td>
<td align="left">E</td>
<td align="left">F</td>
<td align="left">A</td>
</tr>
<tr class="even">
<td align="left">3</td>
<td align="left">C</td>
<td align="left">D</td>
<td align="left">E</td>
<td align="left">F</td>
<td align="left">A</td>
<td align="left">B</td>
</tr>
<tr class="odd">
<td align="left">4</td>
<td align="left">D</td>
<td align="left">E</td>
<td align="left">F</td>
<td align="left">A</td>
<td align="left">B</td>
<td align="left">C</td>
</tr>
<tr class="even">
<td align="left">5</td>
<td align="left">E</td>
<td align="left">F</td>
<td align="left">A</td>
<td align="left">B</td>
<td align="left">C</td>
<td align="left">D</td>
</tr>
<tr class="odd">
<td align="left">6</td>
<td align="left">F</td>
<td align="left">A</td>
<td align="left">B</td>
<td align="left">C</td>
<td align="left">D</td>
<td align="left">E</td>
</tr>
</tbody>
</table>
<p>Keep in mind that while there are three factors, each with <span class="math inline">\(r\)</span> levels, there
are only <span class="math inline">\(r^2\)</span> observations. Once the row and columns have been indexed, there is only one treatment that appears. This can make writing the model confusing with an observation being <span class="math inline">\(Y_{ijk}\)</span>, because you cannot cycle through all three subscripts.</p>
<p>However, there are still <span class="math inline">\(r\)</span> means for each treatment, row, and column, each based on <span class="math inline">\(r\)</span> observations. Let <span class="math inline">\(T_{kl}\)</span> represent the measurement for the <span class="math inline">\(l^{th}\)</span> replicate when treatment <span class="math inline">\(k\)</span> is assigned, <span class="math inline">\(R_{il}\)</span> represent the <span class="math inline">\(l^{th}\)</span> replicate in row <span class="math inline">\(i\)</span>, and <span class="math inline">\(C_{jl}\)</span> represent the <span class="math inline">\(l^{th}\)</span> replicate in column <span class="math inline">\(j\)</span>. Further let <span class="math inline">\(\overline{Y}\)</span> represent the overall mean and <span class="math inline">\(SSTO\)</span> be the usual total sum of squares. We obtain the Analysis of Variance as follows (note that when using software packages, this is a trivial extension of the Randomized Block Design).</p>
<p><span class="math display">\[
\mbox{Total:} \quad SSTO = \sum_{\mbox{all data}}\left(Y-\overline{Y}\right)^2 \qquad
df_{TO}=r^2-1
\]</span></p>
<p><span class="math display">\[
\mbox{Treatments:} \quad \overline{T}_k=\frac{\sum_{l=1}^rT_{kl}}{r} \qquad
SSTR=r\sum_{k=1}^r\left(\overline{T}_k-\overline{Y}\right)^2 \qquad df_{TR}=r-1
\]</span>
<span class="math display">\[
\mbox{Rows:} \quad \overline{R}_i=\frac{\sum_{l=1}^rR_{il}}{r} \qquad
SSR=r\sum_{i=1}^r\left(\overline{R}_i-\overline{Y}\right)^2 \qquad df_{R}=r-1
\]</span>
<span class="math display">\[
\mbox{Columns:} \quad \overline{C}_j=\frac{\sum_{l=1}^rC_{jl}}{r} \qquad
SSC=r\sum_{j=1}^r\left(\overline{C}_j-\overline{Y}\right)^2 \qquad df_{C}=r-1
\]</span>
<span class="math display">\[
\mbox{Error:} \quad SSE = SSTO-SSTR-SSR-SSC
\]</span>
<span class="math display">\[
df_E =\left(r^2-1\right)-3(r-1)=(r+1)(r-1)-3(r-1)=
(r-1)[(r+1)-3]=(r-1)(r-2)
\]</span>
The usual <span class="math inline">\(F\)</span>-test for treatment effects and contrasts among treatment levels can be conducted as before. For instance, for Tukey’s HSD, we would compute the following values for the Honest Significant Difference and for simultaneous <span class="math inline">\((1-\alpha)100\%\)</span> Confidence Intervals. As in the RBD, these will all be based on common sample sizes <span class="math inline">\((r)\)</span>,
and <span class="math inline">\(\tau_k\)</span> is the treatment effect for treatment <span class="math inline">\(k\)</span>.</p>
<p><span class="math display">\[
HSD = q(1-\alpha;r,(r-1)(r-2))\sqrt{\frac{MSE}{r}}
\]</span>
<span class="math display">\[
(1-\alpha)100\% \mbox { Confidence Interval for } \tau_k-\tau_{k&#39;}:
\left(\overline{T}_k-\overline{T}_{k&#39;}\right) \pm HSD
\]</span></p>
<p><strong>Example 10.5 - Comparison of Medium (Psychic) Readings</strong></p>
<p>A study compared <span class="math inline">\(r=5\)</span> Psychic Mediums (treatments) in a Latin Square experiment <span class="citation">(<a href="#ref-okeeffe_2005">O’Keeffe and Wiseman 2005</a>)</span>.
We will treat Medium as a fixed factor (only interest is comparing these specific ones).
There were 5 Sitters (row factor) and 5 Sessions (column factor). Each Medium read each Sitter once, and each Medium read in each Session once. This design would look like the previous example, with one less row, one less column, and “F” removed.
We will do computations directly, then use the <strong>aov</strong> and <strong>TukeyHSD</strong> functions for the analysis. The response was <span class="math inline">\(Y\)</span>, the number of statements by the Medium on the Sitter.</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="block-designs.html#cb335-1" tabindex="-1"></a>mr <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/medium_reading.csv&quot;</span>)</span>
<span id="cb335-2"><a href="block-designs.html#cb335-2" tabindex="-1"></a><span class="fu">head</span>(mr)</span></code></pre></div>
<pre><code>##   session medium sitter statements rating
## 1       1      1      1         55   3.33
## 2       2      2      1         92   3.72
## 3       3      3      1          6   1.52
## 4       4      4      1         24   3.67
## 5       5      5      1         80   5.24
## 6       2      1      2         62   2.88</code></pre>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="block-designs.html#cb337-1" tabindex="-1"></a><span class="do">## Direct Calculation</span></span>
<span id="cb337-2"><a href="block-designs.html#cb337-2" tabindex="-1"></a>all.mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(mr<span class="sc">$</span>statements)</span>
<span id="cb337-3"><a href="block-designs.html#cb337-3" tabindex="-1"></a>trt.mean <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(mr<span class="sc">$</span>statements, mr<span class="sc">$</span>medium, mean))</span>
<span id="cb337-4"><a href="block-designs.html#cb337-4" tabindex="-1"></a>row.mean <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(mr<span class="sc">$</span>statements, mr<span class="sc">$</span>sitter, mean))</span>
<span id="cb337-5"><a href="block-designs.html#cb337-5" tabindex="-1"></a>col.mean <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(mr<span class="sc">$</span>statements, mr<span class="sc">$</span>session, mean))</span>
<span id="cb337-6"><a href="block-designs.html#cb337-6" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">length</span>(trt.mean)</span>
<span id="cb337-7"><a href="block-designs.html#cb337-7" tabindex="-1"></a></span>
<span id="cb337-8"><a href="block-designs.html#cb337-8" tabindex="-1"></a>SSTO <span class="ot">&lt;-</span> <span class="fu">sum</span>((mr<span class="sc">$</span>statements<span class="sc">-</span>all.mean)<span class="sc">^</span><span class="dv">2</span>); df_TO <span class="ot">&lt;-</span> r<span class="sc">^</span><span class="dv">2-1</span></span>
<span id="cb337-9"><a href="block-designs.html#cb337-9" tabindex="-1"></a>SSTR <span class="ot">&lt;-</span> r<span class="sc">*</span><span class="fu">sum</span>((trt.mean<span class="sc">-</span>all.mean)<span class="sc">^</span><span class="dv">2</span>);    df_TR <span class="ot">&lt;-</span> r<span class="dv">-1</span>; MSTR <span class="ot">&lt;-</span> SSTR<span class="sc">/</span>df_TR</span>
<span id="cb337-10"><a href="block-designs.html#cb337-10" tabindex="-1"></a>SSR <span class="ot">&lt;-</span> r<span class="sc">*</span><span class="fu">sum</span>((row.mean<span class="sc">-</span>all.mean)<span class="sc">^</span><span class="dv">2</span>);    df_R <span class="ot">&lt;-</span> r<span class="dv">-1</span>; MSR <span class="ot">&lt;-</span> SSR<span class="sc">/</span>df_R</span>
<span id="cb337-11"><a href="block-designs.html#cb337-11" tabindex="-1"></a>SSC <span class="ot">&lt;-</span> r<span class="sc">*</span><span class="fu">sum</span>((col.mean<span class="sc">-</span>all.mean)<span class="sc">^</span><span class="dv">2</span>);    df_C <span class="ot">&lt;-</span> r<span class="dv">-1</span>; MSC <span class="ot">&lt;-</span> SSC<span class="sc">/</span>df_C</span>
<span id="cb337-12"><a href="block-designs.html#cb337-12" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> SSTO<span class="sc">-</span>SSTR<span class="sc">-</span>SSR<span class="sc">-</span>SSC; df_E <span class="ot">&lt;-</span> (r<span class="dv">-1</span>)<span class="sc">*</span>(r<span class="dv">-2</span>); MSE <span class="ot">&lt;-</span> SSE<span class="sc">/</span>df_E</span>
<span id="cb337-13"><a href="block-designs.html#cb337-13" tabindex="-1"></a>Fstar <span class="ot">&lt;-</span> MSTR<span class="sc">/</span>MSE</span>
<span id="cb337-14"><a href="block-designs.html#cb337-14" tabindex="-1"></a>pF <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">pf</span>(Fstar, df_TR, df_E)</span>
<span id="cb337-15"><a href="block-designs.html#cb337-15" tabindex="-1"></a></span>
<span id="cb337-16"><a href="block-designs.html#cb337-16" tabindex="-1"></a>aov.out1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df_TR, SSTR, MSTR, Fstar, <span class="fu">qf</span>(.<span class="dv">95</span>,df_TR,df_E), pF)</span>
<span id="cb337-17"><a href="block-designs.html#cb337-17" tabindex="-1"></a>aov.out2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df_R, SSR, MSR, MSR<span class="sc">/</span>MSE, <span class="fu">qf</span>(.<span class="dv">95</span>,df_R,df_E), <span class="dv">1</span><span class="sc">-</span><span class="fu">pf</span>(MSR<span class="sc">/</span>MSE,df_R,df_E))</span>
<span id="cb337-18"><a href="block-designs.html#cb337-18" tabindex="-1"></a>aov.out3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df_C, SSC, MSC, MSC<span class="sc">/</span>MSE, <span class="fu">qf</span>(.<span class="dv">95</span>,df_C,df_E), <span class="dv">1</span><span class="sc">-</span><span class="fu">pf</span>(MSC<span class="sc">/</span>MSE,df_C,df_E))</span>
<span id="cb337-19"><a href="block-designs.html#cb337-19" tabindex="-1"></a>aov.out4 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df_E, SSE, MSE, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>)</span>
<span id="cb337-20"><a href="block-designs.html#cb337-20" tabindex="-1"></a>aov.out5 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df_TO, SSTO, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>)</span>
<span id="cb337-21"><a href="block-designs.html#cb337-21" tabindex="-1"></a>aov.out <span class="ot">&lt;-</span> <span class="fu">rbind</span>(aov.out1,aov.out2,aov.out3,aov.out4,aov.out5)</span>
<span id="cb337-22"><a href="block-designs.html#cb337-22" tabindex="-1"></a><span class="fu">colnames</span>(aov.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;df&quot;</span>, <span class="st">&quot;SS&quot;</span>, <span class="st">&quot;MS&quot;</span>, <span class="st">&quot;F*&quot;</span>, <span class="st">&quot;F(.95)&quot;</span>, <span class="st">&quot;P(&gt;F*)&quot;</span>)</span>
<span id="cb337-23"><a href="block-designs.html#cb337-23" tabindex="-1"></a><span class="fu">rownames</span>(aov.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Medium&quot;</span>, <span class="st">&quot;Sitter&quot;</span>, <span class="st">&quot;Session&quot;</span>, <span class="st">&quot;Error&quot;</span>, <span class="st">&quot;Total&quot;</span>)</span>
<span id="cb337-24"><a href="block-designs.html#cb337-24" tabindex="-1"></a><span class="fu">round</span>(aov.out,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##         df       SS      MS     F* F(.95) P(&gt;F*)
## Medium   4 17280.56 4320.14 55.006  3.259  0.000
## Sitter   4   205.76   51.44  0.655  3.259  0.635
## Session  4   231.76   57.94  0.738  3.259  0.584
## Error   12   942.48   78.54     NA     NA     NA
## Total   24 18660.56      NA     NA     NA     NA</code></pre>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="block-designs.html#cb339-1" tabindex="-1"></a>HSD <span class="ot">&lt;-</span> <span class="fu">qtukey</span>(.<span class="dv">95</span>,r,df_E) <span class="sc">*</span> <span class="fu">sqrt</span>(MSE<span class="sc">/</span>r)</span>
<span id="cb339-2"><a href="block-designs.html#cb339-2" tabindex="-1"></a>Tukey.out <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">8</span><span class="sc">*</span>r<span class="sc">*</span>(r<span class="dv">-1</span>)<span class="sc">/</span><span class="dv">2</span>),<span class="at">ncol=</span><span class="dv">8</span>)</span>
<span id="cb339-3"><a href="block-designs.html#cb339-3" tabindex="-1"></a></span>
<span id="cb339-4"><a href="block-designs.html#cb339-4" tabindex="-1"></a>row.count <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb339-5"><a href="block-designs.html#cb339-5" tabindex="-1"></a><span class="cf">for</span> (i1 <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>r) {</span>
<span id="cb339-6"><a href="block-designs.html#cb339-6" tabindex="-1"></a>  <span class="cf">for</span> (i2 <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(i1<span class="dv">-1</span>)) {</span>
<span id="cb339-7"><a href="block-designs.html#cb339-7" tabindex="-1"></a>    row.count <span class="ot">&lt;-</span> row.count <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb339-8"><a href="block-designs.html#cb339-8" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">1</span>] <span class="ot">&lt;-</span> i1</span>
<span id="cb339-9"><a href="block-designs.html#cb339-9" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">2</span>] <span class="ot">&lt;-</span> i2</span>
<span id="cb339-10"><a href="block-designs.html#cb339-10" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">3</span>] <span class="ot">&lt;-</span> trt.mean[i1]</span>
<span id="cb339-11"><a href="block-designs.html#cb339-11" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">4</span>] <span class="ot">&lt;-</span> trt.mean[i2]</span>
<span id="cb339-12"><a href="block-designs.html#cb339-12" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">5</span>] <span class="ot">&lt;-</span> trt.mean[i1] <span class="sc">-</span> trt.mean[i2]</span>
<span id="cb339-13"><a href="block-designs.html#cb339-13" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">6</span>] <span class="ot">&lt;-</span> Tukey.out[row.count,<span class="dv">5</span>] <span class="sc">-</span> HSD</span>
<span id="cb339-14"><a href="block-designs.html#cb339-14" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">7</span>] <span class="ot">&lt;-</span> Tukey.out[row.count,<span class="dv">5</span>] <span class="sc">+</span> HSD</span>
<span id="cb339-15"><a href="block-designs.html#cb339-15" tabindex="-1"></a>    Tukey.out[row.count,<span class="dv">8</span>] <span class="ot">&lt;-</span> </span>
<span id="cb339-16"><a href="block-designs.html#cb339-16" tabindex="-1"></a>      <span class="dv">1</span><span class="sc">-</span><span class="fu">ptukey</span>(<span class="fu">abs</span>(Tukey.out[row.count,<span class="dv">5</span>])<span class="sc">/</span><span class="fu">sqrt</span>(MSE<span class="sc">/</span>r),r,df_E)</span>
<span id="cb339-17"><a href="block-designs.html#cb339-17" tabindex="-1"></a>  }</span>
<span id="cb339-18"><a href="block-designs.html#cb339-18" tabindex="-1"></a>}</span>
<span id="cb339-19"><a href="block-designs.html#cb339-19" tabindex="-1"></a></span>
<span id="cb339-20"><a href="block-designs.html#cb339-20" tabindex="-1"></a><span class="fu">colnames</span>(Tukey.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;k&quot;</span>, <span class="st">&quot;k&#39;&quot;</span>, <span class="st">&quot;ybar_i&quot;</span>, <span class="st">&quot;ybar_i&#39;&quot;</span>, <span class="st">&quot;diff&quot;</span>,</span>
<span id="cb339-21"><a href="block-designs.html#cb339-21" tabindex="-1"></a>                         <span class="st">&quot;LB&quot;</span>, <span class="st">&quot;UB&quot;</span>, <span class="st">&quot;p adj&quot;</span>)</span>
<span id="cb339-22"><a href="block-designs.html#cb339-22" tabindex="-1"></a><span class="fu">round</span>(Tukey.out,<span class="dv">4</span>)</span></code></pre></div>
<pre><code>##       k k&#39; ybar_i ybar_i&#39;  diff       LB       UB  p adj
##  [1,] 2  1   75.4    59.8  15.6  -2.2656  33.4656 0.0983
##  [2,] 3  1    8.0    59.8 -51.8 -69.6656 -33.9344 0.0000
##  [3,] 3  2    8.0    75.4 -67.4 -85.2656 -49.5344 0.0000
##  [4,] 4  1   23.4    59.8 -36.4 -54.2656 -18.5344 0.0002
##  [5,] 4  2   23.4    75.4 -52.0 -69.8656 -34.1344 0.0000
##  [6,] 4  3   23.4     8.0  15.4  -2.4656  33.2656 0.1042
##  [7,] 5  1   67.2    59.8   7.4 -10.4656  25.2656 0.6848
##  [8,] 5  2   67.2    75.4  -8.2 -26.0656   9.6656 0.6026
##  [9,] 5  3   67.2     8.0  59.2  41.3344  77.0656 0.0000
## [10,] 5  4   67.2    23.4  43.8  25.9344  61.6656 0.0000</code></pre>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="block-designs.html#cb341-1" tabindex="-1"></a><span class="do">### aov and TukeyHSD functions</span></span>
<span id="cb341-2"><a href="block-designs.html#cb341-2" tabindex="-1"></a></span>
<span id="cb341-3"><a href="block-designs.html#cb341-3" tabindex="-1"></a>mr.mod1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(statements <span class="sc">~</span> <span class="fu">factor</span>(medium) <span class="sc">+</span> <span class="fu">factor</span>(sitter) <span class="sc">+</span> <span class="fu">factor</span>(session), <span class="at">data=</span>mr)</span>
<span id="cb341-4"><a href="block-designs.html#cb341-4" tabindex="-1"></a><span class="fu">anova</span>(mr.mod1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: statements
##                 Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
## factor(medium)   4 17280.6  4320.1 55.0056 1.28e-07 ***
## factor(sitter)   4   205.8    51.4  0.6550   0.6346    
## factor(session)  4   231.8    57.9  0.7377   0.5840    
## Residuals       12   942.5    78.5                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="block-designs.html#cb343-1" tabindex="-1"></a>HSD.med <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(mr.mod1, <span class="st">&quot;factor(medium)&quot;</span>)</span>
<span id="cb343-2"><a href="block-designs.html#cb343-2" tabindex="-1"></a>HSD.med</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = statements ~ factor(medium) + factor(sitter) + factor(session), data = mr)
## 
## $`factor(medium)`
##      diff        lwr        upr     p adj
## 2-1  15.6  -2.265551  33.465551 0.0983090
## 3-1 -51.8 -69.665551 -33.934449 0.0000069
## 4-1 -36.4 -54.265551 -18.534449 0.0002343
## 5-1   7.4 -10.465551  25.265551 0.6847850
## 3-2 -67.4 -85.265551 -49.534449 0.0000004
## 4-2 -52.0 -69.865551 -34.134449 0.0000066
## 5-2  -8.2 -26.065551   9.665551 0.6026044
## 4-3  15.4  -2.465551  33.265551 0.1042146
## 5-3  59.2  41.334449  77.065551 0.0000016
## 5-4  43.8  25.934449  61.665551 0.0000387</code></pre>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="block-designs.html#cb345-1" tabindex="-1"></a><span class="fu">plot</span>(HSD.med, <span class="at">las=</span><span class="dv">1</span>, <span class="at">cex.axis=</span><span class="fl">0.75</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_STA4211Notes1_files/figure-html/ch0906-1.png" width="672" /></p>
<p>There are highly significant differences among the mediums in terms of mean number of statements made. Of the 5(4)/2=10 pairs, six are significantly different based on Tukey’s HSD.</p>
<p><span class="math display">\[\nabla\]</span></p>

<pre><code>## Warning: package &#39;lmerTest&#39; was built under R version 4.5.3</code></pre>
<pre><code>## Loading required package: lme4</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## 
## Attaching package: &#39;lmerTest&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:lme4&#39;:
## 
##     lmer</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     step</code></pre>
</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-fidaleo_2012" class="csl-entry">
Fidaleo, M., M. Moresi, A. Cammaroto, M. Ladrange, and R. Nardi. 2012. <span>“Soy Sauce Desalting by Electrodialysis.”</span> <em>Journal of Food Engineering</em> 110: 175–81.
</div>
<div id="ref-ohare_2009" class="csl-entry">
O’Hare, D., and N. Stenhouse. 2009. <span>“Under the Weather: An Evaluation of Different Modes of Presenting Meteorological Information for Pilots.”</span> <em>Applied Ergonomics</em> 40: 688–93.
</div>
<div id="ref-okeeffe_2005" class="csl-entry">
O’Keeffe, C., and R. Wiseman. 2005. <span>“Testing Alleged Mediumship: Methods and Results.”</span> <em>British Journal of Psychology</em> 96: 165–79.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="higher-order-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="random-and-mixed-effects-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  },
  "link": "https://github.com/LarryWinner/STA4211-Notes1.git/edit/main/%s",
  "text": "Edit"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
